name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_1737"
    type: trojan
    server: "188.42.145.180"
    port: 443
    password: "humanity"
    sni: "www.volumeroot.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.volumeroot.com"
  - name: "@DeltaKroneckerGithub_1739"
    type: trojan
    server: "107.150.105.84"
    port: 43022
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1740"
    type: trojan
    server: "64.94.95.117"
    port: 57142
    password: "kkzh2prsyr2ik47as615"
    sni: "static.rutube.ru"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1741"
    type: trojan
    server: "82.117.245.125"
    port: 2053
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1743"
    type: trojan
    server: "107.150.105.84"
    port: 46292
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1744"
    type: trojan
    server: "185.18.250.252"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1746"
    type: trojan
    server: "185.255.179.166"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1748"
    type: trojan
    server: "z-sg2.251313.xyz"
    port: 10046
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1749"
    type: trojan
    server: "hk03.qianmoip.win"
    port: 50222
    password: "d742752c-4231-4695-801e-f06d77f0f277"
    sni: "taobao.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1750"
    type: trojan
    server: "edu.ruangguru.com"
    port: 443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
      headers:
        Host: "id1.nathaya.web.id"
  - name: "@DeltaKroneckerGithub_1752"
    type: trojan
    server: "45.130.125.112"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1754"
    type: trojan
    server: "107.150.105.84"
    port: 38261
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1755"
    type: trojan
    server: "z-sg1.251313.xyz"
    port: 10044
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1756"
    type: trojan
    server: "104.18.35.15"
    port: 443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1758"
    type: trojan
    server: "104.21.33.59"
    port: 443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
      headers:
        Host: "id1.nathaya.web.id"
  - name: "@DeltaKroneckerGithub_1760"
    type: trojan
    server: "104.21.83.135"
    port: 443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
      headers:
        Host: "id1.nathaya.web.id"
  - name: "@DeltaKroneckerGithub_1762"
    type: trojan
    server: "172.67.217.240"
    port: 443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
      headers:
        Host: "id1.nathaya.web.id"
  - name: "@DeltaKroneckerGithub_1764"
    type: trojan
    server: "139.59.238.97"
    port: 50573
    password: "pvZE3UfT0ziK1omVLlsjINBqeqqwab1M"
    sni: "139.59.238.97"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1765"
    type: trojan
    server: "172.64.152.23"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1767"
    type: trojan
    server: "172.64.152.241"
    port: 443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1769"
    type: trojan
    server: "89.150.34.41"
    port: 2053
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1771"
    type: trojan
    server: "47.250.84.25"
    port: 443
    password: "5931134d1cde66bf83a54acdfebe7ab2"
    sni: "moltbot.doctoroyy.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1772"
    type: trojan
    server: "64.94.95.115"
    port: 57142
    password: "kkzh2prsyr2ik47as615"
    sni: "static.rutube.ru"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1773"
    type: trojan
    server: "us01.duotg.top"
    port: 38261
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1774"
    type: trojan
    server: "us01.duotg.top"
    port: 54657
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1775"
    type: trojan
    server: "us01.duotg.top"
    port: 43022
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1776"
    type: trojan
    server: "34.131.228.210"
    port: 443
    password: "M7v%w11Se*"
    sni: "hyfuuf6.wsone.icu"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1777"
    type: trojan
    server: "100.42.228.109"
    port: 443
    password: "BxceQaOe"
    sni: "t.me/ripaojiedian"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1778"
    type: trojan
    server: "104.21.70.21"
    port: 443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
      headers:
        Host: "id1.nathaya.web.id"
  - name: "@DeltaKroneckerGithub_1780"
    type: trojan
    server: "194.9.172.236"
    port: 1105
    password: "kakashka13222"
    sni: "194.9.172.236"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1781"
    type: trojan
    server: "64.94.95.114"
    port: 57142
    password: "kkzh2prsyr2ik47as615"
    sni: "static.rutube.ru"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1782"
    type: trojan
    server: "104.17.122.10"
    port: 2083
    password: "123444"
    sni: "northrendserver.sherekontop.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "northrendserver.sherekontop.workers.dev"
  - name: "@DeltaKroneckerGithub_1784"
    type: trojan
    server: "107.150.105.84"
    port: 27732
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1785"
    type: trojan
    server: "us01.duotg.top"
    port: 20065
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1786"
    type: trojan
    server: "z-sg2.251313.xyz"
    port: 10044
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1787"
    type: trojan
    server: "206.1.96.244"
    port: 8443
    password: "yVnpewtJT__ErgqS-TI2dw"
    sni: "lunexhost.tolkun-tv.ru"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/Lunex"
      headers:
        Host: "lunexhost.tolkun-tv.ru"
  - name: "@DeltaKroneckerGithub_1789"
    type: trojan
    server: "64.94.95.118"
    port: 57142
    password: "kkzh2prsyr2ik47as615"
    sni: "static.rutube.ru"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1790"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "109.206.241.10"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1791"
    type: trojan
    server: "46.29.142.57"
    port: 4443
    password: "C0ldyfh-vpnjantit.com"
    sni: "hu2.vpnjantit.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1792"
    type: trojan
    server: "us01.duotg.top"
    port: 59385
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1793"
    type: trojan
    server: "107.150.105.84"
    port: 54657
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "us01.duotg.top"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1794"
    type: trojan
    server: "154.90.62.70"
    port: 56127
    password: "p5jTPcffLgi4gaNOJd2KUTb9YEPBBD5B"
    sni: "154.90.62.70"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1795"
    type: trojan
    server: "z-sg2.251313.xyz"
    port: 10045
    password: "ultra@kWZdAzt_IH593eGLRjdxnBZ0"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1796"
    type: trojan
    server: "88.99.189.60"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1798"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1799"
    type: trojan
    server: "172.67.176.157"
    port: 443
    password: "018b8e7b-7813-4dcb-84a5-3c98f1521e00"
    sni: "id1.nathaya.web.id"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/trojan"
      headers:
        Host: "id1.nathaya.web.id"
  - name: "@DeltaKroneckerGithub_1801"
    type: trojan
    server: "us01.duotg.top"
    port: 27732
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1802"
    type: trojan
    server: "104.21.33.59"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_1804"
    type: trojan
    server: "104.16.72.50"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1806"
    type: trojan
    server: "185.220.100.168"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1808"
    type: trojan
    server: "104.18.8.83"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1810"
    type: trojan
    server: "8.47.69.0"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_1812"
    type: trojan
    server: "104.17.121.43"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1814"
    type: trojan
    server: "104.16.72.2"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1816"
    type: trojan
    server: "166.1.36.83"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1818"
    type: trojan
    server: "104.16.72.41"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1820"
    type: trojan
    server: "193.233.87.41"
    port: 8443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1822"
    type: trojan
    server: "212.227.144.37"
    port: 8443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1824"
    type: trojan
    server: "45.130.125.190"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1826"
    type: trojan
    server: "185.225.68.232"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1828"
    type: trojan
    server: "107.150.105.84"
    port: 20065
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1829"
    type: trojan
    server: "us01.duotg.top"
    port: 46292
    password: "02cd3bac-2a78-4dbb-82b9-6b64084ddd8e"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_1737"
      - "@DeltaKroneckerGithub_1739"
      - "@DeltaKroneckerGithub_1740"
      - "@DeltaKroneckerGithub_1741"
      - "@DeltaKroneckerGithub_1743"
      - "@DeltaKroneckerGithub_1744"
      - "@DeltaKroneckerGithub_1746"
      - "@DeltaKroneckerGithub_1748"
      - "@DeltaKroneckerGithub_1749"
      - "@DeltaKroneckerGithub_1750"
      - "@DeltaKroneckerGithub_1752"
      - "@DeltaKroneckerGithub_1754"
      - "@DeltaKroneckerGithub_1755"
      - "@DeltaKroneckerGithub_1756"
      - "@DeltaKroneckerGithub_1758"
      - "@DeltaKroneckerGithub_1760"
      - "@DeltaKroneckerGithub_1762"
      - "@DeltaKroneckerGithub_1764"
      - "@DeltaKroneckerGithub_1765"
      - "@DeltaKroneckerGithub_1767"
      - "@DeltaKroneckerGithub_1769"
      - "@DeltaKroneckerGithub_1771"
      - "@DeltaKroneckerGithub_1772"
      - "@DeltaKroneckerGithub_1773"
      - "@DeltaKroneckerGithub_1774"
      - "@DeltaKroneckerGithub_1775"
      - "@DeltaKroneckerGithub_1776"
      - "@DeltaKroneckerGithub_1777"
      - "@DeltaKroneckerGithub_1778"
      - "@DeltaKroneckerGithub_1780"
      - "@DeltaKroneckerGithub_1781"
      - "@DeltaKroneckerGithub_1782"
      - "@DeltaKroneckerGithub_1784"
      - "@DeltaKroneckerGithub_1785"
      - "@DeltaKroneckerGithub_1786"
      - "@DeltaKroneckerGithub_1787"
      - "@DeltaKroneckerGithub_1789"
      - "@DeltaKroneckerGithub_1790"
      - "@DeltaKroneckerGithub_1791"
      - "@DeltaKroneckerGithub_1792"
      - "@DeltaKroneckerGithub_1793"
      - "@DeltaKroneckerGithub_1794"
      - "@DeltaKroneckerGithub_1795"
      - "@DeltaKroneckerGithub_1796"
      - "@DeltaKroneckerGithub_1798"
      - "@DeltaKroneckerGithub_1799"
      - "@DeltaKroneckerGithub_1801"
      - "@DeltaKroneckerGithub_1802"
      - "@DeltaKroneckerGithub_1804"
      - "@DeltaKroneckerGithub_1806"
      - "@DeltaKroneckerGithub_1808"
      - "@DeltaKroneckerGithub_1810"
      - "@DeltaKroneckerGithub_1812"
      - "@DeltaKroneckerGithub_1814"
      - "@DeltaKroneckerGithub_1816"
      - "@DeltaKroneckerGithub_1818"
      - "@DeltaKroneckerGithub_1820"
      - "@DeltaKroneckerGithub_1822"
      - "@DeltaKroneckerGithub_1824"
      - "@DeltaKroneckerGithub_1826"
      - "@DeltaKroneckerGithub_1828"
      - "@DeltaKroneckerGithub_1829"


rules:
  - MATCH,PROXY
