name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_1656"
    type: trojan
    server: "bright.bitgas.org"
    port: 443
    password: "UQfj7bdfjibTjpUHfg72aew51S7fB32g"
    sni: "bright.bitgas.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1657"
    type: trojan
    server: "104.18.8.83"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "//assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1659"
    type: trojan
    server: "154.90.62.70"
    port: 56127
    password: "p5jTPcffLgi4gaNOJd2KUTb9YEPBBD5B"
    sni: "154.90.62.70"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1660"
    type: trojan
    server: "104.21.13.204"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1662"
    type: trojan
    server: "hk03.qianmoip.win"
    port: 50222
    password: "d742752c-4231-4695-801e-f06d77f0f277"
    sni: "taobao.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1663"
    type: trojan
    server: "213.182.199.137"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_1665"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1666"
    type: trojan
    server: "172.64.152.23"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1668"
    type: trojan
    server: "45.205.0.6"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1670"
    type: trojan
    server: "188.42.145.180"
    port: 443
    password: "humanity"
    sni: "www.volumeroot.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.volumeroot.com"
  - name: "@DeltaKroneckerGithub_1672"
    type: trojan
    server: "8.47.69.0"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_1674"
    type: trojan
    server: "172.67.211.79"
    port: 443
    password: "Puj01Rc8UcA9IzcFcYOs8KMOhCz6aX2Q"
    sni: "mfyousheng.nl.eu.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tjwsLhx0SFASG4l9FERJ1g"
      headers:
        Host: "mfyousheng.nl.eu.org"
  - name: "@DeltaKroneckerGithub_1676"
    type: trojan
    server: "100.42.228.109"
    port: 443
    password: "BxceQaOe"
    sni: "t.me/ripaojiedian"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1677"
    type: trojan
    server: "172.64.152.241"
    port: 443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1679"
    type: trojan
    server: "45.130.125.112"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1681"
    type: trojan
    server: "64.20.209.125"
    port: 443
    password: "UQfj7bdfjibTjpUHfg72aew51S7fB32g"
    sni: "64.20.209.125"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1682"
    type: trojan
    server: "188.114.97.3"
    port: 443
    password: "Puj01Rc8UcA9IzcFcYOs8KMOhCz6aX2Q"
    sni: "mfyousheng.nl.eu.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tjwsLhx0SFASG4l9FERJ1g"
  - name: "@DeltaKroneckerGithub_1684"
    type: trojan
    server: "join.my.telegram.channel.cmliussss.to.unlock.more.premium.nodes.cf.090227.xyz"
    port: 443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1686"
    type: trojan
    server: "104.21.33.59"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_1688"
    type: trojan
    server: "104.18.35.15"
    port: 443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1690"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "russiapower.accesscam.org"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1691"
    type: trojan
    server: "47.250.84.25"
    port: 443
    password: "5931134d1cde66bf83a54acdfebe7ab2"
    sni: "moltbot.doctoroyy.net"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1692"
    type: trojan
    server: "185.220.100.168"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1694"
    type: trojan
    server: "195.181.244.216"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1696"
    type: trojan
    server: "78.47.146.151"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "@DeltaKroneckerGithub_1698"
    type: trojan
    server: "104.17.121.71"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1700"
    type: trojan
    server: "188.114.98.0"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1702"
    type: trojan
    server: "162.159.36.20"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1704"
    type: trojan
    server: "chatgpt.com"
    port: 443
    password: "Puj01Rc8UcA9IzcFcYOs8KMOhCz6aX2Q"
    sni: "mfyousheng.nl.eu.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tjwsLhx0SFASG4l9FERJ1g"
  - name: "@DeltaKroneckerGithub_1706"
    type: trojan
    server: "185.255.179.166"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1708"
    type: trojan
    server: "162.159.91.211"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1710"
    type: trojan
    server: "91.245.225.79"
    port: 2053
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_1656"
      - "@DeltaKroneckerGithub_1657"
      - "@DeltaKroneckerGithub_1659"
      - "@DeltaKroneckerGithub_1660"
      - "@DeltaKroneckerGithub_1662"
      - "@DeltaKroneckerGithub_1663"
      - "@DeltaKroneckerGithub_1665"
      - "@DeltaKroneckerGithub_1666"
      - "@DeltaKroneckerGithub_1668"
      - "@DeltaKroneckerGithub_1670"
      - "@DeltaKroneckerGithub_1672"
      - "@DeltaKroneckerGithub_1674"
      - "@DeltaKroneckerGithub_1676"
      - "@DeltaKroneckerGithub_1677"
      - "@DeltaKroneckerGithub_1679"
      - "@DeltaKroneckerGithub_1681"
      - "@DeltaKroneckerGithub_1682"
      - "@DeltaKroneckerGithub_1684"
      - "@DeltaKroneckerGithub_1686"
      - "@DeltaKroneckerGithub_1688"
      - "@DeltaKroneckerGithub_1690"
      - "@DeltaKroneckerGithub_1691"
      - "@DeltaKroneckerGithub_1692"
      - "@DeltaKroneckerGithub_1694"
      - "@DeltaKroneckerGithub_1696"
      - "@DeltaKroneckerGithub_1698"
      - "@DeltaKroneckerGithub_1700"
      - "@DeltaKroneckerGithub_1702"
      - "@DeltaKroneckerGithub_1704"
      - "@DeltaKroneckerGithub_1706"
      - "@DeltaKroneckerGithub_1708"
      - "@DeltaKroneckerGithub_1710"


rules:
  - MATCH,PROXY
