name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_3650"
    type: ss
    server: "108.181.118.10"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "G5p6ww4o67HB"
    udp: true
  - name: "@DeltaKroneckerGithub_2741"
    type: trojan
    server: "better-molly.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "better-molly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_756"
    type: vless
    server: "172.64.52.230"
    port: 2087
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "faxf32gkfzoxqv.fx6hsv0.ccwu.cc"
  - name: "@DeltaKroneckerGithub_106"
    type: vless
    server: "213.165.39.193"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node4.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_2695"
    type: trojan
    server: "104.17.121.9"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_789"
    type: vless
    server: "107.151.250.183"
    port: 443
    uuid: "4caaaae0-516b-4026-b2b2-69fea69df19a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "LDpWYUJjGRJomvaN-gfgY96EJOF2DDHiFcNPEBLtoW0"
      short-id: "9019bbea8ff8781e"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_1686"
    type: vless
    server: "172.239.26.184"
    port: 17780
    uuid: "a06119a7-4f1a-4592-86d9-e050a332b2b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "amp-api-edge.apps.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CHNEnURyZzZ1OQwb5SD2Ze8K9eIY2oggyrV5FOIsU28"
      short-id: "a0fbc54d937aaccb"
  - name: "@DeltaKroneckerGithub_78"
    type: vless
    server: "144.31.87.16"
    port: 2096
    uuid: "c40f773e-3b96-417e-b22c-e48cb63ca7d9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.avito.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HdIk7jX58DtK-PGVKoU587O4w1KrDiej1qz8J2SmRA8"
      short-id: "a7bf40db1b0e566a"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "@DeltaKroneckerGithub_3155"
    type: ss
    server: "194.87.47.162"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true
  - name: "@DeltaKroneckerGithub_1104"
    type: vless
    server: "138.124.4.128"
    port: 443
    uuid: "553de958-b515-4e0d-b39c-943b5f8d86c2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "q6kGq9xjd1-dpAYhM3UNUQ_H424z2ZFLF-3txqvpaQ4"
      short-id: "5edc2176"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_2003"
    type: vless
    server: "72.56.8.87"
    port: 443
    uuid: "afa92127-9235-4f03-9663-5eaef3f3d7bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "jqvmkS71kRIg4vycIPj0vNlb_COI6K8hILmNwHp-xj4"
      short-id: "cdb849205ccb59b0"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_911"
    type: vless
    server: "104.16.7.70"
    port: 443
    uuid: "03707fb7-0990-440f-88f6-b0e0f7242a38"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "de-new.ariyuz.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_3138"
    type: ss
    server: "185.226.172.8"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "@DeltaKroneckerGithub_3428"
    type: ss
    server: "156.146.38.169"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_2866"
    type: trojan
    server: "concise-bass.rooster465.autos"
    port: 443
    password: "EQ30679154"
    sni: "concise-bass.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_2298"
    type: trojan
    server: "primary-leech.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "primary-leech.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1572"
    type: vless
    server: "31.58.50.200"
    port: 8443
    uuid: "db381c11-9dc4-4689-b654-a8159598e16d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mr5AF0LFyDzYDRoYAwH6QNcHXL77-LoiwRx50ZzU8QU"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_65"
    type: vless
    server: "www.visa.com.sg"
    port: 8880
    uuid: "d8235de7-84c7-4454-b333-4d854c393929"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "fragrant-butterfly-3e76.387.workers.dev"
  - name: "@DeltaKroneckerGithub_1666"
    type: vless
    server: "150.241.82.19"
    port: 13443
    uuid: "b80b392c-0cf4-42f9-ae54-9f862e3ba276"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "auto.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "gc9oXe37KCCm3J1dJ03wdGsnxPBdeEkRPOvl_t-vfVM"
      short-id: "a7f3c91b2e6d84c0"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_2773"
    type: trojan
    server: "13.114.100.100"
    port: 443
    password: "FH72359861"
    sni: "pleased-sawfly.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3042"
    type: ss
    server: "82.38.31.203"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_762"
    type: vless
    server: "31.58.181.88"
    port: 8443
    uuid: "18b3f812-142c-494e-aeea-f60e264f9cc6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "AERbWB2uslqIzm1hSlOZZEH3Y9qg_zlWRRyLfh97kXc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_954"
    type: vless
    server: "derman.neobo-tooth.ru"
    port: 2053
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "6RshLCSAs31qGRa_tWi63KClbh2Kzj9ooXpdaPJKbjs"
      short-id: "a6bbc4aecf5d961f"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_25"
    type: vless
    server: "104.17.171.60"
    port: 2083
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso6.1d.mom"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_2392"
    type: trojan
    server: "fun-poodle.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "fun-poodle.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_2727"
    type: trojan
    server: "definite-ladybird.rooster465.autos"
    port: 443
    password: "UO36402987"
    sni: "definite-ladybird.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_2930"
    type: trojan
    server: "concise-bass.rooster465.autos"
    port: 443
    password: "PQ05174892"
    sni: "concise-bass.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3359"
    type: ss
    server: "193.29.139.144"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_2948"
    type: trojan
    server: "up-dinosaur.rooster465.autos"
    port: 443
    password: "FH72359861"
    sni: "up-dinosaur.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1192"
    type: vless
    server: "5.180.40.9"
    port: 443
    uuid: "5e19b3c8-c1dc-4163-95e2-895319c15d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cloud.mail.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "06GvG7PU5F3Hgq-vUH24tU0tpsbGMCCt26BSvlaBNUE"
      short-id: "dfbfa87e9f37f1f0"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_3617"
    type: ss
    server: "82.38.31.11"
    port: 443
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_1191"
    type: vless
    server: "fv2026.node2.top"
    port: 21001
    uuid: "5f369953-0f06-4f80-802e-2901a7a044a9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "itunes.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HWUNFHoOryJHQXKF-ZOm6wMYZdVJwH5aHGa5I9_HDGA"
      short-id: "dfa28122"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_1820"
    type: vless
    server: "86.54.28.75"
    port: 443
    uuid: "44ae52b9-76fc-444d-8e43-186b4384b80a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PryGoq51ilG0eLUPl9i0xCvmk1xpwkyFSr_tG4GNLlU"
      short-id: "1d86d17709852910"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_2292"
    type: trojan
    server: "18.182.55.209"
    port: 443
    password: "PQ05174892"
    sni: "prime-quail.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3108"
    type: ss
    server: "ca4.levikogjgfdd.ir"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "FD3rCuOsxOay"
    udp: true
  - name: "@DeltaKroneckerGithub_386"
    type: vless
    server: "139.64.235.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "@DeltaKroneckerGithub_643"
    type: vless
    server: "fv2026.node2.top"
    port: 21001
    uuid: "1f1401c8-bc59-44bd-919e-a7bed908a9f9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "itunes.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HWUNFHoOryJHQXKF-ZOm6wMYZdVJwH5aHGa5I9_HDGA"
      short-id: "dfa28122"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_1596"
    type: vless
    server: "162.35.231.61"
    port: 443
    uuid: "b5ca5ab3-8cbc-4ac3-89da-9cd360589ecb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "savesafe.co"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "6z3YcVP0f2pK3iANKIkBUZOgNeErDjxY83mHZG5jrnI"
      short-id: "f63805c3ecc7a483"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_3287"
    type: ss
    server: "82.38.31.13"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_1826"
    type: vless
    server: "rm-jp-01.409648.xyz"
    port: 20725
    uuid: "6dcb725e-947e-4bbe-bb35-903374d57179"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "buylite.tv.apple.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "hceZHd9X9FSbWGXGgm3OWN-4Au26rrsriTcyHw5M3VU"
      short-id: "0102ac4e"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_3650"
      - "@DeltaKroneckerGithub_2741"
      - "@DeltaKroneckerGithub_756"
      - "@DeltaKroneckerGithub_106"
      - "@DeltaKroneckerGithub_2695"
      - "@DeltaKroneckerGithub_789"
      - "@DeltaKroneckerGithub_1686"
      - "@DeltaKroneckerGithub_78"
      - "@DeltaKroneckerGithub_3155"
      - "@DeltaKroneckerGithub_1104"
      - "@DeltaKroneckerGithub_2003"
      - "@DeltaKroneckerGithub_911"
      - "@DeltaKroneckerGithub_3138"
      - "@DeltaKroneckerGithub_3428"
      - "@DeltaKroneckerGithub_2866"
      - "@DeltaKroneckerGithub_2298"
      - "@DeltaKroneckerGithub_1572"
      - "@DeltaKroneckerGithub_65"
      - "@DeltaKroneckerGithub_1666"
      - "@DeltaKroneckerGithub_2773"
      - "@DeltaKroneckerGithub_3042"
      - "@DeltaKroneckerGithub_762"
      - "@DeltaKroneckerGithub_954"
      - "@DeltaKroneckerGithub_25"
      - "@DeltaKroneckerGithub_2392"
      - "@DeltaKroneckerGithub_2727"
      - "@DeltaKroneckerGithub_2930"
      - "@DeltaKroneckerGithub_3359"
      - "@DeltaKroneckerGithub_2948"
      - "@DeltaKroneckerGithub_1192"
      - "@DeltaKroneckerGithub_3617"
      - "@DeltaKroneckerGithub_1191"
      - "@DeltaKroneckerGithub_1820"
      - "@DeltaKroneckerGithub_2292"
      - "@DeltaKroneckerGithub_3108"
      - "@DeltaKroneckerGithub_386"
      - "@DeltaKroneckerGithub_643"
      - "@DeltaKroneckerGithub_1596"
      - "@DeltaKroneckerGithub_3287"
      - "@DeltaKroneckerGithub_1826"


rules:
  - MATCH,PROXY
