name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_3743"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_362"
    type: vless
    server: "188.114.97.6"
    port: 443
    uuid: "65aed3c1-1999-46a1-a3f3-2e5eb119ec64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "weathered-hat-76a5.380-d00.workers.dev"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "weathered-hat-76a5.380-d00.workers.dev"
  - name: "@DeltaKroneckerGithub_3546"
    type: trojan
    server: "104.21.4.176"
    port: 443
    password: "Telegram_healer_config"
    sni: "5Er0m2i2eNS2uLpg7SJd45UGqS.87fcvT2k11501YnO2TXm6yw-miPJ2Kr.worKerS.deV"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/tr/5cJhuZZi5ZL6KKmZ5vKVeM?ed=2560"
  - name: "@DeltaKroneckerGithub_3883"
    type: ss
    server: "156.146.38.169"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_4458"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_4380"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_4053"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_1641"
    type: vless
    server: "108.162.198.178"
    port: 2086
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_3793"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_4462"
    type: ss
    server: "82.38.31.192"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "k1dBOmOB4oqi7Ump37a1bQ"
    udp: true
  - name: "@DeltaKroneckerGithub_2295"
    type: vless
    server: "deepl.com"
    port: 8880
    uuid: "f15a5586-23f6-453f-97f5-c301b949e699"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "mute-sunset-0849.40-aeb.workers.dev"
  - name: "@DeltaKroneckerGithub_161"
    type: vless
    server: "34.3.101.206"
    port: 443
    uuid: "c64a5cfa-0fd6-4978-b062-6e89da013260"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gateway.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "C4ky4RduL1cfjZ3okHXDkpD2Ns4DViMkB-mDlisBrzc"
      short-id: "8a17287288cf25e5"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_2505"
    type: vless
    server: "104.21.0.115"
    port: 8880
    uuid: "8995976a-1c81-4b44-a414-d3bc71058a21"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "muddy-queen-cdda.181-cf9.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_3743"
      - "@DeltaKroneckerGithub_362"
      - "@DeltaKroneckerGithub_3546"
      - "@DeltaKroneckerGithub_3883"
      - "@DeltaKroneckerGithub_4458"
      - "@DeltaKroneckerGithub_4380"
      - "@DeltaKroneckerGithub_4053"
      - "@DeltaKroneckerGithub_1641"
      - "@DeltaKroneckerGithub_3793"
      - "@DeltaKroneckerGithub_4462"
      - "@DeltaKroneckerGithub_2295"
      - "@DeltaKroneckerGithub_161"
      - "@DeltaKroneckerGithub_2505"


rules:
  - MATCH,PROXY
