name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_2973"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "0432902e-6604-40cd-bbd0-57ab4e5d909f"
    udp: true
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiOENNZnB6WTgiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119"
      headers:
        Host: "bpb-4dc4958b.hxjkcghchv.workers.dev"
  - name: "@DeltaKroneckerGithub_4495"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_1395"
    type: vless
    server: "sc-thenetherlands2.09vpn.com"
    port: 80
    uuid: "e73df646-1f62-41bf-8c50-653497d603d0"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "SC-TheNetherlands2.09vpn.com"
  - name: "@DeltaKroneckerGithub_3888"
    type: ss
    server: "156.146.38.169"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_2872"
    type: vless
    server: "62.60.159.81"
    port: 2053
    uuid: "fc00adfb-232a-46ce-8b93-0c70e516aa8a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "ygmJxS-Mc7g0buNSUTVGhazT-FoBjyYtLLfUYIQxFTw"
      short-id: "d0ea1847066af5a6"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpce5bb9e71"
  - name: "@DeltaKroneckerGithub_832"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "7242eccf-5261-4e31-813e-871bfbde90c2"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.JP.CMLiussss.net"
      headers:
        Host: "long-flower-ac0d.176-17e.workers.dev"
  - name: "@DeltaKroneckerGithub_234"
    type: vless
    server: "172.67.222.62"
    port: 443
    uuid: "ea50b1a3-3a98-4c5e-a150-48ada40d68d7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cf-vless-4cf55824.aimall.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/connect"
      headers:
        Host: "cf-vless-4cf55824.aimall.fr"
  - name: "@DeltaKroneckerGithub_1919"
    type: vless
    server: "skk.moe"
    port: 8880
    uuid: "160ca353-676d-4b7f-a041-0289e388b865"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "proud-cloud-7bdd.208-a52.workers.dev"
  - name: "@DeltaKroneckerGithub_1688"
    type: vless
    server: "172.67.213.26"
    port: 2053
    uuid: "52450a53-ac49-42ff-be36-0899178d34b9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "little-violet-8ade.vpnstoregod.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiOHBjT0w3NmxvazAiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByZWZpeCIsInBhbmVsSVBzIjpbIlsyYTAyOjg5ODoxNDY6NjQ6Ol0iXX0="
      headers:
        Host: "little-violet-8ade.vpnstoregod.workers.dev"
  - name: "@DeltaKroneckerGithub_3308"
    type: vless
    server: "60.248.219.53"
    port: 443
    uuid: "c1c04450-bf71-4049-ad0c-9cf6d94d9f1f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "@DeltaKroneckerGithub_1434"
    type: vless
    server: "www.zsu.gov.ua"
    port: 8880
    uuid: "667a035b-6656-4a4f-a74c-8cd6a679f8d4"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "winter-mode-7f4e.89-136.workers.dev"
  - name: "@DeltaKroneckerGithub_4044"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "@DeltaKroneckerGithub_3553"
    type: trojan
    server: "45.205.0.6"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_2266"
    type: vless
    server: "www.iplocation.net"
    port: 8880
    uuid: "878dd962-027b-4bd3-a1f8-66be68a03c4d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "young-wind-3c58.240-2ce.workers.dev"
  - name: "@DeltaKroneckerGithub_1696"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "fc60147e-76b8-4bc5-b691-90b2da79e3d2"
    udp: true
    network: ws
    ws-opts:
      path: "/138.2.74.219-28616"
      headers:
        Host: "nautica-cff.kloningstrife002.workers.dev"
  - name: "@DeltaKroneckerGithub_1782"
    type: vless
    server: "172.67.179.98"
    port: 8880
    uuid: "81b3fa7e-12b0-4c2b-9866-324edd26ef7f"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "falling-lake-0b5a.192-3e2.workers.dev"
  - name: "@DeltaKroneckerGithub_3721"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_79"
    type: vless
    server: "nasnet-162191099-direct.mbghalibaf.com"
    port: 443
    uuid: "e8b1500b-e9e8-5492-8312-f4eadf7d0767"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_3514"
    type: trojan
    server: "31.77.168.35"
    port: 443
    password: "MDYVt6HgSqB7d537GPQXjk6Rk0E4RxWo"
    sni: "d3-de2.cloud-cdn.xyz"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "ajv"
  - name: "@DeltaKroneckerGithub_1677"
    type: vless
    server: "188.114.97.6"
    port: 443
    uuid: "645ea5d2-7d0a-4d66-940d-eefc2b84f4e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fragrant-surf-4797.496-345.workers.dev"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "fragrant-surf-4797.496-345.workers.dev"
  - name: "@DeltaKroneckerGithub_3980"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_4553"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_2676"
    type: vless
    server: "free-amsterdam-node-1.cloudwidecdn.com"
    port: 443
    uuid: "44ae52b9-76fc-444d-8e43-186b4384b80a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PryGoq51ilG0eLUPl9i0xCvmk1xpwkyFSr_tG4GNLlU"
      short-id: "1d86d17709852910"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_640"
    type: vless
    server: "104.18.47.113"
    port: 8080
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_3005"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "def8ed1e-e07b-40e0-9bc0-7a2ba2cedd56"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.US.CMLiussss.net"
      headers:
        Host: "lucky-haze-724d.330-8c5.workers.dev"
  - name: "@DeltaKroneckerGithub_1947"
    type: vless
    server: "104.26.6.214"
    port: 8880
    uuid: "565326ee-c588-4843-9472-a051578ab1ae"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.KR.CMLiussss.net"
      headers:
        Host: "lucky-cell-e8c5.490-f12.workers.dev"
  - name: "@DeltaKroneckerGithub_4525"
    type: ss
    server: "156.146.38.168"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "@DeltaKroneckerGithub_3634"
    type: trojan
    server: "34.94.125.227"
    port: 443
    password: "M7v%w11Se*"
    sni: "mxlo.wsone.icu"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_3735"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_2025"
    type: vless
    server: "94.156.79.93"
    port: 443
    uuid: "d6752c6b-80ae-4a91-b446-bb330f7f8177"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.foxsports.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_0fpFqEEuCso3B8K7AAcMjctwG_xfCxO2PdKzGd_-hg"
      short-id: "88a13cf2655c"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_2442"
    type: vless
    server: "188.114.97.6"
    port: 443
    uuid: "daf485ba-60fc-4166-a72c-8d2a5407cbc5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kievh9yxcgg14-gy4wxqcav0pegkd.d-0ezpk5xp5wk8ltdgb6evlpgc-jin.workers.dev"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/vl/zM8ELyqEIYeZ3ijacV9kuK?ed"
      headers:
        Host: "kievh9yxcgg14-gy4wxqcav0pegkd.d-0ezpk5xp5wk8ltdgb6evlpgc-jin.workers.dev"
  - name: "@DeltaKroneckerGithub_2327"
    type: vless
    server: "courses.mftplus.qzz.io"
    port: 2096
    uuid: "b9ede7a5-5b4b-4aee-ac37-2c307e587e47"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "courses.mftplus.qzz.io"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoidVkzQm1ROUg4dyIsInByb3RvY29sIjoidmwiLCJtb2RlIjoicHJveHlpcCIsInBhbmVsSVBzIjpbXX0="
      headers:
        Host: "courses.mftplus.qzz.io"
  - name: "@DeltaKroneckerGithub_853"
    type: vless
    server: "188.114.97.6"
    port: 8080
    uuid: "9f4b666c-ecf1-49e9-8ab8-9ae2c4f4c613"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "withered-morning-aa51.64-c79.workers.dev"
  - name: "@DeltaKroneckerGithub_4382"
    type: ss
    server: "45.149.114.171"
    port: 777
    cipher: "chacha20-ietf-poly1305"
    password: "Jeoq8ujfkqZKKvACQhoqBQ1PA3uq4242"
    udp: true
  - name: "@DeltaKroneckerGithub_3305"
    type: vless
    server: "103.30.76.197"
    port: 21263
    uuid: "57beeeb0-03fc-4fc9-94da-7604488a7134"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us1p1.xn--ghq880n3na965a.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "YinI5MijeZpRatg6QNDvP0qXEif-6VHC6gV5yoji4i4"
      short-id: "3d31326f95"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_3479"
    type: trojan
    server: "104.16.7.70"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_4030"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_828"
    type: vless
    server: "104.16.10.21"
    port: 443
    uuid: "c4edb87e-8544-4fa4-bd1c-b0cda9a34b46"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "a.cwvps.eu.org"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "a.cwvps.eu.org"
  - name: "@DeltaKroneckerGithub_1850"
    type: vless
    server: "188.114.96.1"
    port: 443
    uuid: "af0db32b-2cb0-48c7-b04e-96003f8c2369"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "Dl2Uf-IVdEzILz3e86Rk18.hhVT37TJm2xbOSql5hxOgN-Y.woRKers.DeV"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vl/WzJrIU8RBLiKEwHrtTJL2XpzurfIundt?ed=2560"
      headers:
        Host: "dl2uf-ivdezilz3e86rk18.hhvt37tjm2xbosql5hxogn-y.workers.dev"
  - name: "@DeltaKroneckerGithub_2158"
    type: vless
    server: "94.159.106.205"
    port: 443
    uuid: "4b21fbc7-00c2-4665-9788-02153832f9e5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "v2ray.aizgl.com"
    client-fingerprint: "android"
    network: ws
    ws-opts:
      path: "/xray-ws"
      headers:
        Host: "v2ray.aizgl.com"
  - name: "@DeltaKroneckerGithub_1105"
    type: vless
    server: "172.64.42.85"
    port: 2095
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560security=tls"
      headers:
        Host: "8nj2r.2k8t.f88.hh.vavava.kdns.fr"
  - name: "@DeltaKroneckerGithub_1474"
    type: vless
    server: "104.18.12.229"
    port: 8880
    uuid: "35b94b2c-1b46-4209-a04b-32ecf159b632"
    udp: true
    network: ws
    ws-opts:
      path: "/pyip=ProxyIP.SG.CMLiussss.net"
      headers:
        Host: "fragrant-tooth-2180.97-cbb.workers.dev"
  - name: "@DeltaKroneckerGithub_3377"
    type: trojan
    server: "31.77.168.21"
    port: 443
    password: "MDYVt6HgSqB7d537GPQXjk6Rk0E4RxWo"
    sni: "d3-de2.cloud-cdn.xyz"
    skip-cert-verify: true
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "ajv"
  - name: "@DeltaKroneckerGithub_291"
    type: vless
    server: "5.161.203.24"
    port: 4000
    uuid: "83db8840-0d41-4a23-9ec3-682380924eb5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play.googleapis.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gNJZix6GHGuB246_yD6n0EQQY-6Vb1zXg3ipjnubawE"
      short-id: "6d66b2bd572f34fb"
  - name: "@DeltaKroneckerGithub_3713"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_3212"
    type: vless
    server: "104.21.70.21"
    port: 443
    uuid: "d7ec3e31-a9c4-4bdf-a2d8-7f75a8381035"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "weathered-lake-e883.35-bc4.workers.dev"
    client-fingerprint: "unsafe"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "weathered-lake-e883.35-bc4.workers.dev"
  - name: "@DeltaKroneckerGithub_4426"
    type: ss
    server: "82.38.31.155"
    port: 8080
    cipher: "chacha20-ietf-poly1305"
    password: "oZIoA69Q8yhcQV8ka3Pa3A"
    udp: true
  - name: "@DeltaKroneckerGithub_3570"
    type: trojan
    server: "63.178.198.94"
    port: 443
    password: "UX82473651"
    sni: "pleased-albacore.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub_1646"
    type: vless
    server: "169.40.42.163"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_3078"
    type: vless
    server: "xray2-direct-mci1-fs-ce.freesocks.work"
    port: 443
    uuid: "4dc2ee98-b5b7-4aeb-ab95-fcefa87856ee"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7j3hmlHrEDk3Kjx-dFG3E3jf0c6PZF45trIPFsuKWmI"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "@DeltaKroneckerGithub_1158"
    type: vless
    server: "free.server7peekconfig.workers.dev"
    port: 443
    uuid: "682d30e4-3dfc-49f2-a017-9049119e3497"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "FrEE.sErVeR7PeEKcONfig.WoRKErS.deV"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiRm5kaUkxZVFtRVJBIiwicHJvdG9jb2wiOiJ2bCIsIm1vZGUiOiJwcmVmaXgiLCJwYW5lbElQcyI6WyJbMmEwMjo4OTg6MTQ2OjY0OjpdIl19?ed=2560"
      headers:
        Host: "free.server7peekconfig.workers.dev"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_2973"
      - "@DeltaKroneckerGithub_4495"
      - "@DeltaKroneckerGithub_1395"
      - "@DeltaKroneckerGithub_3888"
      - "@DeltaKroneckerGithub_2872"
      - "@DeltaKroneckerGithub_832"
      - "@DeltaKroneckerGithub_234"
      - "@DeltaKroneckerGithub_1919"
      - "@DeltaKroneckerGithub_1688"
      - "@DeltaKroneckerGithub_3308"
      - "@DeltaKroneckerGithub_1434"
      - "@DeltaKroneckerGithub_4044"
      - "@DeltaKroneckerGithub_3553"
      - "@DeltaKroneckerGithub_2266"
      - "@DeltaKroneckerGithub_1696"
      - "@DeltaKroneckerGithub_1782"
      - "@DeltaKroneckerGithub_3721"
      - "@DeltaKroneckerGithub_79"
      - "@DeltaKroneckerGithub_3514"
      - "@DeltaKroneckerGithub_1677"
      - "@DeltaKroneckerGithub_3980"
      - "@DeltaKroneckerGithub_4553"
      - "@DeltaKroneckerGithub_2676"
      - "@DeltaKroneckerGithub_640"
      - "@DeltaKroneckerGithub_3005"
      - "@DeltaKroneckerGithub_1947"
      - "@DeltaKroneckerGithub_4525"
      - "@DeltaKroneckerGithub_3634"
      - "@DeltaKroneckerGithub_3735"
      - "@DeltaKroneckerGithub_2025"
      - "@DeltaKroneckerGithub_2442"
      - "@DeltaKroneckerGithub_2327"
      - "@DeltaKroneckerGithub_853"
      - "@DeltaKroneckerGithub_4382"
      - "@DeltaKroneckerGithub_3305"
      - "@DeltaKroneckerGithub_3479"
      - "@DeltaKroneckerGithub_4030"
      - "@DeltaKroneckerGithub_828"
      - "@DeltaKroneckerGithub_1850"
      - "@DeltaKroneckerGithub_2158"
      - "@DeltaKroneckerGithub_1105"
      - "@DeltaKroneckerGithub_1474"
      - "@DeltaKroneckerGithub_3377"
      - "@DeltaKroneckerGithub_291"
      - "@DeltaKroneckerGithub_3713"
      - "@DeltaKroneckerGithub_3212"
      - "@DeltaKroneckerGithub_4426"
      - "@DeltaKroneckerGithub_3570"
      - "@DeltaKroneckerGithub_1646"
      - "@DeltaKroneckerGithub_3078"
      - "@DeltaKroneckerGithub_1158"


rules:
  - MATCH,PROXY
