name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "@DeltaKroneckerGithub_1821"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1825"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1828"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1832"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1835"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1838"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1842"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1845"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1847"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1849"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1851"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1853"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1856"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1858"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1861"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1863"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1866"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1869"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1871"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1874"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1876"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1878"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1880"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1884"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1886"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1892"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1894"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1896"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1898"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1904"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "@DeltaKroneckerGithub_1907"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1911"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1913"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1915"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1917"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1920"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1922"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1924"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1926"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@DeltaKroneckerGithub_1928"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1931"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1933"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1935"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "@DeltaKroneckerGithub_1937"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub_1821"
      - "@DeltaKroneckerGithub_1825"
      - "@DeltaKroneckerGithub_1828"
      - "@DeltaKroneckerGithub_1832"
      - "@DeltaKroneckerGithub_1835"
      - "@DeltaKroneckerGithub_1838"
      - "@DeltaKroneckerGithub_1842"
      - "@DeltaKroneckerGithub_1845"
      - "@DeltaKroneckerGithub_1847"
      - "@DeltaKroneckerGithub_1849"
      - "@DeltaKroneckerGithub_1851"
      - "@DeltaKroneckerGithub_1853"
      - "@DeltaKroneckerGithub_1856"
      - "@DeltaKroneckerGithub_1858"
      - "@DeltaKroneckerGithub_1861"
      - "@DeltaKroneckerGithub_1863"
      - "@DeltaKroneckerGithub_1866"
      - "@DeltaKroneckerGithub_1869"
      - "@DeltaKroneckerGithub_1871"
      - "@DeltaKroneckerGithub_1874"
      - "@DeltaKroneckerGithub_1876"
      - "@DeltaKroneckerGithub_1878"
      - "@DeltaKroneckerGithub_1880"
      - "@DeltaKroneckerGithub_1884"
      - "@DeltaKroneckerGithub_1886"
      - "@DeltaKroneckerGithub_1892"
      - "@DeltaKroneckerGithub_1894"
      - "@DeltaKroneckerGithub_1896"
      - "@DeltaKroneckerGithub_1898"
      - "@DeltaKroneckerGithub_1904"
      - "@DeltaKroneckerGithub_1907"
      - "@DeltaKroneckerGithub_1911"
      - "@DeltaKroneckerGithub_1913"
      - "@DeltaKroneckerGithub_1915"
      - "@DeltaKroneckerGithub_1917"
      - "@DeltaKroneckerGithub_1920"
      - "@DeltaKroneckerGithub_1922"
      - "@DeltaKroneckerGithub_1924"
      - "@DeltaKroneckerGithub_1926"
      - "@DeltaKroneckerGithub_1928"
      - "@DeltaKroneckerGithub_1931"
      - "@DeltaKroneckerGithub_1933"
      - "@DeltaKroneckerGithub_1935"
      - "@DeltaKroneckerGithub_1937"


rules:
  - MATCH,PROXY
