name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇧🇷_1"
    type: vless
    server: "cave.magazinetut.online"
    port: 443
    uuid: "0000e293-996d-4c32-99dc-29a8aba80d06"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cave.magazinetut.online"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_2"
    type: vless
    server: "23.251.56.78"
    port: 443
    uuid: "9638a83e-f1f7-4cc8-a602-924965d9534f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "E6Y9lNizCXo8tJ6EXwLYQIjyIwmxIs4foyRlY2MgkjA"
      short-id: "59ccabb0a1483c4b"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_3"
    type: vless
    server: "cave.magazinetut.online"
    port: 443
    uuid: "a78d6a0b-8751-4e8e-bafa-79a86c5a5fc7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cave.magazinetut.online"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_4"
    type: vless
    server: "23.251.55.216"
    port: 443
    uuid: "c396fa08-e07a-459b-b894-389456fd6a82"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "m89wjPa2LxODyi8U5pRVI4E1fwVawIaftC3fLY0ZLw4"
      short-id: "9ea177c3c147119b"
    flow: "xtls-rprx-vision"
  - name: "🇧🇷_5"
    type: ss
    server: "163.176.208.150"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "OJSP24R+VVhsEXvSTPBOfLpNBdI8/RI6vrqhIlk0xbg="
    udp: true
  - name: "🇧🇷_6"
    type: ss
    server: "137.131.181.65"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "AR+KCUvNn+P1ZAGJipDZhmMesTxHnvRYwW3pwGzlK7U="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"


rules:
  - MATCH,PROXY
