name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇧🇷_1"
    type: vless
    server: "201.24.49.228"
    port: 2200
    uuid: "09f2e2f4-3225-4342-bc92-cb58ee841f72"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇧🇷_2"
    type: vless
    server: "201.24.49.237"
    port: 2200
    uuid: "af412668-578c-4296-bc8c-8fac6a8d9003"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇧🇷_3"
    type: vless
    server: "201.24.49.69"
    port: 4100
    uuid: "2cd5f052-6455-4153-b7d3-0545184dc64c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇧🇷_4"
    type: vless
    server: "201.24.49.213"
    port: 4100
    uuid: "6d662736-24ea-4f8e-9e73-acbc14d09cb1"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇧🇷_5"
    type: vless
    server: "201.24.49.53"
    port: 4100
    uuid: "33965d4f-f9bd-4437-8867-ed705b435518"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇧🇷_6"
    type: vless
    server: "201.24.49.79"
    port: 4100
    uuid: "3b4274c1-4744-452e-9903-e11ccc0c9900"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇧🇷_7"
    type: vless
    server: "201.24.49.19"
    port: 2200
    uuid: "716903b1-e6bf-4420-9e27-65e4451692e9"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇧🇷_8"
    type: vless
    server: "201.24.49.240"
    port: 4100
    uuid: "aa7d939b-feaa-4ad3-9615-74216f490807"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇧🇷_9"
    type: vless
    server: "201.24.49.117"
    port: 2200
    uuid: "2e228435-33a0-47d1-a1d8-9a34b5a03c45"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇧🇷_10"
    type: vless
    server: "201.24.49.120"
    port: 2200
    uuid: "b671573f-6303-4cdf-ad50-0401d07e85bf"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇧🇷_11"
    type: vless
    server: "201.24.49.120"
    port: 4100
    uuid: "714e1212-6707-471e-9f40-2fbd3d8d3b4b"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇧🇷_12"
    type: vless
    server: "201.24.49.233"
    port: 2200
    uuid: "ed1fd11d-cbf7-4a73-9e98-c7f332b37117"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇧🇷_13"
    type: vless
    server: "201.24.49.74"
    port: 2200
    uuid: "f0528a17-863f-4160-a5a0-0d9ad03f2ee7"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇧🇷_14"
    type: ss
    server: "144.22.225.161"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "GRe/0J+gpJILazFMu8n4Lo6J1AjoIG2+mdCoR7RmX74="
    udp: true
  - name: "🇧🇷_15"
    type: ss
    server: "146.235.25.6"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "FWlUCAS9IBNg+5FoZ+U0kRs3dcz+oQnQkjGI/iKZMR0="
    udp: true
  - name: "🇧🇷_16"
    type: ss
    server: "146.235.25.6"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "FWlUCAS9IBNg+5FoZ+U0kRs3dcz+oQnQkjGI/iKZMR0="
    udp: true
  - name: "🇧🇷_17"
    type: ss
    server: "137.131.200.22"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "tNYMIixAhMRlptzlIGQrnx6y24ONgfLrblB3qmVzwDY="
    udp: true
  - name: "🇧🇷_18"
    type: ss
    server: "144.22.225.161"
    port: 59319
    cipher: "2022-blake3-chacha20-poly1305"
    password: "GRe/0J+gpJILazFMu8n4Lo6J1AjoIG2+mdCoR7RmX74="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇧🇷_1"
      - "🇧🇷_2"
      - "🇧🇷_3"
      - "🇧🇷_4"
      - "🇧🇷_5"
      - "🇧🇷_6"
      - "🇧🇷_7"
      - "🇧🇷_8"
      - "🇧🇷_9"
      - "🇧🇷_10"
      - "🇧🇷_11"
      - "🇧🇷_12"
      - "🇧🇷_13"
      - "🇧🇷_14"
      - "🇧🇷_15"
      - "🇧🇷_16"
      - "🇧🇷_17"
      - "🇧🇷_18"


rules:
  - MATCH,PROXY
