name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇭_1"
    type: vless
    server: "45.143.200.245"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇨🇭_2"
    type: vless
    server: "free01.tunnely.space"
    port: 2096
    uuid: "c3ac697e-f4ca-4aae-9593-1c5b99096220"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "free01.tunnely.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mChFHtaRmeuO2aDuDPqZvBFaCz6f34sVJIKuJcAR130"
      short-id: "2e40144ddc07e8e1"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇭_3"
    type: vless
    server: "178.83.226.55"
    port: 443
    uuid: "2a77a470-315c-493d-b690-59b814a804cb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sellflow.org"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_4"
    type: vless
    server: "194.147.173.116"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇨🇭_5"
    type: vless
    server: "151.243.190.41"
    port: 25488
    uuid: "e6c94266-956d-46dd-9fd7-02d38179f7d9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "proxy11.h1guro.ovh"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "z3eHrafcEv7gDkshLVUyR7GOH2eqxUigKB-LOg8-EgI"
      short-id: "135f036cf30861a5"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_6"
    type: vless
    server: "45.90.56.231"
    port: 443
    uuid: "e2b8f727-c5ee-47e1-8f1b-7c5c61479ce0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "KrFnWxAwVGL6tuj1JE0qpykLzY4aOFjyK3OaymF_hT0"
      short-id: "e2e66f4537770cef"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_7"
    type: vless
    server: "140.238.208.210"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇨🇭_8"
    type: trojan
    server: "86.106.84.195"
    port: 53261
    password: "y3b03zx3tznhyo538p4c"
    sni: "86.106.84.195"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇭_1"
      - "🇨🇭_2"
      - "🇨🇭_3"
      - "🇨🇭_4"
      - "🇨🇭_5"
      - "🇨🇭_6"
      - "🇨🇭_7"
      - "🇨🇭_8"


rules:
  - MATCH,PROXY
