name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇭_1"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "329aa1be-ee6d-4d92-a8ef-c2ddac7583b1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇨🇭_2"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "097e0483-50a9-4adf-8f62-031057710d11"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇨🇭_3"
    type: vless
    server: "208.69.78.217"
    port: 2053
    uuid: "c0dd6d59-1573-43af-8b70-1470b2632a6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "A49ue7zXSusJZdErPAewg3jqGdUFIO1a9xOunEKJfC0"
      short-id: "ad86e2d52ff40ebd"
  - name: "🇨🇭_4"
    type: vless
    server: "45.90.59.15"
    port: 443
    uuid: "3950b45e-740d-4dca-ac95-505ec8534592"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "P7S4UPFlQbmiBr4txyy8NZIMTrmO3UdxyH16WBU-YzY"
      short-id: "19253fae84102271"
    flow: "xtls-rprx-vision"
  - name: "🇨🇭_5"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "00274dd7-7cee-420d-9942-b24d047611a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇨🇭_6"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "d25fa7ff-f71e-4cc2-88e6-a340b86fdebf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "ke859ch2gse1iery3hiz.e3q4a5mjld11kpj0zj8dq.workers.dev"
  - name: "🇨🇭_7"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "08db3580-ce2e-4e88-80c7-ffcc02de55e8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "3tmj2egtm-fno.49bnithzk8vphybv36d1z1xkzfvogt2m6.workers.dev"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "3tmj2egtm-fno.49bnithzk8vphybv36d1z1xkzfvogt2m6.workers.dev"
  - name: "🇨🇭_8"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "fc85cf23-75e6-4b91-b468-8adc9407047b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇨🇭_9"
    type: vless
    server: "116.204.164.17"
    port: 7443
    uuid: "57c830ca-19a2-441c-811d-db5d81b86b47"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇨🇭_10"
    type: trojan
    server: "91.245.225.79"
    port: 2053
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇨🇭_11"
    type: ss
    server: "132.243.175.144"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "e8KgS8fD0yDqYFpgN4G5piCOt9aFyqA3"
    udp: true
  - name: "🇨🇭_12"
    type: ss
    server: "132.243.175.144"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "e8KgS8fD0yDqYFpgN4G5piCOt9aFyqA3"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇭_1"
      - "🇨🇭_2"
      - "🇨🇭_3"
      - "🇨🇭_4"
      - "🇨🇭_5"
      - "🇨🇭_6"
      - "🇨🇭_7"
      - "🇨🇭_8"
      - "🇨🇭_9"
      - "🇨🇭_10"
      - "🇨🇭_11"
      - "🇨🇭_12"


rules:
  - MATCH,PROXY
