name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇾_1"
    type: vless
    server: "195.85.59.187"
    port: 2095
    uuid: "86c50e3a-5b87-49dd-bd20-03c7f2735e40"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "llm-api.sofurry.dpdns.org"
  - name: "🇨🇾_2"
    type: vless
    server: "185.249.153.108"
    port: 443
    uuid: "4cf9c712-11c4-47d8-aa31-a1693a1aa4e5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nordivablog.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xOJ3INBNzRKOKYGQZmSYczgTjTKwdYQ4BFfc75wVazw"
      short-id: "73c9e31ccafda20e"
    flow: "xtls-rprx-vision"
  - name: "🇨🇾_3"
    type: vless
    server: "195.85.59.69"
    port: 2095
    uuid: "86c50e3a-5b87-49dd-bd20-03c7f2735e40"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "llm-api.sofurry.dpdns.org"
  - name: "🇨🇾_4"
    type: vless
    server: "2.56.123.131"
    port: 443
    uuid: "0a975d79-6930-4861-a105-dc50793456de"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "contact.yump.online"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "wDAQ_iQ_vv6lQiB9nCxIJviEhARWOQOPyhzos8EJW3o"
      short-id: "9da47879658f9f25"
    flow: "xtls-rprx-vision"
  - name: "🇨🇾_5"
    type: vless
    server: "2.56.123.227"
    port: 443
    uuid: "eec2f6a7-c10f-43b0-b133-61f9bf9bbc27"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bPbAdn6ogLbiv5cRe5d12EL7FhooAIVrC3-fg90P-Bw"
      short-id: "72104d27a0f5f62e"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇾_1"
      - "🇨🇾_2"
      - "🇨🇾_3"
      - "🇨🇾_4"
      - "🇨🇾_5"


rules:
  - MATCH,PROXY
