name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇨🇿_1"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "2fa87b7e-74a3-452f-8c7e-64ffc51dec7d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_2"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "290809d0-ccec-4977-92bd-61ca06067f49"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_3"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "d8463649-fed0-46a8-85b3-631fd7e90e4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_4"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "aba618f7-d311-4c6b-a499-04ace0076dc2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_5"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "ec9daa45-6855-4575-a320-47edaaf93813"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_6"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "168e2280-b202-473e-ba71-4e86f3156dd6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_7"
    type: vless
    server: "103.119.19.208"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇨🇿_8"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "41af5ecc-9d3e-43c1-84bf-22b8d29de237"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_9"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "c1eea94c-1ed3-45b2-b70f-3a103b6b4f64"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_10"
    type: vless
    server: "150.241.121.61"
    port: 443
    uuid: "1acb9aad-9f16-47db-b44c-91f5bd088628"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "1pgt5wjq9slq.bosfiles.net"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇨🇿_11"
    type: vless
    server: "212.102.38.25"
    port: 443
    uuid: "b34a52cb-cd52-49a8-9362-b8e97c151d49"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "udemy.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "23cb4W9THzBKsrECsLh-A_FcKZfkAtUONoDze8-GnQE"
      short-id: "e90360ec7cc61b20"
    flow: "xtls-rprx-vision"
  - name: "🇨🇿_12"
    type: vless
    server: "188.127.247.129"
    port: 443
    uuid: "33aa2b47-484b-49f6-8f23-fb34602d221f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Kb0rDCu2kKhfnC6bsi0DMRxDej9S-Mu1vVza1H1l4U4"
      short-id: "0c"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇨🇿_1"
      - "🇨🇿_2"
      - "🇨🇿_3"
      - "🇨🇿_4"
      - "🇨🇿_5"
      - "🇨🇿_6"
      - "🇨🇿_7"
      - "🇨🇿_8"
      - "🇨🇿_9"
      - "🇨🇿_10"
      - "🇨🇿_11"
      - "🇨🇿_12"


rules:
  - MATCH,PROXY
