name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇩🇪_1"
    type: vless
    server: "82.118.19.153"
    port: 443
    uuid: "adcaa148-7c66-4282-a81a-99ec8afa029d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Tiuy8om5Lk0pWL95-8LaFFTwH0vbURVMoOkaW9xGaiE"
      short-id: "670ed9f350bd8ee0"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_2"
    type: vless
    server: "OV-Germany1.09vpn.com"
    port: 80
    uuid: "18535741-e8b3-4b43-9348-785b55936751"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇩🇪_3"
    type: vless
    server: "2.59.134.226"
    port: 443
    uuid: "88281d02-b387-4fe3-918e-26ed331e6d08"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jolly-ember.cdn.cachefleet.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "1sSmdw90uTiGuitDvp_q8zcXTcHXKQS3IVjA7T1UNiY"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_4"
    type: vless
    server: "2.59.134.226"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rich-nebula.cdn.cachefleet.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "1sSmdw90uTiGuitDvp_q8zcXTcHXKQS3IVjA7T1UNiY"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_5"
    type: vless
    server: "OV-Germany1.09vpn.com"
    port: 80
    uuid: "7d90f043-ed7f-40c9-ac2f-352987904958"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇩🇪_6"
    type: vless
    server: "35.157.240.237"
    port: 443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "🇩🇪_7"
    type: vless
    server: "93.94.52.23"
    port: 40443
    uuid: "bb0f1ed0-0298-40a1-adb1-1f5d6ab33d54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "w4AYHvQnQS6olDqoG9ptLOtgehaWOsv9HQhDax5bLA4"
      short-id: "db46e2946fc466fd"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_8"
    type: vless
    server: "207.241.172.98"
    port: 12345
    uuid: "abc83c2b-9b3b-438f-9145-192dd4d85cbb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheets.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1N8CIM6v_TgbIDNneyEPNQ92hyq5Eyh_irJWOXKDBDw"
      short-id: "2b368990a94e8cbb"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_9"
    type: vless
    server: "140.82.34.114"
    port: 25585
    uuid: "6eebb521-1844-4c3c-bf54-fb0e19870f80"
    udp: true
  - name: "🇩🇪_10"
    type: vless
    server: "77.110.117.199"
    port: 9443
    uuid: "d9d0f208-d582-41d5-bb7b-742671402810"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hub-nl-01.hanvpn.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/nl01-ws-8e47a"
      headers:
        Host: "hub-nl-01.hanvpn.cc"
  - name: "🇩🇪_11"
    type: vless
    server: "144.31.125.60"
    port: 443
    uuid: "9015f0bc-2053-4ca1-9b9b-a018b97b32d2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SVgtyuD9khylgHuB0treGekxVSHPOS-wPZTNHUf6zj8"
      short-id: "85c86a9863"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_12"
    type: vless
    server: "163.8.195.241"
    port: 2087
    uuid: "56ba5d34-ef22-4ba6-8090-4188b807df54"
    udp: true
    network: ws
    ws-opts:
      path: "/29c8fed7ca22"
  - name: "🇩🇪_13"
    type: vless
    server: "140.82.34.114"
    port: 25585
    uuid: "e4668a2b-66d6-4500-bcef-5ed52414e40a"
    udp: true
  - name: "🇩🇪_14"
    type: vless
    server: "31.56.189.27"
    port: 8765
    uuid: "df9f5aca-eda0-428f-a752-e53866153d12"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "srv-21bac9.vless.monster"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "M08l5tDmJUYELykZCNYQyFgtR9Zc-A4ZGlUSLcUeS2c"
      short-id: "1bcc9177f3124b25"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_15"
    type: vless
    server: "88.99.125.243"
    port: 15036
    uuid: "783c7211-5349-4c26-8f8f-85f0f4c93ae8"
    udp: true
  - name: "🇩🇪_16"
    type: vless
    server: "91.228.154.112"
    port: 2053
    uuid: "65c56e1f-5c41-40bc-b0b5-9346772476ca"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "singapore.36109178.xyz"
    client-fingerprint: "android"
    network: ws
    ws-opts:
      path: "/static/media/video-chunk.f4v"
      headers:
        Host: "singapore.36109178.xyz"
  - name: "🇩🇪_17"
    type: vless
    server: "82.24.203.20"
    port: 2087
    uuid: "5fcdc9b7-e70f-4a5c-85c3-e018ad818326"
    udp: true
    network: ws
    ws-opts:
      path: "/fd5ba98a3970"
  - name: "🇩🇪_18"
    type: vless
    server: "2.27.205.59"
    port: 443
    uuid: "c21631d5-36c9-4664-b575-97eca17456be"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇩🇪_19"
    type: vless
    server: "31.56.189.27"
    port: 2087
    uuid: "df9f5aca-eda0-428f-a752-e53866153d12"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "srv-21bac9.vless.monster"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "freegrpc"
  - name: "🇩🇪_20"
    type: vless
    server: "57.129.41.216"
    port: 80
    uuid: "18535741-e8b3-4b43-9348-785b55936751"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇩🇪_21"
    type: vless
    server: "51.38.127.93"
    port: 443
    uuid: "cf39fab0-bb85-42cb-9945-2ad69d78e575"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rubifen.adaspoloandco.com"
    network: ws
    ws-opts:
      path: "/GOrbEh"
  - name: "🇩🇪_22"
    type: vless
    server: "57.129.41.216"
    port: 80
    uuid: "7d74eae4-8a06-4306-a923-ad686f30bf26"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "OV-Germany1.09vpn.com"
  - name: "🇩🇪_23"
    type: vless
    server: "178.105.61.61"
    port: 2083
    uuid: "cb077bf2-70b7-457b-af42-27cdc3e0e544"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "178.105.61.61"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "H0nCazQFHVhSObfqSUhGLhK7KRwKzTMggIBPjnMMqhk"
      short-id: "af04ff8094115e93"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_24"
    type: vless
    server: "2.27.202.112"
    port: 443
    uuid: "bfde1878-f157-4ec7-a5ad-38e8835c6e36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    reality-opts:
      public-key: "Uaq2YojNeUXGkaCPKxcR_IF9iaatuc3srHfFuwwG7FA"
      short-id: "a19516e2d20b09e9"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_25"
    type: vless
    server: "57.129.41.216"
    port: 8443
    uuid: "7d74eae4-8a06-4306-a923-ad686f30bf26"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "OV-Germany1.09vpn.com"
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇩🇪_26"
    type: vless
    server: "207.241.172.98"
    port: 12345
    uuid: "17dee937-7ba5-45d8-8564-b27466317f58"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheets.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1N8CIM6v_TgbIDNneyEPNQ92hyq5Eyh_irJWOXKDBDw"
      short-id: "2b368990a94e8cbb"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_27"
    type: vless
    server: "150.241.101.80"
    port: 8443
    uuid: "47d9b534-8a0a-4bd2-90f1-1d6ade14427e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_28"
    type: vless
    server: "140.82.34.114"
    port: 25585
    uuid: "8b84bbec-9a55-47c2-ac2e-03c41065e572"
    udp: true
  - name: "🇩🇪_29"
    type: vless
    server: "57.129.96.67"
    port: 443
    uuid: "nasnet"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-571299667-direct.mbghalibaf.com"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_30"
    type: vless
    server: "170.101.109.37"
    port: 443
    uuid: "bf645ffe-a3cc-4480-8e4c-9bcd1af41052"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "rTnh7Y8RsSA5HSvFf-pWT49x8va6U6XHMRgNiMuwB0A"
      short-id: "ab88d256"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_31"
    type: vless
    server: "media-dan1.team-pluss.ir"
    port: 12345
    uuid: "4891b572-0830-4d23-b1bf-e4f7d52f99e0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheets.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1N8CIM6v_TgbIDNneyEPNQ92hyq5Eyh_irJWOXKDBDw"
      short-id: "2b368990a94e8cbb"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_32"
    type: vless
    server: "OV-Germany1.09vpn.com"
    port: 80
    uuid: "7d74eae4-8a06-4306-a923-ad686f30bf26"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇩🇪_33"
    type: vless
    server: "93.152.217.41"
    port: 40443
    uuid: "969bcce0-de8a-4b02-8cf8-d00d2d2ca7a5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "VG-FwQBMFzPcemJ_JqtkbO-2WKLmQp2h0CmAj-DfLkA"
      short-id: "5b97"
  - name: "🇩🇪_34"
    type: vless
    server: "2.27.202.112"
    port: 443
    uuid: "b80708a5-90f0-4d02-bcaf-69936cbd15b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Uaq2YojNeUXGkaCPKxcR_IF9iaatuc3srHfFuwwG7FA"
      short-id: "a19516e2d20b09e9"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_35"
    type: vless
    server: "srv-21bac9.vless.monster"
    port: 2087
    uuid: "df9f5aca-eda0-428f-a752-e53866153d12"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "srv-21bac9.vless.monster"
    client-fingerprint: "firefox"
    network: grpc
    grpc-opts:
      grpc-service-name: "freegrpc"
  - name: "🇩🇪_36"
    type: vless
    server: "91.98.102.240"
    port: 42718
    uuid: "b775630e-1386-44a6-9d89-61d029d4b5ab"
    udp: true
  - name: "🇩🇪_37"
    type: vless
    server: "162.248.166.35"
    port: 443
    uuid: "d92b6509-8b63-4505-b3a2-1dc5b1c014ac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.caradisiac.com"
    reality-opts:
      public-key: "NYG48Fv1MF3SqOpHwoa4GqJH5IJrocSrwWzrffY-tCk"
      short-id: "c6dc8abb0235dc05"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_38"
    type: vless
    server: "81.95.4.189"
    port: 443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "🇩🇪_39"
    type: vless
    server: "144.31.168.95"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_40"
    type: vless
    server: "media-dan1.team-pluss.ir"
    port: 12345
    uuid: "abc83c2b-9b3b-438f-9145-192dd4d85cbb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sheets.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1N8CIM6v_TgbIDNneyEPNQ92hyq5Eyh_irJWOXKDBDw"
      short-id: "2b368990a94e8cbb"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_41"
    type: vless
    server: "srv-21bac9.vless.monster"
    port: 8765
    uuid: "df9f5aca-eda0-428f-a752-e53866153d12"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "srv-21bac9.vless.monster"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "M08l5tDmJUYELykZCNYQyFgtR9Zc-A4ZGlUSLcUeS2c"
      short-id: "1bcc9177f3124b25"
    flow: "xtls-rprx-vision"
  - name: "🇩🇪_42"
    type: trojan
    server: "185.220.100.168"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇩🇪_43"
    type: trojan
    server: "78.47.146.151"
    port: 443
    password: "humanity"
    sni: "www.pleadcourt.org"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.pleadcourt.org"
  - name: "🇩🇪_44"
    type: trojan
    server: "185.255.179.166"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇩🇪_45"
    type: ss
    server: "130.61.236.161"
    port: 59924
    cipher: "2022-blake3-chacha20-poly1305"
    password: "jDcGibduRNsgoed1T+wYpfvxjfkqQCz/8GwzmQbnZCE="
    udp: true
  - name: "🇩🇪_46"
    type: ss
    server: "209.46.102.22"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "1hhrqrokj3ag"
    udp: true
  - name: "🇩🇪_47"
    type: ss
    server: "8.209.74.72"
    port: 20001
    cipher: "chacha20-ietf-poly1305"
    password: "PWpjPo3tqhPN4yRZ"
    udp: true
  - name: "🇩🇪_48"
    type: ss
    server: "130.61.144.173"
    port: 59924
    cipher: "2022-blake3-chacha20-poly1305"
    password: "MSBulFIL/2cQ1Jg+HZEfrPrfk/2Ev2nlSei+wSvdOLY="
    udp: true
  - name: "🇩🇪_49"
    type: ss
    server: "2.58.81.221"
    port: 443
    cipher: "aes-256-gcm"
    password: "kKEd0rBrd56Furjz"
    udp: true
  - name: "🇩🇪_50"
    type: ss
    server: "130.61.144.173"
    port: 59924
    cipher: "2022-blake3-chacha20-poly1305"
    password: "MSBulFIL/2cQ1Jg+HZEfrPrfk/2Ev2nlSei+wSvdOLY="
    udp: true
  - name: "🇩🇪_51"
    type: ss
    server: "79.137.207.190"
    port: 3
    cipher: "chacha20-ietf-poly1305"
    password: "9ri2bpxWs4FHXRjlhTFlQQ"
    udp: true
  - name: "🇩🇪_52"
    type: ss
    server: "185.226.172.8"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇩🇪_53"
    type: ss
    server: "141.95.29.163"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:JTou+JSmZOAyrMLdvNBcXFm0Y9luZ/8u17ie48jQfVc="
    udp: true
  - name: "🇩🇪_54"
    type: ss
    server: "141.95.29.163"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:JTou+JSmZOAyrMLdvNBcXFm0Y9luZ/8u17ie48jQfVc="
    udp: true
  - name: "🇩🇪_55"
    type: ss
    server: "79.137.207.190"
    port: 2
    cipher: "chacha20-ietf-poly1305"
    password: "9ri2bpxWs4FHXRjlhTFlQQ"
    udp: true
  - name: "🇩🇪_56"
    type: ss
    server: "213.202.208.199"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇩🇪_57"
    type: ss
    server: "130.61.226.18"
    port: 59924
    cipher: "2022-blake3-chacha20-poly1305"
    password: "kp7CxMhMIiTO7veAEdxWlHNbZPqsgeXVt84mg+SOt/k="
    udp: true
  - name: "🇩🇪_58"
    type: ss
    server: "2.58.81.221"
    port: 80
    cipher: "aes-256-gcm"
    password: "kKEd0rBrd56Furjz"
    udp: true
  - name: "🇩🇪_59"
    type: ss
    server: "2.58.81.221"
    port: 443
    cipher: "aes-256-gcm"
    password: "kKEd0rBrd56Furjz"
    udp: true
  - name: "🇩🇪_60"
    type: ss
    server: "185.226.172.8"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇩🇪_61"
    type: ss
    server: "209.46.102.22"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "1hhrqrokj3ag"
    udp: true
  - name: "🇩🇪_62"
    type: ss
    server: "2.58.81.221"
    port: 80
    cipher: "aes-256-gcm"
    password: "kKEd0rBrd56Furjz"
    udp: true
  - name: "🇩🇪_63"
    type: ss
    server: "185.226.172.8"
    port: 8008
    cipher: "aes-256-gcm"
    password: "XKFKl2rULjIp74"
    udp: true
  - name: "🇩🇪_64"
    type: ss
    server: "130.61.144.173"
    port: 59924
    cipher: "2022-blake3-chacha20-poly1305"
    password: "MSBulFIL/2cQ1Jg+HZEfrPrfk/2Ev2nlSei+wSvdOLY="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇩🇪_1"
      - "🇩🇪_2"
      - "🇩🇪_3"
      - "🇩🇪_4"
      - "🇩🇪_5"
      - "🇩🇪_6"
      - "🇩🇪_7"
      - "🇩🇪_8"
      - "🇩🇪_9"
      - "🇩🇪_10"
      - "🇩🇪_11"
      - "🇩🇪_12"
      - "🇩🇪_13"
      - "🇩🇪_14"
      - "🇩🇪_15"
      - "🇩🇪_16"
      - "🇩🇪_17"
      - "🇩🇪_18"
      - "🇩🇪_19"
      - "🇩🇪_20"
      - "🇩🇪_21"
      - "🇩🇪_22"
      - "🇩🇪_23"
      - "🇩🇪_24"
      - "🇩🇪_25"
      - "🇩🇪_26"
      - "🇩🇪_27"
      - "🇩🇪_28"
      - "🇩🇪_29"
      - "🇩🇪_30"
      - "🇩🇪_31"
      - "🇩🇪_32"
      - "🇩🇪_33"
      - "🇩🇪_34"
      - "🇩🇪_35"
      - "🇩🇪_36"
      - "🇩🇪_37"
      - "🇩🇪_38"
      - "🇩🇪_39"
      - "🇩🇪_40"
      - "🇩🇪_41"
      - "🇩🇪_42"
      - "🇩🇪_43"
      - "🇩🇪_44"
      - "🇩🇪_45"
      - "🇩🇪_46"
      - "🇩🇪_47"
      - "🇩🇪_48"
      - "🇩🇪_49"
      - "🇩🇪_50"
      - "🇩🇪_51"
      - "🇩🇪_52"
      - "🇩🇪_53"
      - "🇩🇪_54"
      - "🇩🇪_55"
      - "🇩🇪_56"
      - "🇩🇪_57"
      - "🇩🇪_58"
      - "🇩🇪_59"
      - "🇩🇪_60"
      - "🇩🇪_61"
      - "🇩🇪_62"
      - "🇩🇪_63"
      - "🇩🇪_64"


rules:
  - MATCH,PROXY
