name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_2"
    type: vless
    server: "94.183.170.231"
    port: 8443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy2.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_3"
    type: vless
    server: "94.183.170.231"
    port: 443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_4"
    type: vless
    server: "93.123.39.158"
    port: 2066
    uuid: "24f8209b-6689-4e7a-b067-f886e04dfc43"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "XIBKbglsQ9pI4eo26LoUkmNxnVqlKtxZRO0H91v3jF0"
      short-id: "1b2a3f"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_5"
    type: vless
    server: "185.155.97.241"
    port: 443
    uuid: "0b9bcbc1-b289-4a64-86fa-a5b731b65384"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "SJkDT_L0eziQR2afDGrkN7-uRxjYu6bZxIGXlKeCvX4"
      short-id: "15aa18f971da1f81"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_6"
    type: vless
    server: "estproxy3.lockdwn.com"
    port: 8443
    uuid: "a4aba0ef-0929-4a34-89bd-5ee96fe968da"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy3.lockdwn.com"
    client-fingerprint: "edge"
  - name: "🇪🇪_7"
    type: vless
    server: "64.188.82.152"
    port: 443
    uuid: "7836b28e-8451-4596-ad3e-e3601b2335ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cloudflare.vhub.pro"
    client-fingerprint: "safari"
    network: ws
    ws-opts:
      path: "/websocket?ed=2560"
      headers:
        Host: "cloudflare.vhub.pro"
  - name: "🇪🇪_8"
    type: vless
    server: "95.85.224.3"
    port: 8443
    uuid: "7e8f7489-e65f-4be6-93ed-867a74ec6759"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇪🇪_9"
    type: trojan
    server: "80.77.25.142"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"


rules:
  - MATCH,PROXY
