name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "5.101.180.145"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pg/10086-dfc816f117c49173"
      headers:
        Host: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
  - name: "🇪🇪_2"
    type: vless
    server: "5.189.254.168"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_3"
    type: vless
    server: "94.183.170.231"
    port: 8443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy2.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_4"
    type: vless
    server: "132.243.65.4"
    port: 443
    uuid: "d96e05a1-18bb-45da-9e9f-ab7caab6952a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee.cdn-global.pro"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "RO5YMxxtJmZo2w370qG-seJ41toowHPbz6i2uXJ2gG0"
      short-id: "7a3f9e2b1c8d4f6a"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_5"
    type: vless
    server: "ee.cdn-global.pro"
    port: 443
    uuid: "d96e05a1-18bb-45da-9e9f-ab7caab6952a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee.cdn-global.pro"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "RO5YMxxtJmZo2w370qG-seJ41toowHPbz6i2uXJ2gG0"
      short-id: "7a3f9e2b1c8d4f6a"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_6"
    type: vless
    server: "5.189.254.168"
    port: 2053
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_7"
    type: vless
    server: "5.175.178.254"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pg/10086-dfc816f117c49173"
      headers:
        Host: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
  - name: "🇪🇪_8"
    type: vless
    server: "159.253.21.82"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_9"
    type: vless
    server: "94.183.170.135"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_10"
    type: vless
    server: "5.45.114.210"
    port: 8443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_11"
    type: vless
    server: "est1.nihaovpn.ru"
    port: 443
    uuid: "00506574-3b10-4f7d-9b2f-8afdc5919b93"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "stackoverflow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "lG0cFS6B-psGN0Qre9LArEvTsOyqQjVba9iQ2d3K5BY"
      short-id: "20d13a0be892b6f5"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_12"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_13"
    type: vless
    server: "94.183.170.231"
    port: 443
    uuid: "19f54e37-5fae-47f6-bc10-e71ccbc58389"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_14"
    type: vless
    server: "5.101.114.177"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pg/10086-dfc816f117c49173"
      headers:
        Host: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
  - name: "🇪🇪_15"
    type: vless
    server: "5.101.118.52"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇪🇪_16"
    type: vless
    server: "93.123.39.4"
    port: 443
    uuid: "00506574-3b10-4f7d-9b2f-8afdc5919b93"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "stackoverflow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "lG0cFS6B-psGN0Qre9LArEvTsOyqQjVba9iQ2d3K5BY"
      short-id: "20d13a0be892b6f5"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_17"
    type: vless
    server: "5.45.118.220"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pg/10086-dfc816f117c49173"
      headers:
        Host: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
  - name: "🇪🇪_18"
    type: vless
    server: "estproxy4.lockdwn.com"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "edge"
  - name: "🇪🇪_19"
    type: vless
    server: "2.26.135.193"
    port: 443
    uuid: "627b1c2d-2905-470f-857a-da7589968fbc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smorodina.mycdn-me.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "09O8bAlIWm9AGnNyxBtHwpYNQxlXPSQeQeKzS3ZMwGE"
      short-id: "a1f9c0e21d7b6485"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_20"
    type: vless
    server: "95.85.243.240"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
    network: ws
    ws-opts:
      path: "/pg/10086-dfc816f117c491730| 🇪🇪 爱沙尼亚 20 | 95.85.243.240:443"
      headers:
        Host: "8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr"
  - name: "🇪🇪_21"
    type: vless
    server: "94.183.170.135"
    port: 443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "estproxy4.lockdwn.com"
  - name: "🇪🇪_22"
    type: vless
    server: "5.45.126.36"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/pg/10086-dfc816f117c49173"
      headers:
        Host: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
  - name: "🇪🇪_23"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "russiapower.accesscam.org"
    skip-cert-verify: true
    udp: true
  - name: "🇪🇪_24"
    type: trojan
    server: "80.77.25.142"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"
      - "🇪🇪_14"
      - "🇪🇪_15"
      - "🇪🇪_16"
      - "🇪🇪_17"
      - "🇪🇪_18"
      - "🇪🇪_19"
      - "🇪🇪_20"
      - "🇪🇪_21"
      - "🇪🇪_22"
      - "🇪🇪_23"
      - "🇪🇪_24"


rules:
  - MATCH,PROXY
