name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇪🇪_1"
    type: vless
    server: "95.85.245.163"
    port: 442
    uuid: "2c070f10-57e8-442b-b6cb-ff39b35d929d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "p-nt-www-amazon-com-kalias.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "urhSusjL1QqHdmlCrvbC9yBftecrgQMuhWmfGh0CUFg"
      short-id: "ab"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_2"
    type: vless
    server: "94.183.170.135"
    port: 443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "estproxy4.lockdwn.com"
  - name: "🇪🇪_3"
    type: vless
    server: "95.85.224.51"
    port: 443
    uuid: "342ab7e4-5a89-0001-8809-304120d4aa83"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "WWeAHWUVD-phmnjNJ823cer0c4CMIbEs08AhsuEZmDc"
      short-id: "a696de84963656de"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_4"
    type: vless
    server: "94.183.170.147"
    port: 8443
    uuid: "66ac188b-bd8d-4218-b9ba-0bad0e152cd0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "s2uiu3GQA2SlZzsr86Z5Dav97eAFTPf7Nvr-zqzzRgg"
      short-id: "72ccd4a7563c2953"
    network: grpc
    grpc-opts:
      grpc-service-name: "9d30d49278"
  - name: "🇪🇪_5"
    type: vless
    server: "5.181.201.44"
    port: 443
    uuid: "47b63e55-a4e4-43ce-97dc-946e6a26971d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bababoy.karp1pdd.life"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "98MNvJC4t0ZjK_xHlQjOx2WfLfAPluNDb71MzS9sPT8"
      short-id: "38018dde3e27335e"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_6"
    type: vless
    server: "5.181.201.43"
    port: 443
    uuid: "f495298f-2bdb-4fd8-9ac9-5dd33d1b482a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "est1.loozerp.wiki"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "98MNvJC4t0ZjK_xHlQjOx2WfLfAPluNDb71MzS9sPT8"
      short-id: "38018dde3e27335e"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_7"
    type: vless
    server: "94.183.170.135"
    port: 8443
    uuid: "06c4e938-2954-478f-a870-ca1b163e30e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "estproxy4.lockdwn.com"
    client-fingerprint: "firefox"
  - name: "🇪🇪_8"
    type: vless
    server: "144.31.170.72"
    port: 443
    uuid: "deea5046-3543-4b1b-a17f-3d08a65db91d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "est.bopen.bond"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "fkZTYNydTBVO-1LSiTvDcyBMx-zBP5Am780jECmUgg0"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_9"
    type: vless
    server: "94.183.170.147"
    port: 8443
    uuid: "5edbcb44-8d04-4fa7-a587-bc5d60c24ca1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "s2uiu3GQA2SlZzsr86Z5Dav97eAFTPf7Nvr-zqzzRgg"
      short-id: "72ccd4a7563c2953"
    network: grpc
    grpc-opts:
      grpc-service-name: "9d30d49278"
  - name: "🇪🇪_10"
    type: vless
    server: "xnod17x.artemida.live"
    port: 8443
    uuid: "d9ca156c-8b6d-4ca6-8be1-4eee64c93c36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xnod17x.artemida.live"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "ZRTNgwFRP8viY4SQOgPTfWlLWJCwY3dr0aawA7vHwhU"
      short-id: "a1b2c3d4e5f6a7b8"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_11"
    type: vless
    server: "201.7.25.126"
    port: 24446
    uuid: "b229d38c-35ec-4a0b-9c86-8fceba243d6c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "spry-jolt.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "esOi15BFVX7pHyci7GQp8_FVlY2EmjSF2-0pPu4lIlk"
      short-id: "defeaa98406c7bdf"
    network: grpc
    grpc-opts:
      grpc-service-name: "telegram-bridge"
  - name: "🇪🇪_12"
    type: vless
    server: "94.183.170.39"
    port: 8443
    uuid: "d9ca156c-8b6d-4ca6-8be1-4eee64c93c36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xnod22x.artemida.live"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ZRTNgwFRP8viY4SQOgPTfWlLWJCwY3dr0aawA7vHwhU"
      short-id: "a1b2c3d4e5f6a7b8"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_13"
    type: vless
    server: "94.183.170.51"
    port: 8443
    uuid: "d9ca156c-8b6d-4ca6-8be1-4eee64c93c36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xnod17x.artemida.live"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ZRTNgwFRP8viY4SQOgPTfWlLWJCwY3dr0aawA7vHwhU"
      short-id: "a1b2c3d4e5f6a7b8"
    flow: "xtls-rprx-vision"
  - name: "🇪🇪_14"
    type: trojan
    server: "109.206.241.10"
    port: 449
    password: "oiiaB38ywjEHCWRs_O_a_1113_Il_KeyyyHop_Bes1"
    sni: "russiapower.accesscam.org"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇪🇪_1"
      - "🇪🇪_2"
      - "🇪🇪_3"
      - "🇪🇪_4"
      - "🇪🇪_5"
      - "🇪🇪_6"
      - "🇪🇪_7"
      - "🇪🇪_8"
      - "🇪🇪_9"
      - "🇪🇪_10"
      - "🇪🇪_11"
      - "🇪🇪_12"
      - "🇪🇪_13"
      - "🇪🇪_14"


rules:
  - MATCH,PROXY
