name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇫🇷_1"
    type: vless
    server: "77.221.152.100"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_2"
    type: vless
    server: "usejh2.neobo-tooth.ru"
    port: 2053
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "dRLd_E_GYCkCcwxLN5EcRQYsREKqisb26_ZSehxUpWY"
      short-id: "1eb8ea8dae937ae0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_3"
    type: vless
    server: "bab-6.site"
    port: 443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
  - name: "🇫🇷_4"
    type: vless
    server: "node14.mxvpn.dev"
    port: 443
    uuid: "564082ff-cf3c-48db-9e10-8ad2312847b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_5"
    type: vless
    server: "95.179.219.244"
    port: 39769
    uuid: "683cc41a-2654-4fdb-b4d8-515d356defcb"
    udp: true
  - name: "🇫🇷_6"
    type: vless
    server: "OV-France1.09vpn.com"
    port: 80
    uuid: "25f86cb1-2140-4085-abcb-c3a0ea7a4be0"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇫🇷_7"
    type: vless
    server: "finite-node.rtxconfigz.com"
    port: 443
    uuid: "ce2aa2ab-d893-43c2-ae4c-5b45eb74d49f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tiktok.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_8"
    type: vless
    server: "89.208.113.16"
    port: 443
    uuid: "adce7c2a-3191-49ae-b61c-9b8258ea1b0e"
    udp: true
  - name: "🇫🇷_9"
    type: vless
    server: "finite-node.rtxconfigz.com"
    port: 443
    uuid: "25f3beef-a4b6-40bc-aa74-17a0f89f683c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "telegram.us"
  - name: "🇫🇷_10"
    type: vless
    server: "169.58.143.21"
    port: 443
    uuid: "a5d740d3-2af5-49c2-bfca-f0983456f5fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_11"
    type: vless
    server: "217.69.5.160"
    port: 13903
    uuid: "3bbbd875-6bf1-4240-bd15-061e78206140"
    udp: true
  - name: "🇫🇷_12"
    type: vless
    server: "fra3.freeinternat.com"
    port: 443
    uuid: "dabb9a19-03ab-4cdf-8963-d3c45eb0f80d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fra3.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_13"
    type: vless
    server: "145.223.68.58"
    port: 443
    uuid: "edb50d20-2d3e-4c1e-8a75-a17168a89aa5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "qc2DcqT9zPPZr6ePZ7ukxACWrYhRNIBjDIjCK7veyQg"
      short-id: "a44ff7d2e80213c2"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_14"
    type: vless
    server: "169.58.143.21"
    port: 443
    uuid: "ce2aa2ab-d893-43c2-ae4c-5b45eb74d49f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_15"
    type: vless
    server: "83.136.210.237"
    port: 443
    uuid: "df880bf8-2635-4a83-a6bf-91bb36df284b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fr2.janusgate.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nilJ07r1KZ0-KhmRNYeICXGhM9HeG9uxnRaqjYz3fWg"
      short-id: "6ed1d644822b2951"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_16"
    type: vless
    server: "nasnet-162191099-direct.mbghalibaf.com"
    port: 443
    uuid: "nasnet"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_17"
    type: vless
    server: "141.101.122.147"
    port: 443
    uuid: "c4edb87e-8544-4fa4-bd1c-b0cda9a34b46"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "a.cwvps.eu.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/ws"
      headers:
        Host: "a.cwvps.eu.org"
  - name: "🇫🇷_18"
    type: vless
    server: "45.144.28.39"
    port: 2096
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "usejh2.neobo-tooth.ru"
  - name: "🇫🇷_19"
    type: vless
    server: "104.105.202.38"
    port: 29239
    uuid: "14155d8d-14f7-4105-984b-f477e3880943"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "KGI60DoZFcBFTq4yrjFE5C4QitMypVH4HJlkM9VqB1M"
      short-id: "fd7069bcd5853169"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_20"
    type: vless
    server: "45.144.28.39"
    port: 2083
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usejh2.neobo-tooth.ru"
    client-fingerprint: "ios"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇷_21"
    type: vless
    server: "nasnet-162191099-direct.mbghalibaf.com"
    port: 443
    uuid: "e8b1500b-e9e8-5492-8312-f4eadf7d0767"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    client-fingerprint: "chrome"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_22"
    type: vless
    server: "62.210.91.10"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_23"
    type: vless
    server: "sv-fr2.cdnturbo.net"
    port: 443
    uuid: "b4c5a66f-1f66-4262-b72d-c6aa661abc2c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "0jolgptjjXxVsUgMPN_mcoyHET2uHQ7onbAMZ7uCc2w"
      short-id: "8d0a77a398415b0e"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_24"
    type: vless
    server: "83.136.208.170"
    port: 443
    uuid: "df880bf8-2635-4a83-a6bf-91bb36df284b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fr2.janusgate.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nilJ07r1KZ0-KhmRNYeICXGhM9HeG9uxnRaqjYz3fWg"
      short-id: "6ed1d644822b2951"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_25"
    type: vless
    server: "217.69.5.160"
    port: 13903
    uuid: "fe6f28ad-178b-4cd3-9c4d-a52ab1407e7d"
    udp: true
  - name: "🇫🇷_26"
    type: vless
    server: "62.210.91.2"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_27"
    type: vless
    server: "213.136.92.67"
    port: 443
    uuid: "af348651-1624-4710-b55f-0307a22d891f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "status.play.google.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "jvJPfOHtnr2sH79qG-rEtJHFbr36_7Ag7ARsUmtSDQo"
      short-id: "5030"
  - name: "🇫🇷_28"
    type: vless
    server: "95.179.219.244"
    port: 39769
    uuid: "896caf1b-cd54-481f-8c2c-22aedc28f13b"
    udp: true
  - name: "🇫🇷_29"
    type: vless
    server: "161.97.160.224"
    port: 443
    uuid: "b81b4d1b-7f20-48f1-82dc-d24bef898cab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "passport.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "33zaT3jHXjtynSQ0Ucw9bK92-XH2zolJmuIeZ1XyZB0"
      short-id: "e6"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_30"
    type: vless
    server: "194.76.154.31"
    port: 40443
    uuid: "9f0baff8-bdee-4de9-9515-bcc4932b41fa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "deepl.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "MN6QjUHDUXyteMdR-cDna89fq4X3qgQhLnNqTtRUbBQ"
      short-id: "a8ae"
  - name: "🇫🇷_31"
    type: vless
    server: "finite-node.rtxconfigz.com"
    port: 443
    uuid: "a5d740d3-2af5-49c2-bfca-f0983456f5fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇫🇷_32"
    type: vless
    server: "51.77.217.70"
    port: 2053
    uuid: "fae272a6-a184-4c91-83ed-771abdcff404"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    reality-opts:
      public-key: "5Me9XEMwr9siyrnV5zPHYfxB3QLqw-OzNAOuzkFu1kw"
      short-id: "7af95330630a7327"
  - name: "🇫🇷_33"
    type: vless
    server: "20.33.23.66"
    port: 443
    uuid: "79863d42-9f1c-4e8e-a65b-1003090871c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "coNFIghayE.moKhaBeraTebInZON.workErS.deV"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/eyJqdW5rIjoiUHVXcXFjYTJGVGI3IiwicHJvdG9jb2wiOiJ2bCIsIm1vZGUiOiJwcmVmaXgiLCJwYW5lbElQcyI6WyJbMmEwMjo4OTg6MTQ2OjY0OjpdIl19?ed=2560"
      headers:
        Host: "confighaye.mokhaberatebinzon.workers.dev"
  - name: "🇫🇷_34"
    type: vless
    server: "fr2.janusgate.org"
    port: 443
    uuid: "df880bf8-2635-4a83-a6bf-91bb36df284b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fr2.janusgate.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "nilJ07r1KZ0-KhmRNYeICXGhM9HeG9uxnRaqjYz3fWg"
      short-id: "6ed1d644822b2951"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_35"
    type: vless
    server: "173.199.70.108"
    port: 37185
    uuid: "a8bc03e1-8e80-4a40-863b-6032f3ab7ca8"
    udp: true
  - name: "🇫🇷_36"
    type: vless
    server: "162.19.10.99"
    port: 443
    uuid: "e8b1500b-e9e8-5492-8312-f4eadf7d0767"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "nasnet-162191099-direct.mbghalibaf.com"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_37"
    type: vless
    server: "83.136.211.167"
    port: 443
    uuid: "df880bf8-2635-4a83-a6bf-91bb36df284b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fr2.janusgate.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nilJ07r1KZ0-KhmRNYeICXGhM9HeG9uxnRaqjYz3fWg"
      short-id: "6ed1d644822b2951"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_38"
    type: vless
    server: "149.202.58.99"
    port: 443
    uuid: "b585dc5e-55bf-4a8b-913a-27c9ccac05c3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bab-6.site"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/vws/"
      headers:
        Host: "bab-6.site"
  - name: "🇫🇷_39"
    type: vless
    server: "OV-France1.09vpn.com"
    port: 80
    uuid: "f5c47e9c-914a-4a91-a81e-a5a77bc10fc1"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇫🇷_40"
    type: vless
    server: "83.136.210.59"
    port: 443
    uuid: "df880bf8-2635-4a83-a6bf-91bb36df284b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fr2.janusgate.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "nilJ07r1KZ0-KhmRNYeICXGhM9HeG9uxnRaqjYz3fWg"
      short-id: "6ed1d644822b2951"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_41"
    type: vless
    server: "5.196.243.4"
    port: 443
    uuid: "b4c5a66f-1f66-4262-b72d-c6aa661abc2c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0jolgptjjXxVsUgMPN_mcoyHET2uHQ7onbAMZ7uCc2w"
      short-id: "8d0a77a398415b0e"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_42"
    type: vless
    server: "169.58.143.21"
    port: 443
    uuid: "25f3beef-a4b6-40bc-aa74-17a0f89f683c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "finite-node.rtxconfigz.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "telegram.us"
  - name: "🇫🇷_43"
    type: vless
    server: "77.221.152.100"
    port: 443
    uuid: "0772109c-a680-4896-b005-d86513194f96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_44"
    type: vless
    server: "217.69.5.160"
    port: 13903
    uuid: "8c52f7db-9f22-49c0-b4be-c957b57b393a"
    udp: true
  - name: "🇫🇷_45"
    type: vless
    server: "usejh2.neobo-tooth.ru"
    port: 2083
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "usejh2.neobo-tooth.ru"
    client-fingerprint: "ios"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇫🇷_46"
    type: vless
    server: "node14.mxvpn.dev"
    port: 443
    uuid: "0772109c-a680-4896-b005-d86513194f96"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node14.mxvpn.dev"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw"
      short-id: "bbc68cec8bb8d2e3"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_47"
    type: vless
    server: "45.80.215.68"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "45.80.215.68"
  - name: "🇫🇷_48"
    type: vless
    server: "152.228.162.19"
    port: 80
    uuid: "25f86cb1-2140-4085-abcb-c3a0ea7a4be0"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇫🇷_49"
    type: vless
    server: "45.144.28.39"
    port: 2053
    uuid: "70e20b2e-3b1f-4c25-9a3d-9240570391bb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dRLd_E_GYCkCcwxLN5EcRQYsREKqisb26_ZSehxUpWY"
      short-id: "1eb8ea8dae937ae0"
    flow: "xtls-rprx-vision"
  - name: "🇫🇷_50"
    type: trojan
    server: "194.9.172.236"
    port: 1105
    password: "kakashka13222"
    sni: "194.9.172.236"
    skip-cert-verify: true
    udp: true
  - name: "🇫🇷_51"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_52"
    type: ss
    server: "38.180.92.242"
    port: 32245
    cipher: "chacha20-ietf-poly1305"
    password: "pFNN9jKe8jwD"
    udp: true
  - name: "🇫🇷_53"
    type: ss
    server: "38.180.92.242"
    port: 32245
    cipher: "chacha20-ietf-poly1305"
    password: "pFNN9jKe8jwD"
    udp: true
  - name: "🇫🇷_54"
    type: ss
    server: "51.77.225.200"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇫🇷_55"
    type: ss
    server: "51.255.13.232"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "BqnqToih0PbU"
    udp: true
  - name: "🇫🇷_56"
    type: ss
    server: "51.77.225.200"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇫🇷_1"
      - "🇫🇷_2"
      - "🇫🇷_3"
      - "🇫🇷_4"
      - "🇫🇷_5"
      - "🇫🇷_6"
      - "🇫🇷_7"
      - "🇫🇷_8"
      - "🇫🇷_9"
      - "🇫🇷_10"
      - "🇫🇷_11"
      - "🇫🇷_12"
      - "🇫🇷_13"
      - "🇫🇷_14"
      - "🇫🇷_15"
      - "🇫🇷_16"
      - "🇫🇷_17"
      - "🇫🇷_18"
      - "🇫🇷_19"
      - "🇫🇷_20"
      - "🇫🇷_21"
      - "🇫🇷_22"
      - "🇫🇷_23"
      - "🇫🇷_24"
      - "🇫🇷_25"
      - "🇫🇷_26"
      - "🇫🇷_27"
      - "🇫🇷_28"
      - "🇫🇷_29"
      - "🇫🇷_30"
      - "🇫🇷_31"
      - "🇫🇷_32"
      - "🇫🇷_33"
      - "🇫🇷_34"
      - "🇫🇷_35"
      - "🇫🇷_36"
      - "🇫🇷_37"
      - "🇫🇷_38"
      - "🇫🇷_39"
      - "🇫🇷_40"
      - "🇫🇷_41"
      - "🇫🇷_42"
      - "🇫🇷_43"
      - "🇫🇷_44"
      - "🇫🇷_45"
      - "🇫🇷_46"
      - "🇫🇷_47"
      - "🇫🇷_48"
      - "🇫🇷_49"
      - "🇫🇷_50"
      - "🇫🇷_51"
      - "🇫🇷_52"
      - "🇫🇷_53"
      - "🇫🇷_54"
      - "🇫🇷_55"
      - "🇫🇷_56"


rules:
  - MATCH,PROXY
