name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇬🇧_1"
    type: vless
    server: "91.193.58.215"
    port: 2083
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso4.1d.mom"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇬🇧_2"
    type: vless
    server: "144.31.213.225"
    port: 443
    uuid: "9e3de7f7-a595-4117-b1b6-dc41eb870ab1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ABNRlkjlonYV9TOFYgjWwz0wn1s6sg_yCErsLYkU_Sg"
      short-id: "d6ff9019a77e354a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_3"
    type: vless
    server: "5.253.38.161"
    port: 443
    uuid: "9bd29aae-51f9-31f3-a1dc-da8d01d68908"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "6099f3ccs374.csgfw.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ymymFdoobDai29Ww576QkQtEFftfyKFLAW58mPIJxkY"
      short-id: "f4b54c0a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_4"
    type: vless
    server: "91.193.58.219"
    port: 2053
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso4.1d.mom"
    network: ws
    ws-opts:
      path: "/socks5=888:888@hkip.1d.mom:1080fp=chrome"
      headers:
        Host: "vlso4.1d.mom"
  - name: "🇬🇧_5"
    type: vless
    server: "91.193.59.27"
    port: 2096
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso300.1d.mom"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇬🇧_6"
    type: vless
    server: "89.125.124.178"
    port: 8443
    uuid: "d71aecee-ef16-418e-baf5-2b2458122d5a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gb.wlrus.cfd"
    client-fingerprint: "firefox"
  - name: "🇬🇧_7"
    type: vless
    server: "46.250.240.80"
    port: 2053
    uuid: "5c53b9e9-fbe8-4c50-a623-73cdafa3886b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "cevjPz2GmTrXDFXQbGizdN6t4c6m11kclJEf5nOHOTE"
      short-id: "52dfc493bb6b6c16"
  - name: "🇬🇧_8"
    type: vless
    server: "54.37.7.73"
    port: 55605
    uuid: "f99439b7-97ab-4510-9c23-cdb4756b907e"
    udp: true
  - name: "🇬🇧_9"
    type: vless
    server: "149.248.79.235"
    port: 17301
    uuid: "3571b127-4b3b-4c01-8249-1684daf586b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "aws.amazon.com"
    reality-opts:
      public-key: "nadshlxG0RqC6om__cf9E4F6qolRmHJLcNtReBTr9xY"
      short-id: "5d"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_10"
    type: vless
    server: "169.197.113.179"
    port: 20190
    uuid: "ad4dd89a-2e4b-4f33-bb96-7e9c4eb85d0b"
    udp: true
  - name: "🇬🇧_11"
    type: vless
    server: "57.128.181.125"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇬🇧_12"
    type: vless
    server: "45.150.66.201"
    port: 443
    uuid: "19ac8928-fe6e-49af-a223-9ca127e4018f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.nvidia.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CTduQ5Pvex1U2D1ojmFgSF4MQ1N7Yft7EfnEEBK1l1U"
      short-id: "c571c801812c"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_13"
    type: vless
    server: "186.190.211.188"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "186.190.211.188"
  - name: "🇬🇧_14"
    type: vless
    server: "45.77.57.122"
    port: 443
    uuid: "6705ddbd-04cf-40f6-99b9-36846b08c2a9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kjgdksgghre466.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "kjgdksgghre466.pages.dev"
  - name: "🇬🇧_15"
    type: vless
    server: "5.253.38.67"
    port: 40444
    uuid: "ddfb7f45-8a5c-41d2-882e-50ed09701ce0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.lovelive-anime.jp"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ZZK_Oo5-iDDgoWzxIURTLWoKPbC8NFto3Mk7OvAZgRU"
      short-id: "b3f2a1c9"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_16"
    type: vless
    server: "83.147.18.3"
    port: 443
    uuid: "9f61cdf4-810d-4052-bbc7-2da0c8e20104"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "3iVJAIGPx6JMlhlRmfpGrHkSmLpHJ4CPvBBH7KsFrFA"
      short-id: "fd8cf7e1173f0edb"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_17"
    type: vless
    server: "193.219.99.235"
    port: 8443
    uuid: "6705ddbd-04cf-40f6-99b9-36846b08c2a9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kjgdksgghre466.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "kjgdksgghre466.pages.dev"
  - name: "🇬🇧_18"
    type: vless
    server: "194.146.24.240"
    port: 443
    uuid: "e911c552-3a98-41e0-b5fb-0dd3879887b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vod.ensf.top"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/v1/irc"
      headers:
        Host: "vod.ensf.top"
  - name: "🇬🇧_19"
    type: vless
    server: "57.129.132.223"
    port: 80
    uuid: "9e20b04d-5a81-4e16-b421-01e502f0aac6"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "google.com"
  - name: "🇬🇧_20"
    type: vless
    server: "185.193.30.94"
    port: 443
    uuid: "83afd88f-200f-4d89-bfc7-66eff160c1d8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "josni.hoyes.cloudns.ch"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇬🇧_21"
    type: vless
    server: "144.31.213.188"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-west.cendora.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0"
      short-id: "dd3ff38418d29d22"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_22"
    type: vless
    server: "194.150.166.12"
    port: 443
    uuid: "1e973bda-3a02-4431-9df8-83595f6f65d8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.avito.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b75SrHI--As9QxOVfRIPkGmGfXjs53CGAjbws2K99Rs"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_23"
    type: vless
    server: "194.150.166.12"
    port: 443
    uuid: "f1c496bf-d2ab-45be-bc13-051d60d227b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.avito.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "b75SrHI--As9QxOVfRIPkGmGfXjs53CGAjbws2K99Rs"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_24"
    type: vless
    server: "46.250.250.149"
    port: 2053
    uuid: "98944209-4d92-41b2-9c24-c5ac17b3b493"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "2mp1wwmKQyvIVuGujoT0AGoAHwP1IFXlZRj8jB_UnGo"
      short-id: "61abecf0a82c31f5"
  - name: "🇬🇧_25"
    type: vless
    server: "132.243.207.38"
    port: 4443
    uuid: "1f35c4eb-e4fa-5a62-b0e1-b557983b34c7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.vk.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "wg5YJMYIcqRU9X9U54TRzKIIw5aUyxIEI3tL_jck5WU"
      short-id: "44"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_26"
    type: vless
    server: "132.243.207.38"
    port: 5000
    uuid: "6a0a3a97-f063-5599-b5fa-2b5ad599a683"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.vk.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "0qifn7FGo1Fv6bAhw29gy5SmVHcWarBfIHTUPOwpXVs"
      short-id: "f8a5b26d5e"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_27"
    type: vless
    server: "5.253.38.67"
    port: 40444
    uuid: "eced0d03-e140-48f4-9de1-003499eeb45a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.lovelive-anime.jp"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ZZK_Oo5-iDDgoWzxIURTLWoKPbC8NFto3Mk7OvAZgRU"
      short-id: "b3f2a1c9"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_28"
    type: vless
    server: "164.37.104.234"
    port: 443
    uuid: "a6f6d9c9-9d43-4d0e-bf95-4b87cc5bbaac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gb1.murhost.network"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "-nB-tCeZ4Zr72ArHUKnbUphbs4PlBS6iId6PkrPQQTE"
      short-id: "84f9881951050a30"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_29"
    type: vless
    server: "51.89.194.151"
    port: 2053
    uuid: "bb742567-ec51-4956-9d3d-099e1a4d48c4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JH8yFK9WKJnwxF4HTGO2ZOXZDlaDqYzx3e5PvyeU8ww"
      short-id: "6edb6b2ddfed9e1c"
  - name: "🇬🇧_30"
    type: vless
    server: "144.31.213.150"
    port: 443
    uuid: "b052df40-d51c-456c-9bd6-57af01a87e4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.pinecloud.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vWSgdMDirb9aDZLWijSXXXl-NCTrtBgEe9MQqcgV6h8"
      short-id: "6a2e3af684799b19"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_31"
    type: vless
    server: "cdn.pinecloud.net"
    port: 443
    uuid: "b052df40-d51c-456c-9bd6-57af01a87e4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.pinecloud.net"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "vWSgdMDirb9aDZLWijSXXXl-NCTrtBgEe9MQqcgV6h8"
      short-id: "6a2e3af684799b19"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_32"
    type: vless
    server: "91.193.59.251"
    port: 2053
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso6.1d.mom"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇬🇧_33"
    type: vless
    server: "193.219.99.64"
    port: 8443
    uuid: "6705ddbd-04cf-40f6-99b9-36846b08c2a9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kjgdksgghre466.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "kjgdksgghre466.pages.dev"
  - name: "🇬🇧_34"
    type: vless
    server: "46.226.163.243"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-west.cendora.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "m6RDw1b8R4lCaRUIzhHpy6TtX2Dhk6nyby8dWzeQqA0"
      short-id: "dd3ff38418d29d22"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_35"
    type: vless
    server: "57.129.132.223"
    port: 80
    uuid: "dbb78c94-9f87-4d7d-b945-2000b60352fd"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "---@External_Net---@External_Net---@External_Net---@External_Net---@External_Net"
  - name: "🇬🇧_36"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "5c36ebc0-8515-11f1-af84-1239d0255272"
    sni: "chatbuzzteambhm.chatbuzzt7150.workers.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_37"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "179c5360-9538-11f1-9ff7-1239d0255272"
    sni: "chatbuzzteam.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_38"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "dec2d020-9537-11f1-8cf7-1239d0255272"
    sni: "chatbuzzteam.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_39"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "497f2520-9538-11f1-8291-1239d0255272"
    sni: "chatbuzzteam.ir"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_40"
    type: ss
    server: "141.98.101.181"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_41"
    type: ss
    server: "129.151.74.0"
    port: 61312
    cipher: "2022-blake3-chacha20-poly1305"
    password: "TXg10TkiRY05fey6NAHE/mWkCey4sX7NwOHGCjmidHM="
    udp: true
  - name: "🇬🇧_42"
    type: ss
    server: "158.173.24.73"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_43"
    type: ss
    server: "158.173.24.73"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_44"
    type: ss
    server: "141.98.101.181"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_45"
    type: ss
    server: "94.156.250.148"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇬🇧_1"
      - "🇬🇧_2"
      - "🇬🇧_3"
      - "🇬🇧_4"
      - "🇬🇧_5"
      - "🇬🇧_6"
      - "🇬🇧_7"
      - "🇬🇧_8"
      - "🇬🇧_9"
      - "🇬🇧_10"
      - "🇬🇧_11"
      - "🇬🇧_12"
      - "🇬🇧_13"
      - "🇬🇧_14"
      - "🇬🇧_15"
      - "🇬🇧_16"
      - "🇬🇧_17"
      - "🇬🇧_18"
      - "🇬🇧_19"
      - "🇬🇧_20"
      - "🇬🇧_21"
      - "🇬🇧_22"
      - "🇬🇧_23"
      - "🇬🇧_24"
      - "🇬🇧_25"
      - "🇬🇧_26"
      - "🇬🇧_27"
      - "🇬🇧_28"
      - "🇬🇧_29"
      - "🇬🇧_30"
      - "🇬🇧_31"
      - "🇬🇧_32"
      - "🇬🇧_33"
      - "🇬🇧_34"
      - "🇬🇧_35"
      - "🇬🇧_36"
      - "🇬🇧_37"
      - "🇬🇧_38"
      - "🇬🇧_39"
      - "🇬🇧_40"
      - "🇬🇧_41"
      - "🇬🇧_42"
      - "🇬🇧_43"
      - "🇬🇧_44"
      - "🇬🇧_45"


rules:
  - MATCH,PROXY
