name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇬🇧_1"
    type: vless
    server: "50.7.221.227"
    port: 443
    uuid: "8a180a9e-3218-4140-bfd3-56cf230d27f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cekflesmfkwmefsdar.fdc.video-mvm.ru"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_2"
    type: vless
    server: "node-uk.connectsuite.org"
    port: 8443
    uuid: "c08f0056-7a6d-4931-813b-aaa3cdd00aed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node-uk.connectsuite.org"
    client-fingerprint: "chrome"
  - name: "🇬🇧_3"
    type: vless
    server: "46.250.240.80"
    port: 2053
    uuid: "948df76f-505d-4608-9c76-a933ee3ccc76"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "CYFeysLf--_IVhxQOCd3ZxLrAVWFFOkJzvIGHOVXN3E"
      short-id: "4cc9dc65f7770115"
  - name: "🇬🇧_4"
    type: vless
    server: "83.147.18.3"
    port: 443
    uuid: "9f61cdf4-810d-4052-bbc7-2da0c8e20104"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "3iVJAIGPx6JMlhlRmfpGrHkSmLpHJ4CPvBBH7KsFrFA"
      short-id: "fd8cf7e1173f0edb"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_5"
    type: vless
    server: "82.39.171.12"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_6"
    type: vless
    server: "186.190.211.188"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "186.190.211.188"
  - name: "🇬🇧_7"
    type: vless
    server: "213.193.252.114"
    port: 443
    uuid: "f8ad55ea-ef42-434e-8e40-22605066624c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "only-cur2.voxicheck.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "_p24twNlnUIdoSiWlNoxSlu95PfQAoLIrxKQU4IBsU4"
      short-id: "abcd1234"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_8"
    type: vless
    server: "82.39.171.142"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_9"
    type: vless
    server: "50.7.221.219"
    port: 443
    uuid: "8a180a9e-3218-4140-bfd3-56cf230d27f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sdfsldkfslkdmf.fdc.video-mvm.ru"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_10"
    type: vless
    server: "46.250.250.149"
    port: 2053
    uuid: "b4caaf57-ad77-4948-a6f5-51b3513799bf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "hieuCHb3HYdDYHmTDyWw2SGqyfo36AVuA-wSiZMdU1M"
      short-id: "9922313fffed1c63"
  - name: "🇬🇧_11"
    type: vless
    server: "50.7.221.243"
    port: 443
    uuid: "8a180a9e-3218-4140-bfd3-56cf230d27f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "r4vsdfmsdlf8n3.fdc.video-mvm.ru"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_12"
    type: vless
    server: "159.65.51.189"
    port: 443
    uuid: "d342d11e-d224-4463-b982-532309285094"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ccc.010304.xyz"
    network: ws
    ws-opts:
      path: "/fp=chrome"
      headers:
        Host: "ccc.010304.xyz"
  - name: "🇬🇧_13"
    type: vless
    server: "83.147.18.75"
    port: 443
    uuid: "5de0c218-0138-45d8-94d2-c2c3f37a1a6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "tfFzmbVByvoZxxIEUiHMv22_k0-nQz00L0XjU0bd_Fc"
      short-id: "7f1e29593aa94ad1"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_14"
    type: vless
    server: "51.38.71.147"
    port: 8443
    uuid: "c08f0056-7a6d-4931-813b-aaa3cdd00aed"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "node-uk.connectsuite.org"
    client-fingerprint: "firefox"
  - name: "🇬🇧_15"
    type: vless
    server: "50.7.221.235"
    port: 443
    uuid: "8a180a9e-3218-4140-bfd3-56cf230d27f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "glokwdlemdklmwss.fdc.video-mvm.ru"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_16"
    type: vless
    server: "3.9.135.156"
    port: 51847
    uuid: "391a01e9-b664-407b-9158-610fab3f5920"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    reality-opts:
      public-key: "S6noV0L8eNASnTe1gXLutLZNdfENsvKMsOJiGQYi6nc"
      short-id: "0eec442e7b34d2f2"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_17"
    type: vless
    server: "91.208.92.210"
    port: 443
    uuid: "8fc806fa-350b-4548-937a-2bf35f7fe7eb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uk1.sky-vault.top"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "_KTsOFhGnC0W28ZqO8_FApozMp7tJ9cVBTLKLAA_OR0"
      short-id: "ae64c9b46bff174a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_18"
    type: vless
    server: "51.89.194.151"
    port: 2053
    uuid: "8e790f25-1d71-4601-9fb0-d503931dcfca"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "xPEBx4wUmwAAv4ikUALNBf5wH6TRhyeQ0Q2pcNELsV0"
      short-id: "d051f678212f9d54"
  - name: "🇬🇧_19"
    type: vless
    server: "57.129.132.223"
    port: 80
    uuid: "dbb78c94-9f87-4d7d-b945-2000b60352fd"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇬🇧_20"
    type: vless
    server: "57.129.132.223"
    port: 80
    uuid: "9e20b04d-5a81-4e16-b421-01e502f0aac6"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "google.com"
  - name: "🇬🇧_21"
    type: vless
    server: "23.81.34.204"
    port: 443
    uuid: "99955907-9070-46f0-a200-9c7a0b9d74fe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "J_p_dxR8dIKaezk1_Ins5MZ7e4dqgrr2n9690vVuQ2s"
      short-id: "b19b017d6f453873"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_22"
    type: ss
    server: "149.102.132.184"
    port: 443
    cipher: "aes-256-gcm"
    password: "g5h5jleTRSyO3Rk4"
    udp: true
  - name: "🇬🇧_23"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true
  - name: "🇬🇧_24"
    type: ss
    server: "149.102.149.207"
    port: 80
    cipher: "aes-256-gcm"
    password: "LXchLsIwtCeUAUgu"
    udp: true
  - name: "🇬🇧_25"
    type: ss
    server: "149.102.132.184"
    port: 80
    cipher: "aes-256-gcm"
    password: "g5h5jleTRSyO3Rk4"
    udp: true
  - name: "🇬🇧_26"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true
  - name: "🇬🇧_27"
    type: ss
    server: "158.173.24.73"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_28"
    type: ss
    server: "141.98.101.181"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_29"
    type: ss
    server: "51.77.225.200"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇬🇧_30"
    type: ss
    server: "158.173.24.73"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_31"
    type: ss
    server: "94.156.250.148"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇬🇧_32"
    type: ss
    server: "149.102.132.184"
    port: 80
    cipher: "aes-256-gcm"
    password: "g5h5jleTRSyO3Rk4"
    udp: true
  - name: "🇬🇧_33"
    type: ss
    server: "82.110.60.9"
    port: 19999
    cipher: "aes-256-gcm"
    password: "ZRpgaBeGxtENIXgvhpkZBKz9GnWRS2dYcx9O+a2iwN4="
    udp: true
  - name: "🇬🇧_34"
    type: ss
    server: "149.102.149.207"
    port: 80
    cipher: "aes-256-gcm"
    password: "LXchLsIwtCeUAUgu"
    udp: true
  - name: "🇬🇧_35"
    type: ss
    server: "149.102.149.207"
    port: 443
    cipher: "aes-256-gcm"
    password: "LXchLsIwtCeUAUgu"
    udp: true
  - name: "🇬🇧_36"
    type: ss
    server: "141.98.101.181"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_37"
    type: ss
    server: "51.77.225.200"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "zRZNBszYyWo5"
    udp: true
  - name: "🇬🇧_38"
    type: ss
    server: "149.102.149.207"
    port: 443
    cipher: "aes-256-gcm"
    password: "LXchLsIwtCeUAUgu"
    udp: true
  - name: "🇬🇧_39"
    type: ss
    server: "82.110.60.9"
    port: 19999
    cipher: "aes-256-gcm"
    password: "ZRpgaBeGxtENIXgvhpkZBKz9GnWRS2dYcx9O+a2iwN4="
    udp: true
  - name: "🇬🇧_40"
    type: ss
    server: "51.38.71.51"
    port: 2083
    cipher: "2022-blake3-aes-256-gcm"
    password: "cOiC+3JhAXMwdGV5exnrMSorJU0Rl5qlLCbCAuDlWY4=:2tFqykGqZ101XW11f6iRiERnPycFAjjYq0y2zUYhKho="
    udp: true
  - name: "🇬🇧_41"
    type: ss
    server: "149.102.132.184"
    port: 443
    cipher: "aes-256-gcm"
    password: "g5h5jleTRSyO3Rk4"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇬🇧_1"
      - "🇬🇧_2"
      - "🇬🇧_3"
      - "🇬🇧_4"
      - "🇬🇧_5"
      - "🇬🇧_6"
      - "🇬🇧_7"
      - "🇬🇧_8"
      - "🇬🇧_9"
      - "🇬🇧_10"
      - "🇬🇧_11"
      - "🇬🇧_12"
      - "🇬🇧_13"
      - "🇬🇧_14"
      - "🇬🇧_15"
      - "🇬🇧_16"
      - "🇬🇧_17"
      - "🇬🇧_18"
      - "🇬🇧_19"
      - "🇬🇧_20"
      - "🇬🇧_21"
      - "🇬🇧_22"
      - "🇬🇧_23"
      - "🇬🇧_24"
      - "🇬🇧_25"
      - "🇬🇧_26"
      - "🇬🇧_27"
      - "🇬🇧_28"
      - "🇬🇧_29"
      - "🇬🇧_30"
      - "🇬🇧_31"
      - "🇬🇧_32"
      - "🇬🇧_33"
      - "🇬🇧_34"
      - "🇬🇧_35"
      - "🇬🇧_36"
      - "🇬🇧_37"
      - "🇬🇧_38"
      - "🇬🇧_39"
      - "🇬🇧_40"
      - "🇬🇧_41"


rules:
  - MATCH,PROXY
