name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇬🇧_1"
    type: vless
    server: "82.39.171.31"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_2"
    type: vless
    server: "130.78.216.194"
    port: 443
    uuid: "2a12bb81-f3a3-0064-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "calm-panther.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "X44VAj_y9MabQeF7ZgssR57zaf2Rx5bX--BJ-U9wQ2o"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_3"
    type: vless
    server: "194.150.166.12"
    port: 443
    uuid: "f1c496bf-d2ab-45be-bc13-051d60d227b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.avito.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "b75SrHI--As9QxOVfRIPkGmGfXjs53CGAjbws2K99Rs"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_4"
    type: vless
    server: "139.59.191.88"
    port: 443
    uuid: "a6c5f4c7-073f-416b-b5e3-4a86ec2d9f22"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.stanford.edu"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "JeaMU58AmMJ2JqJ-QGotRFua9DYxxveqw7I_XMWCu34"
      short-id: "2da3ecc3ad9a323b"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_5"
    type: vless
    server: "57.129.132.223"
    port: 80
    uuid: "9e20b04d-5a81-4e16-b421-01e502f0aac6"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "google.com"
  - name: "🇬🇧_6"
    type: vless
    server: "46.250.250.149"
    port: 2053
    uuid: "98944209-4d92-41b2-9c24-c5ac17b3b493"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "2mp1wwmKQyvIVuGujoT0AGoAHwP1IFXlZRj8jB_UnGo"
      short-id: "61abecf0a82c31f5"
  - name: "🇬🇧_7"
    type: vless
    server: "91.193.58.217"
    port: 2053
    uuid: "a1de0630-5786-48a0-84f6-dc6f2de10d6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vlso200.1d.mom"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇬🇧_8"
    type: vless
    server: "46.250.240.80"
    port: 2053
    uuid: "5c53b9e9-fbe8-4c50-a623-73cdafa3886b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "cevjPz2GmTrXDFXQbGizdN6t4c6m11kclJEf5nOHOTE"
      short-id: "52dfc493bb6b6c16"
  - name: "🇬🇧_9"
    type: vless
    server: "89.125.124.104"
    port: 1337
    uuid: "ccd2bfcd-b949-476d-bd6e-710a41021b1c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eng.xanka.best"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "MKoeqrRMeryTxhSbcrPmoMZKKtd9268vwsiZ22w2Gig"
      short-id: "be901ea3"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_10"
    type: vless
    server: "130.78.216.196"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "calm-panther.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "X44VAj_y9MabQeF7ZgssR57zaf2Rx5bX--BJ-U9wQ2o"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_11"
    type: vless
    server: "185.232.117.115"
    port: 443
    uuid: "c04bf2df-2b7f-44da-a893-3792d3910fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vl05.skorostnet.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_12"
    type: vless
    server: "67.159.56.57"
    port: 443
    uuid: "52b71b75-4b77-4cec-990b-046ec1938e1f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uk.bvps.cloud"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "j5qmR8E9er-0n5zZbK6s_SdvYm-tYlraXVYm49ArWS8"
      short-id: "60debb3ab744d8ce"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_13"
    type: vless
    server: "191.215.37.90"
    port: 443
    uuid: "SoonTeam"
    udp: true
  - name: "🇬🇧_14"
    type: vless
    server: "82.39.171.131"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "ios"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_15"
    type: vless
    server: "82.39.171.145"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_16"
    type: vless
    server: "164.37.109.187"
    port: 443
    uuid: "c28ee61d-0d43-0064-8e6a-6397ed0ffc03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gb.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "sBSNX3DhJSWOkqTmRHisayVLisCBQLb4JcpKzwCrvC0"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_17"
    type: vless
    server: "130.78.216.194"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "calm-panther.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "X44VAj_y9MabQeF7ZgssR57zaf2Rx5bX--BJ-U9wQ2o"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_18"
    type: vless
    server: "82.39.171.16"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_19"
    type: vless
    server: "89.125.124.178"
    port: 8443
    uuid: "11b7e901-e970-4491-9c7d-13c153e39e5b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gb.wlrus.cfd"
    client-fingerprint: "firefox"
  - name: "🇬🇧_20"
    type: vless
    server: "149.248.79.235"
    port: 17301
    uuid: "3571b127-4b3b-4c01-8249-1684daf586b5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "aws.amazon.com"
    reality-opts:
      public-key: "nadshlxG0RqC6om__cf9E4F6qolRmHJLcNtReBTr9xY"
      short-id: "5d"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇬🇧_21"
    type: vless
    server: "164.37.104.149"
    port: 443
    uuid: "c28ee61d-0d43-0065-8e6a-6397ed0ffc03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gb.cdn.cachefleet.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "sBSNX3DhJSWOkqTmRHisayVLisCBQLb4JcpKzwCrvC0"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_22"
    type: vless
    server: "130.78.216.197"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "luminous-jolt.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "X44VAj_y9MabQeF7ZgssR57zaf2Rx5bX--BJ-U9wQ2o"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_23"
    type: vless
    server: "164.37.105.37"
    port: 443
    uuid: "c28ee61d-0d43-4e69-8e6a-6397ed0ffc03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sl.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "sBSNX3DhJSWOkqTmRHisayVLisCBQLb4JcpKzwCrvC0"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_24"
    type: vless
    server: "144.31.213.225"
    port: 443
    uuid: "9e3de7f7-a595-4117-b1b6-dc41eb870ab1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ABNRlkjlonYV9TOFYgjWwz0wn1s6sg_yCErsLYkU_Sg"
      short-id: "d6ff9019a77e354a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_25"
    type: vless
    server: "185.232.117.113"
    port: 443
    uuid: "c04bf2df-2b7f-44da-a893-3792d3910fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vl03.skorostnet.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_26"
    type: vless
    server: "186.190.211.188"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "186.190.211.188"
  - name: "🇬🇧_27"
    type: vless
    server: "54.37.3.0"
    port: 40813
    uuid: "26c0589f-79e5-4789-8ff7-914f2e26e8e5"
    udp: true
  - name: "🇬🇧_28"
    type: vless
    server: "global-video2.ruvps.pro"
    port: 443
    uuid: "9847793c-3860-41e8-9838-b21bccdc013a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "global-video.ruvps.pro"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "rCipfShXDNFO3P-H78EkGj53JoqWgt6JeMq6wztvH08"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_29"
    type: vless
    server: "185.232.117.114"
    port: 443
    uuid: "c04bf2df-2b7f-44da-a893-3792d3910fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vl04.skorostnet.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_30"
    type: vless
    server: "194.150.166.12"
    port: 443
    uuid: "1e973bda-3a02-4431-9df8-83595f6f65d8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.avito.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b75SrHI--As9QxOVfRIPkGmGfXjs53CGAjbws2K99Rs"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_31"
    type: vless
    server: "169.197.113.179"
    port: 20190
    uuid: "ad4dd89a-2e4b-4f33-bb96-7e9c4eb85d0b"
    udp: true
  - name: "🇬🇧_32"
    type: vless
    server: "130.78.216.195"
    port: 443
    uuid: "2a12bb81-f3a3-41bb-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "quiet-bear.cdn.cachefleet.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "X44VAj_y9MabQeF7ZgssR57zaf2Rx5bX--BJ-U9wQ2o"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_33"
    type: vless
    server: "130.78.216.194"
    port: 443
    uuid: "2a12bb81-f3a3-0065-99ab-36febf676b4a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "quiet-bear.cdn.cachefleet.com"
    reality-opts:
      public-key: "X44VAj_y9MabQeF7ZgssR57zaf2Rx5bX--BJ-U9wQ2o"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_34"
    type: vless
    server: "82.39.171.148"
    port: 443
    uuid: "d65cc14c-f53f-4fe2-b262-97856601319c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "e2RLf57Li_-MDZGE9ss1BWPgP54mqRb5PfXhW2jcVVg"
      short-id: "c39cc7310a"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_35"
    type: vless
    server: "144.31.213.150"
    port: 443
    uuid: "b052df40-d51c-456c-9bd6-57af01a87e4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.pinecloud.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "vWSgdMDirb9aDZLWijSXXXl-NCTrtBgEe9MQqcgV6h8"
      short-id: "6a2e3af684799b19"
    flow: "xtls-rprx-vision"
  - name: "🇬🇧_36"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "41290c00-8515-11f1-aefe-1239d0255272"
    sni: "chatbuzzteambhm.chatbuzzt7150.workers.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_37"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "5c36ebc0-8515-11f1-af84-1239d0255272"
    sni: "chatbuzzteambhm.chatbuzzt7150.workers.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_38"
    type: trojan
    server: "217.217.222.230"
    port: 20004
    password: "ba07a8af-5544-48ac-ab62-3b6c00a44fa6"
    sni: "hk.catxstar.com"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_39"
    type: trojan
    server: "uk1.test3.net"
    port: 443
    password: "6bd65120-8515-11f1-8fef-1239d0255272"
    sni: "chatbuzzteambhm.chatbuzzt7150.workers.dev"
    skip-cert-verify: true
    udp: true
  - name: "🇬🇧_40"
    type: ss
    server: "141.98.101.182"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_41"
    type: ss
    server: "134.65.57.130"
    port: 61312
    cipher: "chacha20-ietf-poly1305"
    password: "MGU4ZjVkMGNhY2Y3YzM0NmIxMDgyNDQ5OGVjZjY2Y2Y="
    udp: true
  - name: "🇬🇧_42"
    type: ss
    server: "129.151.81.224"
    port: 61312
    cipher: "chacha20-ietf-poly1305"
    password: "MGU4ZjVkMGNhY2Y3YzM0NmIxMDgyNDQ5OGVjZjY2Y2Y="
    udp: true
  - name: "🇬🇧_43"
    type: ss
    server: "194.164.92.198"
    port: 1234
    cipher: "chacha20-ietf-poly1305"
    password: "zz0dHjDfoaSaZuRFLGH-hNfBALSEJUYD"
    udp: true
  - name: "🇬🇧_44"
    type: ss
    server: "94.156.250.148"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇬🇧_45"
    type: ss
    server: "194.164.92.198"
    port: 1234
    cipher: "chacha20-ietf-poly1305"
    password: "zz0dHjDfoaSaZuRFLGH-hNfBALSEJUYD"
    udp: true
  - name: "🇬🇧_46"
    type: ss
    server: "158.173.24.73"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_47"
    type: ss
    server: "141.98.101.182"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_48"
    type: ss
    server: "141.98.101.181"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_49"
    type: ss
    server: "141.98.101.182"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_50"
    type: ss
    server: "141.98.101.181"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇬🇧_51"
    type: ss
    server: "141.98.101.179"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇬🇧_1"
      - "🇬🇧_2"
      - "🇬🇧_3"
      - "🇬🇧_4"
      - "🇬🇧_5"
      - "🇬🇧_6"
      - "🇬🇧_7"
      - "🇬🇧_8"
      - "🇬🇧_9"
      - "🇬🇧_10"
      - "🇬🇧_11"
      - "🇬🇧_12"
      - "🇬🇧_13"
      - "🇬🇧_14"
      - "🇬🇧_15"
      - "🇬🇧_16"
      - "🇬🇧_17"
      - "🇬🇧_18"
      - "🇬🇧_19"
      - "🇬🇧_20"
      - "🇬🇧_21"
      - "🇬🇧_22"
      - "🇬🇧_23"
      - "🇬🇧_24"
      - "🇬🇧_25"
      - "🇬🇧_26"
      - "🇬🇧_27"
      - "🇬🇧_28"
      - "🇬🇧_29"
      - "🇬🇧_30"
      - "🇬🇧_31"
      - "🇬🇧_32"
      - "🇬🇧_33"
      - "🇬🇧_34"
      - "🇬🇧_35"
      - "🇬🇧_36"
      - "🇬🇧_37"
      - "🇬🇧_38"
      - "🇬🇧_39"
      - "🇬🇧_40"
      - "🇬🇧_41"
      - "🇬🇧_42"
      - "🇬🇧_43"
      - "🇬🇧_44"
      - "🇬🇧_45"
      - "🇬🇧_46"
      - "🇬🇧_47"
      - "🇬🇧_48"
      - "🇬🇧_49"
      - "🇬🇧_50"
      - "🇬🇧_51"


rules:
  - MATCH,PROXY
