name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇰_1"
    type: vless
    server: "47.86.249.58"
    port: 41528
    uuid: "97672a88-ec39-4234-a102-1df6f9236f36"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "vSXM6NtiXtPcwqZpXCTpKLBOPewzcEfr9-p18aiywio"
      short-id: "b4"
  - name: "🇭🇰_2"
    type: vless
    server: "85.11.161.8"
    port: 444
    uuid: "0b9bcbc1-b289-4a64-86fa-a5b731b65384"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "lxq7uAa7l0ozobBgTRrQIF_aCxDeJqZZFaNv8CFA9TQ"
      short-id: "8622176789abcdef"
    network: grpc
    grpc-opts:
      grpc-service-name: "web.max.ru"
  - name: "🇭🇰_3"
    type: vless
    server: "141.11.149.200"
    port: 11650
    uuid: "2aa2be33-b987-461e-8d0e-2ffe15cb8e4c"
    udp: true
  - name: "🇭🇰_4"
    type: vless
    server: "hk.vrsvpn.com"
    port: 444
    uuid: "0b9bcbc1-b289-4a64-86fa-a5b731b65384"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "web.max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "lxq7uAa7l0ozobBgTRrQIF_aCxDeJqZZFaNv8CFA9TQ"
      short-id: "8622176789abcdef"
    network: grpc
    grpc-opts:
      grpc-service-name: "web.max.ru"
  - name: "🇭🇰_5"
    type: vless
    server: "39.109.117.110"
    port: 43646
    uuid: "d92afe21-8e8b-42c7-98c2-8a33da64d28f"
    udp: true
    network: ws
    ws-opts:
      path: "/d92afe21"
  - name: "🇭🇰_6"
    type: vless
    server: "34.96.200.38"
    port: 443
    uuid: "2058418a-7718-4050-bdd5-db7487ffdb3b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "uoXBNYcBgR-h2YmU1NFhFyASr6qh9UghWOuo1WZIikw"
      short-id: "17d824dd68e24aaf"
  - name: "🇭🇰_7"
    type: vless
    server: "212.192.15.191"
    port: 443
    uuid: "5d02517f-63d5-3e9f-b467-1bcf4d4e25d3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u695099u36cf43b9s298.wagahaha.xyz"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_8"
    type: vless
    server: "35.241.98.220"
    port: 443
    uuid: "96563f88-f743-4395-a3b2-27ec462ae45e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bSK8gtmPMlw7gP415tmh6kQzzFiwzxBsT3Kuqql6cRo"
      short-id: "ec2c7091fe76336c"
  - name: "🇭🇰_9"
    type: vless
    server: "182.16.61.2"
    port: 45647
    uuid: "caec0d8d-ab2f-4247-b97d-7fb1a34ab195"
    udp: true
  - name: "🇭🇰_10"
    type: vless
    server: "38.207.177.236"
    port: 443
    uuid: "9c64064c-aaaf-449f-9344-77632fc9ff1c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "maES4RMEtsm5emBCixDRa6Y5GvmVwmwZNBL2G4Q03D4"
      short-id: "47de54e71fee3451"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_11"
    type: vless
    server: "182.16.61.3"
    port: 45647
    uuid: "431fe973-a43a-4fac-bf83-2a772e0d0625"
    udp: true
  - name: "🇭🇰_12"
    type: vless
    server: "47.83.153.19"
    port: 59750
    uuid: "9e76cfb8-b7a6-40f6-c2aa-9905aa19f31b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "W9BjX6YmCIVsjhKMlz233Yoe0xcf0SVHfvPKqbf3vCg"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_13"
    type: trojan
    server: "electric-gibbon.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "electric-gibbon.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_14"
    type: trojan
    server: "growing-oyster.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "growing-oyster.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_15"
    type: trojan
    server: "modern-bedbug.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "modern-bedbug.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_16"
    type: trojan
    server: "well-marmot.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "well-marmot.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_17"
    type: trojan
    server: "engaging-llama.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "engaging-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_18"
    type: trojan
    server: "185.244.208.210"
    port: 443
    password: "ND91608427"
    sni: "upright-hamster.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_19"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_20"
    type: trojan
    server: "ace-starling.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "ace-starling.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_21"
    type: trojan
    server: "summary-dragon.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "summary-dragon.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_22"
    type: trojan
    server: "91.199.84.120"
    port: 443
    password: "ND91608427"
    sni: "dynamic-grubworm.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_23"
    type: trojan
    server: "helped-buck.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "helped-buck.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_24"
    type: trojan
    server: "pretty-vervet.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "pretty-vervet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_25"
    type: trojan
    server: "ideal-robin.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "ideal-robin.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_26"
    type: trojan
    server: "just-alpaca.rooster465.autos"
    port: 443
    password: "IL37892054"
    sni: "just-alpaca.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_27"
    type: trojan
    server: "dynamic-grubworm.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "dynamic-grubworm.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_28"
    type: trojan
    server: "normal-elk.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "normal-elk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_29"
    type: trojan
    server: "wealthy-loon.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "wealthy-loon.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_30"
    type: trojan
    server: "saved-mudfish.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "saved-mudfish.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_31"
    type: trojan
    server: "18.163.180.201"
    port: 6357
    password: "d1960ba9f0f6353353994fa844cf817b"
    sni: "www.nintendogames.net"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_32"
    type: trojan
    server: "striking-cheetah.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "striking-cheetah.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_33"
    type: trojan
    server: "natural-swan.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "natural-swan.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_34"
    type: trojan
    server: "upright-bedbug.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "upright-bedbug.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_35"
    type: trojan
    server: "leading-ram.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "leading-ram.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_36"
    type: trojan
    server: "just-alpaca.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "just-alpaca.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_37"
    type: trojan
    server: "renewing-ewe.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "renewing-ewe.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_38"
    type: trojan
    server: "modest-foal.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "modest-foal.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_39"
    type: trojan
    server: "upright-hamster.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "upright-hamster.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_40"
    type: trojan
    server: "dynamic-grubworm.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "dynamic-grubworm.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_41"
    type: trojan
    server: "humorous-parakeet.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "humorous-parakeet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_42"
    type: trojan
    server: "kind-unicorn.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "kind-unicorn.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_43"
    type: trojan
    server: "185.244.208.13"
    port: 443
    password: "ND91608427"
    sni: "ace-starling.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_44"
    type: trojan
    server: "strong-haddock.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "strong-haddock.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_45"
    type: trojan
    server: "growing-oyster.rooster465.autos"
    port: 443
    password: "XG59623478"
    sni: "growing-oyster.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_46"
    type: trojan
    server: "sensible-haddock.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "sensible-haddock.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_47"
    type: trojan
    server: "eternal-swift.rooster465.autos"
    port: 443
    password: "FC60532879"
    sni: "eternal-swift.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇰_1"
      - "🇭🇰_2"
      - "🇭🇰_3"
      - "🇭🇰_4"
      - "🇭🇰_5"
      - "🇭🇰_6"
      - "🇭🇰_7"
      - "🇭🇰_8"
      - "🇭🇰_9"
      - "🇭🇰_10"
      - "🇭🇰_11"
      - "🇭🇰_12"
      - "🇭🇰_13"
      - "🇭🇰_14"
      - "🇭🇰_15"
      - "🇭🇰_16"
      - "🇭🇰_17"
      - "🇭🇰_18"
      - "🇭🇰_19"
      - "🇭🇰_20"
      - "🇭🇰_21"
      - "🇭🇰_22"
      - "🇭🇰_23"
      - "🇭🇰_24"
      - "🇭🇰_25"
      - "🇭🇰_26"
      - "🇭🇰_27"
      - "🇭🇰_28"
      - "🇭🇰_29"
      - "🇭🇰_30"
      - "🇭🇰_31"
      - "🇭🇰_32"
      - "🇭🇰_33"
      - "🇭🇰_34"
      - "🇭🇰_35"
      - "🇭🇰_36"
      - "🇭🇰_37"
      - "🇭🇰_38"
      - "🇭🇰_39"
      - "🇭🇰_40"
      - "🇭🇰_41"
      - "🇭🇰_42"
      - "🇭🇰_43"
      - "🇭🇰_44"
      - "🇭🇰_45"
      - "🇭🇰_46"
      - "🇭🇰_47"


rules:
  - MATCH,PROXY
