name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇰_1"
    type: vless
    server: "27.50.49.7"
    port: 8443
    uuid: "7967bf59-57e3-4cde-9898-527b0fe60022"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speed.dulacloud.store"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/dula?Telegram-WangCai2"
      headers:
        Host: "speed.dulacloud.store"
  - name: "🇭🇰_2"
    type: vless
    server: "hk3n.wxgqlfx.vip"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_3"
    type: vless
    server: "hk03.ccdn3.work"
    port: 749
    uuid: "d09c4ed0-a8bf-11f0-b155-cb2d176add19"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "i1.hdslb.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ONLHjUWWv77ovNCrMmckWc0N-1Lc5LEZCMoXbqd20SQ"
      short-id: "00c76c51392e7812"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_4"
    type: vless
    server: "47.239.6.251"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_5"
    type: vless
    server: "47.238.210.5"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
  - name: "🇭🇰_6"
    type: vless
    server: "156.226.168.221"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_7"
    type: vless
    server: "family.bucket.x1.kfc-520.com"
    port: 10202
    uuid: "8cb0c4fb-03ee-35b8-a47b-cd1d7e76dfd3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "E0R7f_nEkbcnc97Z82aDMo2bUVGgcIzChCVYwsQmXnc"
      short-id: "88bd7f"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_8"
    type: vless
    server: "hk03.ccdn3.work"
    port: 757
    uuid: "d09c4ed0-a8bf-11f0-b155-cb2d176add19"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "i1.hdslb.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TOEfmCDbdYjHFdzEAsMTMfXRB-k80zZ5uZV45g3SJRI"
      short-id: "cd0cfab98411cbb7"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_9"
    type: vless
    server: "hk-1.gsafevpnapi.com"
    port: 20270
    uuid: "8f2774ba-73fe-404d-a01b-7c01812ff75b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "0MIamX22OTB4zDokZ5WN_GHBVYs7MkFceuipUvql9Q8"
      short-id: "d5b538acf8a93540"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_10"
    type: vless
    server: "34.92.145.185"
    port: 443
    uuid: "75d38591-267e-4d89-98bc-164f25b50880"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HV_4dmK3rwzqhWP1yOpC1L8BObd5lpZRYTzUflsi2x4"
      short-id: "64b3f192fc0669e1"
  - name: "🇭🇰_11"
    type: trojan
    server: "47.240.80.220"
    port: 2052
    password: "tFjD2X1F6i9FfWp2GDU5Vbi1conuaChDKIYbw9zMFrqvMoSz"
    sni: "vpn.12169.top"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_12"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_13"
    type: trojan
    server: "2.27.109.179"
    port: 45464
    password: "XuMweB2PWs"
    sni: "2.27.109.179.sslip.io"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_14"
    type: ss
    server: "mn.qwer-cn.org"
    port: 10936
    cipher: "aes-128-gcm"
    password: "3234f051-172a-4d96-9f8d-2aeec41cd6a5"
    udp: true
  - name: "🇭🇰_15"
    type: ss
    server: "mn.qwer-cn.org"
    port: 10925
    cipher: "aes-128-gcm"
    password: "3234f051-172a-4d96-9f8d-2aeec41cd6a5"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇰_1"
      - "🇭🇰_2"
      - "🇭🇰_3"
      - "🇭🇰_4"
      - "🇭🇰_5"
      - "🇭🇰_6"
      - "🇭🇰_7"
      - "🇭🇰_8"
      - "🇭🇰_9"
      - "🇭🇰_10"
      - "🇭🇰_11"
      - "🇭🇰_12"
      - "🇭🇰_13"
      - "🇭🇰_14"
      - "🇭🇰_15"


rules:
  - MATCH,PROXY
