name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇭🇰_1"
    type: vless
    server: "35.241.98.220"
    port: 443
    uuid: "96563f88-f743-4395-a3b2-27ec462ae45e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bSK8gtmPMlw7gP415tmh6kQzzFiwzxBsT3Kuqql6cRo"
      short-id: "ec2c7091fe76336c"
  - name: "🇭🇰_2"
    type: vless
    server: "34.96.200.38"
    port: 443
    uuid: "2058418a-7718-4050-bdd5-db7487ffdb3b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "uoXBNYcBgR-h2YmU1NFhFyASr6qh9UghWOuo1WZIikw"
      short-id: "17d824dd68e24aaf"
  - name: "🇭🇰_3"
    type: vless
    server: "182.16.61.2"
    port: 45647
    uuid: "caec0d8d-ab2f-4247-b97d-7fb1a34ab195"
    udp: true
  - name: "🇭🇰_4"
    type: vless
    server: "47.239.6.251"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_5"
    type: vless
    server: "47.238.210.5"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
  - name: "🇭🇰_6"
    type: vless
    server: "103.149.183.198"
    port: 13779
    uuid: "928e6cce-8ced-4243-9a48-a6642edd09b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tesla.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg"
      short-id: "af1bdd293097b664"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_7"
    type: vless
    server: "fv2026.node2.top"
    port: 21001
    uuid: "feea2490-9926-41ff-90fc-4375f24bdae6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "itunes.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HWUNFHoOryJHQXKF-ZOm6wMYZdVJwH5aHGa5I9_HDGA"
      short-id: "dfa28122"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_8"
    type: vless
    server: "vj37-1936vtw.fincore.top"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_9"
    type: vless
    server: "162.141.137.231"
    port: 55371
    uuid: "5b23f73a-1f63-4618-a8f4-40ade38f7bff"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "swdist.apple.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "synxygq0ozctiW0jNF1mmvAI9PainW0rBfqe11LkeAM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_10"
    type: vless
    server: "182.16.61.5"
    port: 45647
    uuid: "6f361c37-bc54-43dd-8c8b-0f59354745a5"
    udp: true
  - name: "🇭🇰_11"
    type: vless
    server: "162.128.157.164"
    port: 443
    uuid: "5e8e81ac-a1c4-4543-b81e-651bf9872b54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.bing.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "TP_bpIPUtjdxxGA9j7mpsHtSDfM2HMSZFNWW9MtDPT0"
      short-id: "14156e3ac23212cc"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_12"
    type: vless
    server: "155.117.224.127"
    port: 443
    uuid: "9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "j.n.i.l.6.m.7.3.o.t.e.s.j.3.us.art-us.kdns.fr"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇭🇰_13"
    type: vless
    server: "xiweini.dpdns.org"
    port: 30100
    uuid: "19bb341c-ee57-4899-b1e7-e9d3ebdf23df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xiweini.dpdns.org"
    client-fingerprint: "chrome"
  - name: "🇭🇰_14"
    type: vless
    server: "161.81.30.254"
    port: 30100
    uuid: "19bb341c-ee57-4899-b1e7-e9d3ebdf23df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "xiweini.dpdns.org"
    client-fingerprint: "firefox"
  - name: "🇭🇰_15"
    type: vless
    server: "156.226.168.221"
    port: 35193
    uuid: "35cbae61-ee10-4cb9-abb8-4950b35e9851"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "d_pn_DMaIxhCkNh80h0Mc7nP94hrlN--I8liOIREDxE"
      short-id: "e8daed2d"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_16"
    type: vless
    server: "103.148.73.144"
    port: 8443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇭🇰_17"
    type: vless
    server: "103.148.73.167"
    port: 8443
    uuid: "f1d247db-d7ce-4eb8-9c0d-7b10603cd0b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ty986gfazs.cainiaohub.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/81574b6b-c9d7-44a0-b83d-dad56e8cb530"
      headers:
        Host: "ty986gfazs.cainiaohub.xyz"
  - name: "🇭🇰_18"
    type: vless
    server: "nian.001.url111.kcloud02.top"
    port: 15006
    uuid: "399c4c9b-27e1-37f1-9dce-22ccc2727a86"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.adobe.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "g9KZONtwSL8mL772rps2nXVAuQpsgHY33K_pHpI89Rg"
      short-id: "029a6cc4"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_19"
    type: vless
    server: "47.83.153.19"
    port: 59750
    uuid: "9e76cfb8-b7a6-40f6-c2aa-9905aa19f31b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "W9BjX6YmCIVsjhKMlz233Yoe0xcf0SVHfvPKqbf3vCg"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_20"
    type: vless
    server: "141.11.76.57"
    port: 21001
    uuid: "3a787d38-aa96-4235-bc3e-248f9ad9ea2b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "itunes.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HWUNFHoOryJHQXKF-ZOm6wMYZdVJwH5aHGa5I9_HDGA"
      short-id: "dfa28122"
    flow: "xtls-rprx-vision"
  - name: "🇭🇰_21"
    type: trojan
    server: "krhtybay.catcat321.com"
    port: 20065
    password: "7e70223b-f331-41d5-9313-02b8d2df2885"
    sni: "hk.catxstar.com"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_22"
    type: trojan
    server: "d3.catcat321.com"
    port: 20065
    password: "7e70223b-f331-41d5-9313-02b8d2df2885"
    sni: "hk.catxstar.com"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_23"
    type: trojan
    server: "119.246.1.143"
    port: 443
    password: "BxceQaOe"
    sni: "119.246.1.143"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_24"
    type: trojan
    server: "45.67.201.210"
    port: 20065
    password: "7e70223b-f331-41d5-9313-02b8d2df2885"
    sni: "hk.catxstar.com"
    skip-cert-verify: true
    udp: true
  - name: "🇭🇰_25"
    type: ss
    server: "sknsdc.hotssid.com"
    port: 10705
    cipher: "aes-256-gcm"
    password: "a02dba9c-05d5-42b1-9433-580aff27be2b"
    udp: true
  - name: "🇭🇰_26"
    type: ss
    server: "95.40.120.162"
    port: 8319
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true
  - name: "🇭🇰_27"
    type: ss
    server: "95.40.120.162"
    port: 8316
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true
  - name: "🇭🇰_28"
    type: ss
    server: "156.238.244.206"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "YMS0xsHjV1Qhg6ZOtqKOxg=="
    udp: true
  - name: "🇭🇰_29"
    type: ss
    server: "95.40.120.162"
    port: 8319
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true
  - name: "🇭🇰_30"
    type: ss
    server: "95.40.120.162"
    port: 8316
    cipher: "chacha20-ietf-poly1305"
    password: "ljqdalu13.."
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇭🇰_1"
      - "🇭🇰_2"
      - "🇭🇰_3"
      - "🇭🇰_4"
      - "🇭🇰_5"
      - "🇭🇰_6"
      - "🇭🇰_7"
      - "🇭🇰_8"
      - "🇭🇰_9"
      - "🇭🇰_10"
      - "🇭🇰_11"
      - "🇭🇰_12"
      - "🇭🇰_13"
      - "🇭🇰_14"
      - "🇭🇰_15"
      - "🇭🇰_16"
      - "🇭🇰_17"
      - "🇭🇰_18"
      - "🇭🇰_19"
      - "🇭🇰_20"
      - "🇭🇰_21"
      - "🇭🇰_22"
      - "🇭🇰_23"
      - "🇭🇰_24"
      - "🇭🇰_25"
      - "🇭🇰_26"
      - "🇭🇰_27"
      - "🇭🇰_28"
      - "🇭🇰_29"
      - "🇭🇰_30"


rules:
  - MATCH,PROXY
