name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇷_1"
    type: vless
    server: "5.202.4.207"
    port: 443
    uuid: "c26fe2f0-5c69-11f1-8a1a-bf116ceb9215"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "aparat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "fwS6bEyF28VsSapBZZ2vz6LJmVismH0NYupk6STFRWc"
      short-id: "f373df45a687eaff"
  - name: "🇮🇷_2"
    type: vless
    server: "45.131.4.192"
    port: 80
    uuid: "5f4845b4-11dc-41d6-9508-4ff6a02e36c1"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "silent-paper-fa57.fipiyag989.workers.dev"
  - name: "🇮🇷_3"
    type: vless
    server: "g1.kxpqus.bestxau.ir"
    port: 36171
    uuid: "d65a82af-a403-405e-8b7b-27a68b830511"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn-apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "NMbNnf_5ef8NzcvuN6McTRCNT3UozSjPKU7BeH9XwGU"
      short-id: "445e71ae7a0dae95"
    flow: "xtls-rprx-vision"
  - name: "🇮🇷_4"
    type: vless
    server: "g1.haxat.bestvbest.ir"
    port: 20610
    uuid: "d65a82af-a403-405e-8b7b-27a68b830511"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "doctor-yab.ir"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "lcXIrYi2o8yXrYHR321qQ--5lqVT8a6TKbaGpYTq4CI"
      short-id: "1d1a8f9fefeff5e6"
  - name: "🇮🇷_5"
    type: trojan
    server: "45.131.4.118"
    port: 443
    password: "f18d6149-e214-8554-e737-f7523c8b2eea"
    sni: "0403.infinityconfig4.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sync"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇷_1"
      - "🇮🇷_2"
      - "🇮🇷_3"
      - "🇮🇷_4"
      - "🇮🇷_5"


rules:
  - MATCH,PROXY
