name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇷_1"
    type: vless
    server: "alman.hellray-server.fun"
    port: 3010
    uuid: "3c4f4d61-ebcb-4594-aacf-ac0d620c8cde"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.aparat.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "F50bIiv7OTo8dY83HheaSJoY_Mn2jZn8mfrCIly8Wy4"
      short-id: "fa16a6435031"
    flow: "xtls-rprx-vision"
  - name: "🇮🇷_2"
    type: vless
    server: "185.143.234.238"
    port: 2086
    uuid: "1ee1f28d-4975-4d7c-95c7-76172c20eed5"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "parsi.parsi.sbs"
  - name: "🇮🇷_3"
    type: vless
    server: "new01.asaltabie.monster"
    port: 443
    uuid: "d0f4d620-db2b-45e0-8353-a073461b1130"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "new01.asaltabie.monster"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "new01.asaltabie.monster"
  - name: "🇮🇷_4"
    type: vless
    server: "185.143.233.238"
    port: 2086
    uuid: "1ee1f28d-4975-4d7c-95c7-76172c20eed5"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "parsi.parsi.sbs"
  - name: "🇮🇷_5"
    type: vless
    server: "irtonn.darklink.ir"
    port: 2035
    uuid: "0c779063-1e0a-41c2-94bf-9bd79b4026f5"
    udp: true
    network: ws
    ws-opts:
      path: "/java"
      headers:
        Host: "irtonn.darklink.ir"
  - name: "🇮🇷_6"
    type: vless
    server: "p01.parsi.sbs"
    port: 2086
    uuid: "1ee1f28d-4975-4d7c-95c7-76172c20eed5"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "parsi.parsi.sbs"
  - name: "🇮🇷_7"
    type: ss
    server: "79.175.134.49"
    port: 39880
    cipher: "aes-256-gcm"
    password: "PcOE52lyGO6MFRm6/m5hfuC3NpNockDvcnNYgq18Ni4="
    udp: true
  - name: "🇮🇷_8"
    type: ss
    server: "79.175.134.49"
    port: 39880
    cipher: "aes-256-gcm"
    password: "PcOE52lyGO6MFRm6/m5hfuC3NpNockDvcnNYgq18Ni4="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇷_1"
      - "🇮🇷_2"
      - "🇮🇷_3"
      - "🇮🇷_4"
      - "🇮🇷_5"
      - "🇮🇷_6"
      - "🇮🇷_7"
      - "🇮🇷_8"


rules:
  - MATCH,PROXY
