name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇮🇹_1"
    type: vless
    server: "ov-italy1.09vpn.com"
    port: 80
    uuid: "1e280316-0408-47c4-b058-05b8f1f17f02"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇮🇹_2"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "4c7480b2-d67b-4bb9-9f33-0700dfcbdee6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "jln31qtswdkut5.60kohcognywybguuq3ouc818oofnxfvn35daott.workers.dev"
  - name: "🇮🇹_3"
    type: vless
    server: "116.204.164.60"
    port: 7443
    uuid: "33509502-dd58-46bf-b574-985ca9a53964"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_4"
    type: vless
    server: "116.204.164.17"
    port: 7443
    uuid: "0baed386-770e-4e17-a6ca-24349e60903f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_5"
    type: vless
    server: "fn.cloud--vpn.site"
    port: 80
    uuid: "78eddd19-4fd4-461e-ad75-efd8cd44e0d0"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "playstationisp.com"
  - name: "🇮🇹_6"
    type: vless
    server: "204.216.216.23"
    port: 10086
    uuid: "9f0285ee-20ca-4953-bcdb-86a920652923"
    udp: true
  - name: "🇮🇹_7"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "dcd08975-739e-44c7-9022-7c7fcb87e74b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "8n9qi6t-owl.gevc9s4n60cc3wzcmwhjyezydpmbchocxp.workers.dev"
  - name: "🇮🇹_8"
    type: vless
    server: "204.216.216.23"
    port: 1114
    uuid: "6ba2eac6-0ec9-44ca-a42b-a8e23aafb530"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yahoo.com"
    reality-opts:
      public-key: "WfkCF0eEuIoO0MyJsKOddU89QrTzCZ4y2dzCJbH99CQ"
      short-id: "79a1e14b"
    flow: "xtls-rprx-vision"
  - name: "🇮🇹_9"
    type: vless
    server: "116.204.164.30"
    port: 7443
    uuid: "097e0483-50a9-4adf-8f62-031057710d11"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇮🇹_10"
    type: vless
    server: "116.204.164.27"
    port: 7443
    uuid: "7d4f5f0d-293f-4612-98d6-01fa0c1954b4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇮🇹_11"
    type: vless
    server: "116.204.164.5"
    port: 7443
    uuid: "2416ff70-cb17-4cdc-834d-a89c00261e01"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "o-85ley6knn8ut.6nvkygqh144t7xtdyvh0y3o4gzo3ujhnk8n.workers.dev"
  - name: "🇮🇹_12"
    type: vless
    server: "57.131.32.191"
    port: 80
    uuid: "1e280316-0408-47c4-b058-05b8f1f17f02"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
      headers:
        Host: "OV-Italy1.09vpn.com"
  - name: "🇮🇹_13"
    type: ss
    server: "62.76.234.75"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true
  - name: "🇮🇹_14"
    type: ss
    server: "185.213.20.110"
    port: 7001
    cipher: "aes-256-gcm"
    password: "RexnBgU7EV5ADxG"
    udp: true
  - name: "🇮🇹_15"
    type: ss
    server: "it2.levikogjgfdd.ir"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true
  - name: "🇮🇹_16"
    type: ss
    server: "62.76.234.75"
    port: 10901
    cipher: "aes-256-gcm"
    password: "d1fa2f4b98a38bc8"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇮🇹_1"
      - "🇮🇹_2"
      - "🇮🇹_3"
      - "🇮🇹_4"
      - "🇮🇹_5"
      - "🇮🇹_6"
      - "🇮🇹_7"
      - "🇮🇹_8"
      - "🇮🇹_9"
      - "🇮🇹_10"
      - "🇮🇹_11"
      - "🇮🇹_12"
      - "🇮🇹_13"
      - "🇮🇹_14"
      - "🇮🇹_15"
      - "🇮🇹_16"


rules:
  - MATCH,PROXY
