name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇯🇵_1"
    type: vless
    server: "137.220.221.179"
    port: 443
    uuid: "a16a3336-c9ab-489f-9b85-c973f5e2cfa4"
    udp: true
  - name: "🇯🇵_2"
    type: vless
    server: "103.75.118.228"
    port: 11452
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_3"
    type: vless
    server: "104.156.238.23"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/bt/image/categories?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_4"
    type: vless
    server: "85.121.50.16"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇯🇵_5"
    type: vless
    server: "80.96.156.58"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/tools/seller?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_6"
    type: vless
    server: "8.222.84.103"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/member/discount?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_7"
    type: vless
    server: "13.231.19.51"
    port: 11690
    uuid: "e2b8b217-cffb-4d66-9b8b-eca6e4334032"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Bv3z0_uFRabB9C4CFpNfqepZUyeO4YTh1duJdMBNLkg"
      short-id: "034885e346fd30"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_8"
    type: vless
    server: "3.114.220.22"
    port: 10583
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_9"
    type: vless
    server: "108.160.136.71"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/doc/products/view?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_10"
    type: vless
    server: "156.231.113.153"
    port: 443
    uuid: "3340c44a-042e-4dfd-b82c-33192d56ba98"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "h2GGazCHLBtmIUxiCxGUvsaEF8mGi8xFeCcI14sAJTI"
      short-id: "4bbe62498d4cc3c9"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_11"
    type: vless
    server: "103.31.77.108"
    port: 2053
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/channels/act"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_12"
    type: vless
    server: "64.176.60.226"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/documents"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_13"
    type: vless
    server: "103.75.118.228"
    port: 12683
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_14"
    type: vless
    server: "156.246.88.125"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_15"
    type: vless
    server: "206.251.53.91"
    port: 8443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/settings?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_16"
    type: vless
    server: "167.179.111.237"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/act/player/search?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_17"
    type: vless
    server: "45.142.166.211"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/knowledge?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_18"
    type: vless
    server: "207.148.99.230"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/test/company/library?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_19"
    type: vless
    server: "3.114.220.22"
    port: 18007
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_20"
    type: vless
    server: "138.2.59.96"
    port: 10129
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/movie/help/events?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_21"
    type: vless
    server: "210.152.85.154"
    port: 19364
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/collect/user/products?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_22"
    type: vless
    server: "152.69.195.67"
    port: 47878
    uuid: "eb8613e3-8393-4cff-a3ad-6501fd4adc63"
    udp: true
  - name: "🇯🇵_23"
    type: vless
    server: "3.114.220.22"
    port: 19645
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_24"
    type: vless
    server: "64.83.39.176"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/seller"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_25"
    type: vless
    server: "154.31.114.248"
    port: 50159
    uuid: "d56624b2-35bb-468c-9b2a-e0b0df7230c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "j4QXngGuJkUGwRj4XIrfHRohYYuEfnJlX4cvCE-WklA"
      short-id: "091e1c5db8451757"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_26"
    type: vless
    server: "103.115.18.54"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/episode/files?ed=2560"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_27"
    type: vless
    server: "104.238.148.149"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇯🇵_28"
    type: vless
    server: "8.222.70.238"
    port: 443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    network: ws
    ws-opts:
      path: "/mall/china/doc?ed=2560fp=chrome"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_29"
    type: vless
    server: "203.137.165.164"
    port: 57554
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇯🇵_30"
    type: vless
    server: "jp.wxgqlfx.top"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_31"
    type: vless
    server: "8.209.248.218"
    port: 443
    uuid: "caab26f1-c2e0-438d-8342-5d2125fb45df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "V94ws5oTIja_a6Hui3rSjomr7hZ-QCtYlsT7BWmxTzk"
      short-id: "973bd4f3d8d217fd"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_32"
    type: vless
    server: "8.211.152.47"
    port: 443
    uuid: "87646ddd-a8b0-4fea-a65c-ad86b0501c54"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.logitech.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "ycun6HN1qxz3fcfn15Bhut7loBGfohZ0wzTIkHKagyg"
      short-id: "89fdcf10a3cbd0b1"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_33"
    type: vless
    server: "8.209.217.129"
    port: 443
    uuid: "4a1bd3a7-22e6-4ed0-add4-7ee824d8f54a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.logitech.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "Ci03uVNJ34iSg-BSeOgrhTAeWcJExB5gQNuQVRY3a2Q"
      short-id: "01b4986b50245272"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_34"
    type: trojan
    server: "aa.ccmusic.jp"
    port: 443
    password: "tsuchiya"
    sni: "aa.ccmusic.jp"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_35"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_36"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_37"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_38"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_39"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_40"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_41"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_42"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_43"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_44"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_45"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_46"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_47"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_48"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇯🇵_1"
      - "🇯🇵_2"
      - "🇯🇵_3"
      - "🇯🇵_4"
      - "🇯🇵_5"
      - "🇯🇵_6"
      - "🇯🇵_7"
      - "🇯🇵_8"
      - "🇯🇵_9"
      - "🇯🇵_10"
      - "🇯🇵_11"
      - "🇯🇵_12"
      - "🇯🇵_13"
      - "🇯🇵_14"
      - "🇯🇵_15"
      - "🇯🇵_16"
      - "🇯🇵_17"
      - "🇯🇵_18"
      - "🇯🇵_19"
      - "🇯🇵_20"
      - "🇯🇵_21"
      - "🇯🇵_22"
      - "🇯🇵_23"
      - "🇯🇵_24"
      - "🇯🇵_25"
      - "🇯🇵_26"
      - "🇯🇵_27"
      - "🇯🇵_28"
      - "🇯🇵_29"
      - "🇯🇵_30"
      - "🇯🇵_31"
      - "🇯🇵_32"
      - "🇯🇵_33"
      - "🇯🇵_34"
      - "🇯🇵_35"
      - "🇯🇵_36"
      - "🇯🇵_37"
      - "🇯🇵_38"
      - "🇯🇵_39"
      - "🇯🇵_40"
      - "🇯🇵_41"
      - "🇯🇵_42"
      - "🇯🇵_43"
      - "🇯🇵_44"
      - "🇯🇵_45"
      - "🇯🇵_46"
      - "🇯🇵_47"
      - "🇯🇵_48"


rules:
  - MATCH,PROXY
