name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇯🇵_1"
    type: vless
    server: "134.122.202.244"
    port: 44915
    uuid: "0ca45842-71e2-47fe-889f-9e75f93ea459"
    udp: true
  - name: "🇯🇵_2"
    type: vless
    server: "92.113.124.204"
    port: 18443
    uuid: "89c1a02f-cef2-4d73-af87-21f894aa3cd5"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "🇯🇵_3"
    type: vless
    server: "156.246.88.125"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_4"
    type: vless
    server: "43.163.241.110"
    port: 24477
    uuid: "2bc72bec-0c2a-4c6b-aa9f-138bfce7ba0d"
    udp: true
  - name: "🇯🇵_5"
    type: vless
    server: "31.76.91.138"
    port: 2087
    uuid: "309b0ce3-09a8-4883-bfe4-bd56e215be44"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JfuItzJ81sJehx1PbxyliWSJvuBMKoa9ahNgPO3R7R4"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇯🇵_6"
    type: vless
    server: "203.137.165.164"
    port: 57554
    uuid: "a2336cca-3fd0-45cb-8ac5-1de6d17692b2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
  - name: "🇯🇵_7"
    type: vless
    server: "3.114.220.22"
    port: 18007
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_8"
    type: vless
    server: "156.231.113.153"
    port: 443
    uuid: "3340c44a-042e-4dfd-b82c-33192d56ba98"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "h2GGazCHLBtmIUxiCxGUvsaEF8mGi8xFeCcI14sAJTI"
      short-id: "4bbe62498d4cc3c9"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_9"
    type: vless
    server: "14.137.238.136"
    port: 10000
    uuid: "6f361c37-bc54-43dd-8c8b-0f59354745a5"
    udp: true
  - name: "🇯🇵_10"
    type: vless
    server: "3.114.220.22"
    port: 10583
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_11"
    type: vless
    server: "210.152.85.154"
    port: 19364
    uuid: "b282d286-e7a3-40ad-953a-aa9052adbcd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "🇯🇵_12"
    type: vless
    server: "154.19.187.249"
    port: 20725
    uuid: "6dcb725e-947e-4bbe-bb35-903374d57179"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "buylite.tv.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "hceZHd9X9FSbWGXGgm3OWN-4Au26rrsriTcyHw5M3VU"
      short-id: "0102ac4e"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_13"
    type: vless
    server: "151.241.129.98"
    port: 7219
    uuid: "5457a7c4-a892-4916-8802-c439cd70ddf0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "🇯🇵_14"
    type: vless
    server: "88.216.188.60"
    port: 443
    uuid: "c1d62d53-2fcd-4951-ab96-c81486f59775"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "w-mebel.pro"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "L7uycVxXYfpb7hNqiRlVlWYDhsevQNGs5eLi2idL6wc"
      short-id: "7e67f3f5a007bdc2"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_15"
    type: vless
    server: "31.76.91.72"
    port: 2087
    uuid: "524e00ce-ed89-481d-b4a4-6d7017f884e3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-ZTJcZ_UcqAB7LHgkUqhnlJsQs_oBafRgjsFtWZElmM"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇯🇵_16"
    type: vless
    server: "31.76.91.138"
    port: 445
    uuid: "309b0ce3-09a8-4883-bfe4-bd56e215be44"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JfuItzJ81sJehx1PbxyliWSJvuBMKoa9ahNgPO3R7R4"
      short-id: "c226283c4de5b1ad"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_17"
    type: vless
    server: "ja10.levikogjgfdd.ir"
    port: 2087
    uuid: "309b0ce3-09a8-4883-bfe4-bd56e215be44"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "JfuItzJ81sJehx1PbxyliWSJvuBMKoa9ahNgPO3R7R4"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇯🇵_18"
    type: vless
    server: "43.165.183.74"
    port: 2443
    uuid: "5c53add3-e092-4b29-b0c0-fb4f784115d1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
  - name: "🇯🇵_19"
    type: vless
    server: "162.141.131.102"
    port: 50159
    uuid: "063e01c2-4c0f-418e-9375-3cc1312f635b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "fLtEa_5BiN89xQDypfFMOu5o6DoUf6ch42jGdkXy6zE"
      short-id: "7f24526f7307c07a"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_20"
    type: vless
    server: "am9.levikogjgfdd.ir"
    port: 24477
    uuid: "2bc72bec-0c2a-4c6b-aa9f-138bfce7ba0d"
    udp: true
  - name: "🇯🇵_21"
    type: vless
    server: "3.114.220.22"
    port: 19645
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_22"
    type: vless
    server: "154.31.114.248"
    port: 50159
    uuid: "d56624b2-35bb-468c-9b2a-e0b0df7230c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "j4QXngGuJkUGwRj4XIrfHRohYYuEfnJlX4cvCE-WklA"
      short-id: "091e1c5db8451757"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_23"
    type: vless
    server: "137.220.221.179"
    port: 443
    uuid: "a16a3336-c9ab-489f-9b85-c973f5e2cfa4"
    udp: true
  - name: "🇯🇵_24"
    type: vless
    server: "96.126.130.176"
    port: 443
    uuid: "825c049b-403c-49e0-b60f-379bdb8611e9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.japan-travel.cn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "sPdtqEglJBpjsEgeOHkyafVgHSDcGzIn4ChX3gY4aVg"
      short-id: "280e30b0075dfda0"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_25"
    type: vless
    server: "152.69.195.67"
    port: 47878
    uuid: "eb8613e3-8393-4cff-a3ad-6501fd4adc63"
    udp: true
  - name: "🇯🇵_26"
    type: vless
    server: "92.113.124.204"
    port: 18443
    uuid: "643fb2dc-9659-43d4-8893-f721d76bc9ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
  - name: "🇯🇵_27"
    type: vless
    server: "rm-jp-01.409648.xyz"
    port: 20725
    uuid: "6dcb725e-947e-4bbe-bb35-903374d57179"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "buylite.tv.apple.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "hceZHd9X9FSbWGXGgm3OWN-4Au26rrsriTcyHw5M3VU"
      short-id: "0102ac4e"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_28"
    type: vless
    server: "13.193.205.133"
    port: 27407
    uuid: "cd5cf6e7-7ce5-42c9-9316-68210fa72a32"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bgcpartners.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "SajK6LzHBkkFlEXjIwseyqbpezgPiop5ZnSToou3G04"
      short-id: "e6ac18b63f23"
  - name: "🇯🇵_29"
    type: vless
    server: "103.75.118.228"
    port: 11452
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_30"
    type: vless
    server: "103.75.118.228"
    port: 12683
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_31"
    type: trojan
    server: "aa.ccmusic.jp"
    port: 443
    password: "tsuchiya"
    sni: "aa.ccmusic.jp"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_32"
    type: trojan
    server: "161.34.39.108"
    port: 443
    password: "tsuchiya"
    sni: "aa.ccmusic.jp"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_33"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_34"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_35"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_36"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_37"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_38"
    type: ss
    server: "ss.031.node-for-bigairport.win"
    port: 12885
    cipher: "aes-256-gcm"
    password: "3b970540-cdc4-43b4-ade2-3983c78afb48"
    udp: true
  - name: "🇯🇵_39"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_40"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_41"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_42"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_43"
    type: ss
    server: "176.97.73.215"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "ma6zc4JoLRJA"
    udp: true
  - name: "🇯🇵_44"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_45"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_46"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_47"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_48"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_49"
    type: ss
    server: "176.97.73.215"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "ma6zc4JoLRJA"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇯🇵_1"
      - "🇯🇵_2"
      - "🇯🇵_3"
      - "🇯🇵_4"
      - "🇯🇵_5"
      - "🇯🇵_6"
      - "🇯🇵_7"
      - "🇯🇵_8"
      - "🇯🇵_9"
      - "🇯🇵_10"
      - "🇯🇵_11"
      - "🇯🇵_12"
      - "🇯🇵_13"
      - "🇯🇵_14"
      - "🇯🇵_15"
      - "🇯🇵_16"
      - "🇯🇵_17"
      - "🇯🇵_18"
      - "🇯🇵_19"
      - "🇯🇵_20"
      - "🇯🇵_21"
      - "🇯🇵_22"
      - "🇯🇵_23"
      - "🇯🇵_24"
      - "🇯🇵_25"
      - "🇯🇵_26"
      - "🇯🇵_27"
      - "🇯🇵_28"
      - "🇯🇵_29"
      - "🇯🇵_30"
      - "🇯🇵_31"
      - "🇯🇵_32"
      - "🇯🇵_33"
      - "🇯🇵_34"
      - "🇯🇵_35"
      - "🇯🇵_36"
      - "🇯🇵_37"
      - "🇯🇵_38"
      - "🇯🇵_39"
      - "🇯🇵_40"
      - "🇯🇵_41"
      - "🇯🇵_42"
      - "🇯🇵_43"
      - "🇯🇵_44"
      - "🇯🇵_45"
      - "🇯🇵_46"
      - "🇯🇵_47"
      - "🇯🇵_48"
      - "🇯🇵_49"


rules:
  - MATCH,PROXY
