name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇯🇵_1"
    type: vless
    server: "3.114.220.22"
    port: 19645
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_2"
    type: vless
    server: "jp.wxgqlfx.top"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_3"
    type: vless
    server: "13.231.19.51"
    port: 11690
    uuid: "e2b8b217-cffb-4d66-9b8b-eca6e4334032"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Bv3z0_uFRabB9C4CFpNfqepZUyeO4YTh1duJdMBNLkg"
      short-id: "034885e346fd30"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_4"
    type: vless
    server: "154.31.114.248"
    port: 50159
    uuid: "d56624b2-35bb-468c-9b2a-e0b0df7230c1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "j4QXngGuJkUGwRj4XIrfHRohYYuEfnJlX4cvCE-WklA"
      short-id: "091e1c5db8451757"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_5"
    type: vless
    server: "206.251.54.34"
    port: 55596
    uuid: "9fc6444b-987a-41d5-9bf5-195d147e0a05"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "QQUHUyF5Wb3XeRRrky-WOaRTxBtHokNaMec02HURWSI"
      short-id: "6ac09686189038"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_6"
    type: vless
    server: "31.76.91.72"
    port: 2087
    uuid: "524e00ce-ed89-481d-b4a4-6d7017f884e3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-ZTJcZ_UcqAB7LHgkUqhnlJsQs_oBafRgjsFtWZElmM"
      short-id: "c226283c4de5b1ad"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇯🇵_7"
    type: vless
    server: "103.75.118.228"
    port: 11452
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_8"
    type: vless
    server: "156.231.113.153"
    port: 443
    uuid: "3340c44a-042e-4dfd-b82c-33192d56ba98"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "h2GGazCHLBtmIUxiCxGUvsaEF8mGi8xFeCcI14sAJTI"
      short-id: "4bbe62498d4cc3c9"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_9"
    type: vless
    server: "172.111.146.64"
    port: 80
    uuid: "904f8ffa-4652-4076-8f2f-e586807840ec"
    udp: true
    network: ws
    ws-opts:
      path: "/vless/"
  - name: "🇯🇵_10"
    type: vless
    server: "18.183.215.124"
    port: 28573
    uuid: "871bfce7-8440-4394-8d82-56b51f20fdad"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1DJr9toke7FRuSXjibBVuNvRnLnJnN5kXwUBG6Romzg"
      short-id: "03653bc03be10c97"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_11"
    type: vless
    server: "137.220.221.179"
    port: 443
    uuid: "a16a3336-c9ab-489f-9b85-c973f5e2cfa4"
    udp: true
  - name: "🇯🇵_12"
    type: vless
    server: "103.75.118.228"
    port: 12683
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_13"
    type: vless
    server: "47.79.32.249"
    port: 443
    uuid: "6030877e-32a0-4f16-b65e-92e076f9e3f9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "5-5-JEuwU97zcy-IJg32zruuHAOZ-85DM0YhRmzWbG4"
      short-id: "25d14b49bd77142e"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_14"
    type: vless
    server: "156.246.88.125"
    port: 26518
    uuid: "e01fcb68-3112-49da-b85d-dffb799cfc9b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "github.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1fa6iCY7vhoQyKu91FeaK04FN-mr1qeHnrtdyLZ79mk"
      short-id: "6caead99"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_15"
    type: vless
    server: "3.114.220.22"
    port: 10583
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_16"
    type: vless
    server: "13.231.7.104"
    port: 24620
    uuid: "b969ef8f-7bdb-474f-9481-d8f3c5686fb8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "eZthMfn0kQJFNr_srk502fr8yUHMoHQ7Oh3v4_HfTBI"
      short-id: "db2cb3b3c2dbb711"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_17"
    type: vless
    server: "3.114.220.22"
    port: 18007
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_18"
    type: vless
    server: "35.78.59.6"
    port: 47571
    uuid: "88a67610-b7ae-42ba-8af0-29cfa54cef37"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "OyfEDzOiDM5eMvTacJ4bVhF1V0QZgvz-vP3K456l3W4"
      short-id: "4c8b46e500b0f3ad"
    flow: "xtls-rprx-vision"
  - name: "🇯🇵_19"
    type: trojan
    server: "aa.ccmusic.jp"
    port: 443
    password: "tsuchiya"
    sni: "aa.ccmusic.jp"
    skip-cert-verify: true
    udp: true
  - name: "🇯🇵_20"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_21"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_22"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_23"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_24"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_25"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_26"
    type: ss
    server: "84.247.155.196"
    port: 80
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_27"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_28"
    type: ss
    server: "149.22.87.240"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_29"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_30"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_31"
    type: ss
    server: "149.22.87.204"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true
  - name: "🇯🇵_32"
    type: ss
    server: "45.32.16.53"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "uTBjZhDmOMwBVAJI"
    udp: true
  - name: "🇯🇵_33"
    type: ss
    server: "84.247.155.196"
    port: 443
    cipher: "aes-256-gcm"
    password: "3eOFeNssde7PYYMv"
    udp: true
  - name: "🇯🇵_34"
    type: ss
    server: "149.22.87.241"
    port: 443
    cipher: "aes-128-gcm"
    password: "shadowsocks"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇯🇵_1"
      - "🇯🇵_2"
      - "🇯🇵_3"
      - "🇯🇵_4"
      - "🇯🇵_5"
      - "🇯🇵_6"
      - "🇯🇵_7"
      - "🇯🇵_8"
      - "🇯🇵_9"
      - "🇯🇵_10"
      - "🇯🇵_11"
      - "🇯🇵_12"
      - "🇯🇵_13"
      - "🇯🇵_14"
      - "🇯🇵_15"
      - "🇯🇵_16"
      - "🇯🇵_17"
      - "🇯🇵_18"
      - "🇯🇵_19"
      - "🇯🇵_20"
      - "🇯🇵_21"
      - "🇯🇵_22"
      - "🇯🇵_23"
      - "🇯🇵_24"
      - "🇯🇵_25"
      - "🇯🇵_26"
      - "🇯🇵_27"
      - "🇯🇵_28"
      - "🇯🇵_29"
      - "🇯🇵_30"
      - "🇯🇵_31"
      - "🇯🇵_32"
      - "🇯🇵_33"
      - "🇯🇵_34"


rules:
  - MATCH,PROXY
