name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇰🇷_1"
    type: vless
    server: "31.77.183.88"
    port: 5001
    uuid: "1206bad5-dcc9-410e-9595-d9fe9ee54085"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "D-G2rTpSUTAF6Rj0C6Gxnk-uzsaGzM6MSbJX3jCyBBk"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_2"
    type: vless
    server: "3.39.4.109"
    port: 18967
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_3"
    type: vless
    server: "31.77.183.88"
    port: 5001
    uuid: "74f73fb2-49cc-4744-bd37-97c5f83963ab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "D-G2rTpSUTAF6Rj0C6Gxnk-uzsaGzM6MSbJX3jCyBBk"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_4"
    type: vless
    server: "151.245.106.49"
    port: 2053
    uuid: "9f7dddc4-6c77-4e2c-bfa4-7e5afdfd48f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Wg07hKwQjSVmOsEHn7X1iLAXR2wkKRSyv8TZmq9ZsRA"
      short-id: "58186df4a95a1504"
  - name: "🇰🇷_5"
    type: vless
    server: "119.28.161.143"
    port: 443
    uuid: "1ebb0858-218a-4dee-8746-36a67bc64462"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "pR7MPTAA4cZsW9AO-twMzuogiWGMKPiheTg70fcWWWs"
      short-id: "0a427bc3"
  - name: "🇰🇷_6"
    type: vless
    server: "kr2.miyazono-kaori.com"
    port: 443
    uuid: "09558890-0fa4-4d55-96b5-f9a5675c2625"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.coway.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "6pZxjabeHoyJlsc2cP3Q5YK7G0bIOQwzWFyiarbUQXc"
      short-id: "c8af1462debbc1"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_7"
    type: vless
    server: "3.39.4.109"
    port: 13672
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_8"
    type: vless
    server: "3.38.1.152"
    port: 19179
    uuid: "10dd7b2d-eda2-4a47-9f6e-5093a3cd7ded"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "BabvzCKB_cqCz56qFQhOWIypFKFhEWo9Eyn_JPZIAxA"
      short-id: "fa1e592603c283"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_9"
    type: vless
    server: "130.94.29.111"
    port: 2087
    uuid: "84da6391-1539-4583-a3d9-d6efd796b4d6"
    udp: true
    network: ws
    ws-opts:
      path: "/e17586a75123"
  - name: "🇰🇷_10"
    type: vless
    server: "31.77.183.88"
    port: 5000
    uuid: "74f73fb2-49cc-4744-bd37-97c5f83963ab"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cpoZcpYNYSvFXGGB21tByHUoNd7-FYrJ0UP7ZDfSFCs"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_11"
    type: vless
    server: "31.77.183.88"
    port: 5000
    uuid: "1206bad5-dcc9-410e-9595-d9fe9ee54085"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "cpoZcpYNYSvFXGGB21tByHUoNd7-FYrJ0UP7ZDfSFCs"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_12"
    type: vless
    server: "43.202.46.25"
    port: 28482
    uuid: "83973343-90db-423d-a5f7-2e3b56aeb8f4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "8fsYG_Pg35aeg1E5Gc3HUaXou2OUQee4ukxVk99iR0s"
      short-id: "fa1e592603c283"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_13"
    type: vless
    server: "kr1.miyazono-kaori.com"
    port: 443
    uuid: "09558890-0fa4-4d55-96b5-f9a5675c2625"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.coway.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "aVGSSemhxqqDg75lUDBxCNZZXfuBb4QrU8yZYnJD6nk"
      short-id: "f554f56d31"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_14"
    type: vless
    server: "221.155.195.197"
    port: 10000
    uuid: "83efc3a0-05c6-462b-89f7-07c430f73c03"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "kdlgIBl7R_1DIWtJIrOqYwt65nedPCbz6XoomdpQIXM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_15"
    type: vless
    server: "54.180.87.212"
    port: 8686
    uuid: "1a17b19d-4896-4531-af79-6e91d8ef8228"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    reality-opts:
      public-key: "A3NXnUIT-W0m1Y_leRnv5so2IeCvk9FCFgL31PulfTw"
      short-id: "628b3c90c98ead4f"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇰🇷_1"
      - "🇰🇷_2"
      - "🇰🇷_3"
      - "🇰🇷_4"
      - "🇰🇷_5"
      - "🇰🇷_6"
      - "🇰🇷_7"
      - "🇰🇷_8"
      - "🇰🇷_9"
      - "🇰🇷_10"
      - "🇰🇷_11"
      - "🇰🇷_12"
      - "🇰🇷_13"
      - "🇰🇷_14"
      - "🇰🇷_15"


rules:
  - MATCH,PROXY
