name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇰🇷_1"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "e06e0fb9-6328-4084-bfa4-2b61dc9f3068"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "sxyyvihkektlx4rjxsdj.pkc73phpweu4rbxbatm444.workers.dev"
  - name: "🇰🇷_2"
    type: vless
    server: "3.39.4.109"
    port: 18967
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_3"
    type: vless
    server: "220.72.143.166"
    port: 12016
    uuid: "0735b6f3-fdaa-4413-9c98-9af58e8a9052"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "2-gys60wmzb6bqzd.qpsjn114hh3vlph9z60sesz0agjawpwroneg.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "2-gys60wmzb6bqzd.qpsjn114hh3vlph9z60sesz0agjawpwroneg.workers.dev"
  - name: "🇰🇷_4"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "7185500c-8b9a-49d2-8cbb-765542a49a52"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "woc0zvrf11w2endu.dphdlc1u77bs3y4kvussbuap4p576f1ws7igthq8zbf3.workers.dev"
  - name: "🇰🇷_5"
    type: vless
    server: "132.145.89.30"
    port: 443
    uuid: "e6d8d743-a9bc-48c9-be99-8f3cc94d16e1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ako.pagate.top"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_6"
    type: vless
    server: "3.37.55.114"
    port: 8686
    uuid: "f0b9ae63-91a7-4673-924e-498e0e0828c0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    reality-opts:
      public-key: "A3NXnUIT-W0m1Y_leRnv5so2IeCvk9FCFgL31PulfTw"
      short-id: "628b3c90c98ead4f"
  - name: "🇰🇷_7"
    type: vless
    server: "54.180.118.19"
    port: 8686
    uuid: "1a17b19d-4896-4531-af79-6e91d8ef8228"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    reality-opts:
      public-key: "A3NXnUIT-W0m1Y_leRnv5so2IeCvk9FCFgL31PulfTw"
      short-id: "628b3c90c98ead4f"
  - name: "🇰🇷_8"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "ae6f014e-c539-4278-8f21-66c7ad2bbb47"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇰🇷_9"
    type: vless
    server: "220.72.143.166"
    port: 12016
    uuid: "9487e433-862e-4b53-893a-5a4f6bc911f0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇰🇷_10"
    type: vless
    server: "183.107.137.157"
    port: 36389
    uuid: "8d4cffc5-5b52-4cef-8059-2095c100a8a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wkytah9k8oggj60.qzfi0skkopy875xhtc0l9pwds.workers.dev"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "wkytah9k8oggj60.qzfi0skkopy875xhtc0l9pwds.workers.dev"
  - name: "🇰🇷_11"
    type: vless
    server: "3.39.4.109"
    port: 13672
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇰🇷_12"
    type: trojan
    server: "43.203.247.197"
    port: 443
    password: "ND91608427"
    sni: "definite-malamute.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_13"
    type: trojan
    server: "chief-bluegill.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "chief-bluegill.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_14"
    type: trojan
    server: "exotic-chow.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "exotic-chow.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_15"
    type: trojan
    server: "uncommon-feline.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "uncommon-feline.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_16"
    type: trojan
    server: "13.125.239.182"
    port: 443
    password: "ND91608427"
    sni: "saving-octopus.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_17"
    type: trojan
    server: "grateful-owl.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "grateful-owl.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_18"
    type: trojan
    server: "54.180.228.238"
    port: 443
    password: "ND91608427"
    sni: "pure-ram.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_19"
    type: trojan
    server: "moved-meerkat.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "moved-meerkat.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_20"
    type: trojan
    server: "43.203.244.203"
    port: 443
    password: "ND91608427"
    sni: "grateful-owl.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_21"
    type: trojan
    server: "43.203.203.244"
    port: 443
    password: "ND91608427"
    sni: "main-whippet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_22"
    type: trojan
    server: "3.38.106.2"
    port: 443
    password: "ND91608427"
    sni: "communal-sunbird.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_23"
    type: trojan
    server: "humorous-malamute.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "humorous-malamute.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_24"
    type: trojan
    server: "communal-sunbird.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "communal-sunbird.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_25"
    type: trojan
    server: "3.36.59.34"
    port: 443
    password: "ND91608427"
    sni: "select-ferret.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_26"
    type: trojan
    server: "distinct-llama.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "distinct-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_27"
    type: trojan
    server: "upward-puma.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "upward-puma.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_28"
    type: trojan
    server: "52.79.210.229"
    port: 443
    password: "ND91608427"
    sni: "chief-bluegill.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_29"
    type: trojan
    server: "43.202.56.122"
    port: 443
    password: "ND91608427"
    sni: "striking-maggot.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_30"
    type: trojan
    server: "3.36.131.218"
    port: 443
    password: "ND91608427"
    sni: "humorous-malamute.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_31"
    type: trojan
    server: "main-whippet.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "main-whippet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_32"
    type: trojan
    server: "select-ferret.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "select-ferret.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_33"
    type: trojan
    server: "52.78.13.238"
    port: 443
    password: "ND91608427"
    sni: "upward-puma.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_34"
    type: trojan
    server: "striking-maggot.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "striking-maggot.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_35"
    type: trojan
    server: "saving-octopus.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "saving-octopus.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_36"
    type: trojan
    server: "definite-malamute.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "definite-malamute.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_37"
    type: trojan
    server: "43.201.103.8"
    port: 443
    password: "ND91608427"
    sni: "intimate-moray.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_38"
    type: trojan
    server: "intimate-moray.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "intimate-moray.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_39"
    type: trojan
    server: "3.35.140.99"
    port: 443
    password: "ND91608427"
    sni: "moved-meerkat.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_40"
    type: trojan
    server: "43.203.119.20"
    port: 443
    password: "ND91608427"
    sni: "uncommon-feline.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_41"
    type: trojan
    server: "43.201.56.44"
    port: 443
    password: "ND91608427"
    sni: "distinct-llama.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_42"
    type: trojan
    server: "pure-ram.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "pure-ram.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇰🇷_43"
    type: trojan
    server: "43.201.46.108"
    port: 443
    password: "ND91608427"
    sni: "exotic-chow.rooster465.autos"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇰🇷_1"
      - "🇰🇷_2"
      - "🇰🇷_3"
      - "🇰🇷_4"
      - "🇰🇷_5"
      - "🇰🇷_6"
      - "🇰🇷_7"
      - "🇰🇷_8"
      - "🇰🇷_9"
      - "🇰🇷_10"
      - "🇰🇷_11"
      - "🇰🇷_12"
      - "🇰🇷_13"
      - "🇰🇷_14"
      - "🇰🇷_15"
      - "🇰🇷_16"
      - "🇰🇷_17"
      - "🇰🇷_18"
      - "🇰🇷_19"
      - "🇰🇷_20"
      - "🇰🇷_21"
      - "🇰🇷_22"
      - "🇰🇷_23"
      - "🇰🇷_24"
      - "🇰🇷_25"
      - "🇰🇷_26"
      - "🇰🇷_27"
      - "🇰🇷_28"
      - "🇰🇷_29"
      - "🇰🇷_30"
      - "🇰🇷_31"
      - "🇰🇷_32"
      - "🇰🇷_33"
      - "🇰🇷_34"
      - "🇰🇷_35"
      - "🇰🇷_36"
      - "🇰🇷_37"
      - "🇰🇷_38"
      - "🇰🇷_39"
      - "🇰🇷_40"
      - "🇰🇷_41"
      - "🇰🇷_42"
      - "🇰🇷_43"


rules:
  - MATCH,PROXY
