name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇱🇹_1"
    type: vless
    server: "144.31.243.240"
    port: 443
    uuid: "f692629b-3557-488a-9c9b-60775331e423"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi1-cosmostechnology.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f3Mwf_vaM2TDw1X8HZORkYPLY0-DE5smNYgHuhrQLTA"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "fi1cosmos"
  - name: "🇱🇹_2"
    type: vless
    server: "84.32.110.58"
    port: 2443
    uuid: "cfae13ae-5f59-42dc-a6cd-a2736dd9dca9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lao10.enterquality.online"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_3"
    type: vless
    server: "88.216.69.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime06.workers.dev"
  - name: "🇱🇹_4"
    type: vless
    server: "46.166.167.222"
    port: 443
    uuid: "cd1673b3-7cec-4fe6-bedf-b534eb54e647"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ddc-chr-lt2.astralweb.tech"
    client-fingerprint: "firefox"
  - name: "🇱🇹_5"
    type: vless
    server: "ddc-chr-lt2.astralweb.tech"
    port: 443
    uuid: "cd1673b3-7cec-4fe6-bedf-b534eb54e647"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ddc-chr-lt2.astralweb.tech"
    client-fingerprint: "firefox"
  - name: "🇱🇹_6"
    type: vless
    server: "89.116.250.8"
    port: 443
    uuid: "47fcef29-ab4e-4aa6-932b-d95a18f28a4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gj2rf.mlrb.tyr.hh.vavava.kdns.fr"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "gj2rf.mlrb.tyr.hh.vavava.kdns.fr"
  - name: "🇱🇹_7"
    type: vless
    server: "46.29.234.210"
    port: 443
    uuid: "218fd696-e3a2-4c33-b397-a5f13a82969e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tradingview.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "II9Tn-HPL7xcENiybDfQ_bSw31rSzQbIGYn-hCxdb2w"
      short-id: "ccda00cc"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇱🇹_8"
    type: vless
    server: "144.31.243.37"
    port: 443
    uuid: "f692629b-3557-488a-9c9b-60775331e423"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi1-cosmostechnology.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f3Mwf_vaM2TDw1X8HZORkYPLY0-DE5smNYgHuhrQLTA"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "fi1cosmos"
  - name: "🇱🇹_9"
    type: vless
    server: "144.31.243.119"
    port: 443
    uuid: "f692629b-3557-488a-9c9b-60775331e423"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi1-cosmostechnology.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f3Mwf_vaM2TDw1X8HZORkYPLY0-DE5smNYgHuhrQLTA"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "fi1cosmos"
  - name: "🇱🇹_10"
    type: vless
    server: "84.32.209.7"
    port: 443
    uuid: "f1c496bf-d2ab-45be-bc13-051d60d227b7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dartsearch-cn.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "00n9LplaZ0VGvRS57548s7xe0deFC10pw2fkFHFPplM"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇱🇹_11"
    type: vless
    server: "144.31.243.105"
    port: 443
    uuid: "f692629b-3557-488a-9c9b-60775331e423"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fi1-cosmostechnology.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "f3Mwf_vaM2TDw1X8HZORkYPLY0-DE5smNYgHuhrQLTA"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "fi1cosmos"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇱🇹_1"
      - "🇱🇹_2"
      - "🇱🇹_3"
      - "🇱🇹_4"
      - "🇱🇹_5"
      - "🇱🇹_6"
      - "🇱🇹_7"
      - "🇱🇹_8"
      - "🇱🇹_9"
      - "🇱🇹_10"
      - "🇱🇹_11"


rules:
  - MATCH,PROXY
