name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇲🇩_1"
    type: vless
    server: "85.121.5.242"
    port: 443
    uuid: "e59382e1-eee1-45e8-a360-a595a5f045ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eeulnknm.scroogethebest.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "Ij47UmBW1LAB4pANpAG9_m8j3wNzqcCE61cbgN-EHD8"
      short-id: "05efc9ea5e2be49b"
    flow: "xtls-rprx-vision"
  - name: "🇲🇩_2"
    type: vless
    server: "80.96.108.232"
    port: 443
    uuid: "e59382e1-eee1-45e8-a360-a595a5f045ba"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kbqvgn4a.scroogethebest.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "49UUO42yZ_vlQETT_wsvBeVcsKD4aECKiu5hjUjGVkk"
      short-id: "9c2378562188c3cb"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇲🇩_1"
      - "🇲🇩_2"


rules:
  - MATCH,PROXY
