name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇵🇱_1"
    type: vless
    server: "81.90.17.164"
    port: 443
    uuid: "cb784d00-d34a-4389-b938-8717f7b28353"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yastatic.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "v0XQn6uvyC8q5CThcRYLer1F1OOYpZDn5NLOvDicaWg"
      short-id: "b31c2b75add2e5fa"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_2"
    type: vless
    server: "78.17.159.71"
    port: 8443
    uuid: "14927bde-0fc8-447c-8c5f-e7fd1bfc6698"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "wjwbbmCr0pjMb6Qvvcf7KMrE-w92jsqJbrNQy8g5EDg"
      short-id: "617a11ec485b2d90"
    network: grpc
    grpc-opts:
      grpc-service-name: "tab.cf.v1"
  - name: "🇵🇱_3"
    type: vless
    server: "meow-warsaw.nethcloud.top"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_4"
    type: vless
    server: "201.3.225.13"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uwu.spectrumproxy.shop"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "EyzTSZxq5qlUT2xW0l7VP-DzIh2ucabMan9ekEv9Owo"
      short-id: "143627f1"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_5"
    type: vless
    server: "2.59.163.45"
    port: 59992
    uuid: "9a9fe945-246a-431e-bd05-1cb981464c8d"
    udp: true
  - name: "🇵🇱_6"
    type: vless
    server: "82.40.62.154"
    port: 443
    uuid: "a1022d47-2417-4489-b7e0-b0febcc7a8ad"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "plconverter.medusafree.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "zoltLkUwzDlwlUK4Z4QBzgoXECPU7z9NAw5Gm4mgoRg"
      short-id: "7da2799ba267b2"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_7"
    type: vless
    server: "uwu.spectrumproxy.shop"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uwu.spectrumproxy.shop"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "EyzTSZxq5qlUT2xW0l7VP-DzIh2ucabMan9ekEv9Owo"
      short-id: "143627f1"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_8"
    type: vless
    server: "alenka.xanka.best"
    port: 8443
    uuid: "dfdc967a-c1fa-4920-a91a-375cd6a99853"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "alenka.xanka.best"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aOjzy8s0C2zfU4F1OPmQJj7ScEZWUSoeekG7Fs0I-Wg"
      short-id: "a3dbb8f6"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_9"
    type: vless
    server: "95.85.227.142"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_10"
    type: vless
    server: "83.168.108.200"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pol3.freeinternat.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_11"
    type: vless
    server: "18.244.146.24"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_12"
    type: vless
    server: "168.222.49.197"
    port: 15744
    uuid: "c26a059d-e324-4c93-912f-443ddec99643"
    udp: true
  - name: "🇵🇱_13"
    type: vless
    server: "83.168.71.216"
    port: 443
    uuid: "a18f7c2d-9e45-4b8a-af3c-1d5e7f9c8b2a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho"
      short-id: "2f49bccf11150ef2"
  - name: "🇵🇱_14"
    type: vless
    server: "18.244.146.80"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_15"
    type: vless
    server: "217.12.207.24"
    port: 443
    uuid: "8970d7c5-55b5-491d-8a3c-5635b81d2f3c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pol-s1.mustgate.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "-UvUcf7EzjiCgbF99XtLh4-gfw0hvw-iNC-7Vaaqsko"
      short-id: "75f8575e5396a2fe"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_16"
    type: vless
    server: "18.244.146.6"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_17"
    type: vless
    server: "support.zoom.us.beichuan.serv00.net"
    port: 9815
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "support.zoom.us.beichuan.serv00.net"
  - name: "🇵🇱_18"
    type: vless
    server: "128.204.223.94"
    port: 9815
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_19"
    type: vless
    server: "18.244.146.94"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_20"
    type: trojan
    server: "relaxed-gull.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_21"
    type: trojan
    server: "202.78.163.248"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_22"
    type: trojan
    server: "202.78.163.148"
    port: 443
    password: "ND91608427"
    sni: "discrete-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_23"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇵🇱_24"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇵🇱_1"
      - "🇵🇱_2"
      - "🇵🇱_3"
      - "🇵🇱_4"
      - "🇵🇱_5"
      - "🇵🇱_6"
      - "🇵🇱_7"
      - "🇵🇱_8"
      - "🇵🇱_9"
      - "🇵🇱_10"
      - "🇵🇱_11"
      - "🇵🇱_12"
      - "🇵🇱_13"
      - "🇵🇱_14"
      - "🇵🇱_15"
      - "🇵🇱_16"
      - "🇵🇱_17"
      - "🇵🇱_18"
      - "🇵🇱_19"
      - "🇵🇱_20"
      - "🇵🇱_21"
      - "🇵🇱_22"
      - "🇵🇱_23"
      - "🇵🇱_24"


rules:
  - MATCH,PROXY
