name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇵🇱_1"
    type: vless
    server: "144.31.3.53"
    port: 443
    uuid: "645710cd-317d-420b-bb07-db6620cc65d0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "proud-dynamo.cdn.cachefleet.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "KOgPteoWEwtVtykS2FGV5NHdZw6197VzbITPGkUJDBQ"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_2"
    type: vless
    server: "82.26.91.87"
    port: 443
    uuid: "7e760d89-a8f4-4a87-8f10-b4af28c61b7f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "faster.yandex-apicloud.ru"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_3"
    type: vless
    server: "18.244.146.24"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_4"
    type: vless
    server: "144.31.112.199"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl2.fast-connect-service.site"
    client-fingerprint: "qq"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_5"
    type: vless
    server: "95.85.253.5"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl4.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_6"
    type: vless
    server: "31.77.56.229"
    port: 443
    uuid: "f61025f4-7973-4e3e-883c-a0fe85f0489c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl.rexten.cc"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "OFmJtVi6OB9E6KIc5QV5YmoouimRFc-Se9hICjtV8hQ"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_7"
    type: vless
    server: "31.56.188.152"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl11.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_8"
    type: vless
    server: "18.244.146.6"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_9"
    type: vless
    server: "83.168.71.216"
    port: 443
    uuid: "a18f7c2d-9e45-4b8a-af3c-1d5e7f9c8b2a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ads.x5.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8h8t5eBWL9oERK7xWHQLFJE5j6sZdgNDQAs3EGnNbho"
      short-id: "2f49bccf11150ef2"
  - name: "🇵🇱_10"
    type: vless
    server: "31.77.56.235"
    port: 443
    uuid: "f61025f4-7973-4e3e-883c-a0fe85f0489c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl.rexten.cc"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "OFmJtVi6OB9E6KIc5QV5YmoouimRFc-Se9hICjtV8hQ"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_11"
    type: vless
    server: "18.244.146.80"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_12"
    type: vless
    server: "201.3.225.13"
    port: 443
    uuid: "76713d07-5a6b-49c2-abd8-bc450a2fa7fc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "uwu.spectrumproxy.shop"
    reality-opts:
      public-key: "EyzTSZxq5qlUT2xW0l7VP-DzIh2ucabMan9ekEv9Owo"
      short-id: "143627f1"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_13"
    type: vless
    server: "beichuan.serv00.net"
    port: 9815
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "beichuan.serv00.net"
  - name: "🇵🇱_14"
    type: vless
    server: "95.85.253.134"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl5.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_15"
    type: vless
    server: "141.101.120.129"
    port: 80
    uuid: "3087ca05-1a7c-45fa-aec9-805adeaedb1b"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "tianshu.kevqwkt451.workers.dev"
  - name: "🇵🇱_16"
    type: vless
    server: "144.31.171.233"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl6.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_17"
    type: vless
    server: "2.59.163.45"
    port: 59992
    uuid: "9a9fe945-246a-431e-bd05-1cb981464c8d"
    udp: true
  - name: "🇵🇱_18"
    type: vless
    server: "95.85.227.142"
    port: 443
    uuid: "a34b5e88-cf0d-4c01-8199-2d1002d3c787"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.wikihow.com"
    reality-opts:
      public-key: "HKpd1sbrhBds8SJSL0d22MAq_QyTR6EP6y5b5DYol3U"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_19"
    type: vless
    server: "34.116.216.59"
    port: 443
    uuid: "1078d418-b4e0-4668-9018-dc90c2042d61"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "workspace.evan00.dpdns.org"
    client-fingerprint: "randomized"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "workspace.evan00.dpdns.org"
  - name: "🇵🇱_20"
    type: vless
    server: "154.84.164.10"
    port: 443
    uuid: "d2042070-c247-4226-a3ac-15337923e00d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "storage.yandex.net"
    reality-opts:
      public-key: "pPi-WO8qQFFZ9UJWNLW9YClbjcoAAZWJQ2_FM3Kjhz8"
      short-id: "da147b40372a5fed"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_21"
    type: vless
    server: "83.168.108.200"
    port: 443
    uuid: "fbb74aa8-b89a-4f20-9504-6b25aadf6681"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pol3.freeinternat.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bZpzmeWiEJyJQy0W2hHc34Nr6BuFXj1UDd80Cbwh1Fk"
      short-id: "ff776ff77be48b88"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_22"
    type: vless
    server: "185.16.36.200"
    port: 43439
    uuid: "03446511-2806-4fc0-b02f-f10d2d3a33c6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn-up.perecbass.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "b4n1pcO8ST3JkGtj8YymXVrW17LEe2EHec5wY7hMMR4"
      short-id: "ae99c61853e8a6ae"
    network: grpc
    grpc-opts:
      grpc-service-name: "ws"
  - name: "🇵🇱_23"
    type: vless
    server: "18.244.146.94"
    port: 443
    uuid: "7ce54bb3-d612-4aa7-be08-089d3c461d53"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "d1yxsk0zprgivr.cloudfront.net"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇵🇱_24"
    type: vless
    server: "2.26.255.36"
    port: 8443
    uuid: "8787dd0a-095a-414e-804f-a7d16a1ae166"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po1.hys.braidx.tech"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_25"
    type: vless
    server: "103.68.110.42"
    port: 443
    uuid: "8033102198"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl1.fast-connect-service.site"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_26"
    type: vless
    server: "141.101.120.73"
    port: 443
    uuid: "5d8eb33a-2166-4daf-88fe-4be5799c493b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "noisy-term-e657.airdrop2014aa5168.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "noisy-term-e657.airdrop2014aa5168.workers.dev"
  - name: "🇵🇱_27"
    type: vless
    server: "150.251.113.34"
    port: 443
    uuid: "d7d724b5-17ce-4f3c-877d-dfbf0f07afa1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "8yMLSTbkpJFfbgTjNzotzz7U8OT6AERrclgKdKrXXW8"
      short-id: "150a627d15154cf2"
    flow: "xtls-rprx-vision"
  - name: "🇵🇱_28"
    type: vless
    server: "31.76.251.127.cdn-one.org"
    port: 443
    uuid: "4f375fb4-3c95-425f-bc7b-8085487a6f3c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "31.76.251.127.cdn-one.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/10336/2GCOqG7bvA"
      headers:
        Host: "31.76.251.127.cdn-one.org"
  - name: "🇵🇱_29"
    type: vless
    server: "128.204.223.94"
    port: 9815
    uuid: "37a0bd7c-8b9f-4693-8916-bd1e2da0a817"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "v2rayNplus--v2rayNplus--v2rayNplus"
  - name: "🇵🇱_30"
    type: trojan
    server: "202.78.163.248"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_31"
    type: trojan
    server: "relaxed-gull.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "relaxed-gull.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_32"
    type: trojan
    server: "202.78.163.148"
    port: 443
    password: "ND91608427"
    sni: "discrete-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_33"
    type: trojan
    server: "discrete-basilisk.rooster465.autos"
    port: 443
    password: "ND91608427"
    sni: "discrete-basilisk.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇵🇱_34"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇵🇱_35"
    type: ss
    server: "92.118.205.211"
    port: 5600
    cipher: "aes-256-gcm"
    password: "Y6R9pAtvxxzmGC"
    udp: true
  - name: "🇵🇱_36"
    type: ss
    server: "64.176.73.160"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "VJtsgllDDJfNmaTe"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇵🇱_1"
      - "🇵🇱_2"
      - "🇵🇱_3"
      - "🇵🇱_4"
      - "🇵🇱_5"
      - "🇵🇱_6"
      - "🇵🇱_7"
      - "🇵🇱_8"
      - "🇵🇱_9"
      - "🇵🇱_10"
      - "🇵🇱_11"
      - "🇵🇱_12"
      - "🇵🇱_13"
      - "🇵🇱_14"
      - "🇵🇱_15"
      - "🇵🇱_16"
      - "🇵🇱_17"
      - "🇵🇱_18"
      - "🇵🇱_19"
      - "🇵🇱_20"
      - "🇵🇱_21"
      - "🇵🇱_22"
      - "🇵🇱_23"
      - "🇵🇱_24"
      - "🇵🇱_25"
      - "🇵🇱_26"
      - "🇵🇱_27"
      - "🇵🇱_28"
      - "🇵🇱_29"
      - "🇵🇱_30"
      - "🇵🇱_31"
      - "🇵🇱_32"
      - "🇵🇱_33"
      - "🇵🇱_34"
      - "🇵🇱_35"
      - "🇵🇱_36"


rules:
  - MATCH,PROXY
