name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "bz2.wba-pn.ru"
    port: 2053
    uuid: "f62a1751-c1e4-4612-90e7-bd5781c1aede"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.com"
    client-fingerprint: "android"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇷🇺_2"
    type: vless
    server: "185.185.69.26"
    port: 2200
    uuid: "7ee53e03-96ed-4121-9da2-62f3d3374506"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_3"
    type: vless
    server: "178.72.147.249"
    port: 4100
    uuid: "6bd3e20b-4be0-41df-a1e0-5c147cc8fbfc"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_4"
    type: vless
    server: "91.210.169.181"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "91.210.169.181"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_5"
    type: vless
    server: "178.72.147.249"
    port: 2200
    uuid: "47f2ac7a-7bc6-4d4c-b4f2-c4681da7f231"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_6"
    type: vless
    server: "201.34.137.15"
    port: 4100
    uuid: "716903b1-e6bf-4420-9e27-65e4451692e9"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_7"
    type: vless
    server: "62.113.106.165"
    port: 5012
    uuid: "1206bad5-dcc9-410e-9595-d9fe9ee54085"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pl.aeternavpn.space"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "S-hF71pRzH9xT1zd3spq6RGlXCrpzyWpTmVKHbdTERg"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_8"
    type: vless
    server: "85.198.70.200"
    port: 14406
    uuid: "237f91bf-102e-4077-8cc3-baebccb42936"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "ldAmsl3dqTCUBmlmA8CS9ZnpznP6cFWj9AxNddWnbxY"
      short-id: "1a2b3c4d5e6f7a8b"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_9"
    type: vless
    server: "95.163.232.242"
    port: 17443
    uuid: "1206bad5-dcc9-410e-9595-d9fe9ee54085"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ee.aeternavpn.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "1qc8V4QTRV4uwEdy2OpDVJc6dP8g9uHIccHtx_ChWTk"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_10"
    type: vless
    server: "188.225.47.234"
    port: 4100
    uuid: "7b2ce6b0-6d2b-4926-b7bf-6247eb1a0050"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇷🇺_11"
    type: vless
    server: "91.222.237.55"
    port: 2200
    uuid: "714e1212-6707-471e-9f40-2fbd3d8d3b4b"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_12"
    type: vless
    server: "159.194.234.196"
    port: 16445
    uuid: "1206bad5-dcc9-410e-9595-d9fe9ee54085"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fr.aeternavpn.space"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "BfWH0Semc11YkTslIO_Igss921A5J3JMmq_i2FaZxDo"
      short-id: "a1b2c3d4"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_13"
    type: vless
    server: "201.24.124.99"
    port: 4100
    uuid: "d46b4fca-2352-4557-a6d5-e8c45b27618c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_14"
    type: vless
    server: "185.178.208.140"
    port: 443
    uuid: "3e6f97d4-c8a4-473c-b7b2-aaa0756b009a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mapgasstation.ru"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/api/v3/live/hls/segment"
  - name: "🇷🇺_15"
    type: vless
    server: "45.9.15.77"
    port: 443
    uuid: "87f56eb8-8e02-4d51-b8d8-9476d5c46e41"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "kYmAepOhG51VCI1ABUsCyBv1H_AOkOg2u6JH5AC3nl4"
      short-id: "9b00f431750d671c"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_16"
    type: vless
    server: "ru9.aimodelhub.top"
    port: 443
    uuid: "ba895ce4-8c24-0003-9f22-81ee227c89d0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru9.aimodelhub.top"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "jwT3lcIzJQMjzBKRNsmyRGrgaa1qNfE7pQF_nAKu0GA"
      short-id: "a73cf719b624"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_17"
    type: vless
    server: "194.26.229.157"
    port: 2200
    uuid: "c05888f0-4029-45c8-bea7-ea5eff564462"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇷🇺_18"
    type: vless
    server: "178.72.147.246"
    port: 4100
    uuid: "d4b80eae-4e0d-4211-bec2-2dc03afb3637"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_19"
    type: vless
    server: "45.12.5.171"
    port: 443
    uuid: "ba895ce4-8c24-0003-9f22-81ee227c89d0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru9.aimodelhub.top"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "jwT3lcIzJQMjzBKRNsmyRGrgaa1qNfE7pQF_nAKu0GA"
      short-id: "a73cf719b624"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_20"
    type: vless
    server: "178.72.147.249"
    port: 4100
    uuid: "7ee53e03-96ed-4121-9da2-62f3d3374506"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇷🇺_21"
    type: vless
    server: "77.222.53.218"
    port: 2200
    uuid: "1cb011db-0211-4120-8984-13d8510a612b"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_22"
    type: vless
    server: "186.246.12.85"
    port: 2053
    uuid: "f62a1751-c1e4-4612-90e7-bd5781c1aede"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bz2.wba-pn.ru"
    client-fingerprint: "qq"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇷🇺_23"
    type: vless
    server: "185.147.27.183"
    port: 8443
    uuid: "379998c5-2a71-4202-9c74-522e0c3c5404"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "user-6a917f32.noooo.win"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_24"
    type: vless
    server: "87.249.54.103"
    port: 4100
    uuid: "db7de26b-96d8-452c-8b9d-4a6bf55a7da7"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_25"
    type: vless
    server: "83.147.246.153"
    port: 4100
    uuid: "85223e1a-f55d-4d0d-b27d-39e8be49d220"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_26"
    type: vless
    server: "201.51.1.84"
    port: 16923
    uuid: "ba222add-6ac1-45f1-9a18-f91cb38e324f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_QeslG3rHGM7DoM99pYC8-jpc16pM2MbNZ6NRMoxmHA"
      short-id: "10ffb85da1c2d986"
    network: grpc
    grpc-opts:
      grpc-service-name: "neurex"
  - name: "🇷🇺_27"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_28"
    type: vless
    server: "83.147.246.153"
    port: 2200
    uuid: "85223e1a-f55d-4d0d-b27d-39e8be49d220"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_29"
    type: vless
    server: "176.109.85.99"
    port: 443
    uuid: "edf302e9-9c00-465c-ae09-8c4c2015f2a7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "st.ozone.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "XeRWYynZqOAQzh2R82AbywidddTr-gvWwgKHiXRKiSE"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_30"
    type: vless
    server: "87.228.122.108"
    port: 4100
    uuid: "155e8dd4-a559-407a-9ea8-13a5e829f066"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇷🇺_31"
    type: vless
    server: "wstg.datasynctrue.online"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_32"
    type: vless
    server: "168.222.194.138"
    port: 9880
    uuid: "76186f1e-3062-4a2b-98c2-fab3c61a9511"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_33"
    type: vless
    server: "185.147.27.164"
    port: 8443
    uuid: "3a90bf69-1ffe-4ebb-b9a7-ad9ba8e9f66f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "user-6a8d949a.noooo.win"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_34"
    type: vless
    server: "45.155.52.231"
    port: 443
    uuid: "219f9fec-8983-4f6f-af8c-31bd0c6dbf19"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ru2.skydrgn-online.online"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "6p0aVCkOgd-xaxqSMANYABL6O4Tdbftnxjiy5qcmISQ"
      short-id: "0b"
  - name: "🇷🇺_35"
    type: vless
    server: "bz16.wba-pn.ru"
    port: 2053
    uuid: "b712ae49-e20f-44d9-ae80-b81f399c5a3a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bz16.wba-pn.ru"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "bz16.wba-pn.ru"
  - name: "🇷🇺_36"
    type: vless
    server: "194.55.239.192"
    port: 11443
    uuid: "5e9fe9c1-38f7-43db-8340-abdd925a551b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "rutube.ru"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "ooXXG3qUvCSb9W_ronALTGzEoTIrJKTaoXevJgISJ1M"
      short-id: "561533e7f4"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_37"
    type: vless
    server: "81.200.144.27"
    port: 4100
    uuid: "f0528a17-863f-4160-a5a0-0d9ad03f2ee7"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_38"
    type: vless
    server: "178.72.147.246"
    port: 4100
    uuid: "5181e3af-4a0c-47d7-8beb-7e4fa4786cdd"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_39"
    type: vless
    server: "5.42.106.111"
    port: 2200
    uuid: "099f0859-cb81-4a57-b6d8-2c8e18030627"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_40"
    type: vless
    server: "194.26.229.122"
    port: 2200
    uuid: "84d0ff7b-9760-415f-a974-b3e1fe92264f"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇷🇺_41"
    type: vless
    server: "5.42.103.91"
    port: 2200
    uuid: "7b2ce6b0-6d2b-4926-b7bf-6247eb1a0050"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇷🇺_42"
    type: vless
    server: "109.196.98.121"
    port: 2053
    uuid: "380f152a-33b3-456e-b5db-970aa27c32e3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "tr.wba-pn.ru"
    client-fingerprint: "qq"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇷🇺_43"
    type: vless
    server: "178.72.147.249"
    port: 4100
    uuid: "d0685701-2fdb-4a50-b1a5-d764c2bb5a43"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇷🇺_44"
    type: vless
    server: "lte-nl.cdn-assets-pro.com"
    port: 443
    uuid: "b49a0ce3-33e2-434a-8023-bb5f565c7ebe"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.byteark.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "N6RiU4XHQl31HeKmBNOFDypgfDqqshGa7zxfqe72hjk"
      short-id: "e42075de64c24511"
    network: grpc
    grpc-opts:
      grpc-service-name: "ns"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"
      - "🇷🇺_20"
      - "🇷🇺_21"
      - "🇷🇺_22"
      - "🇷🇺_23"
      - "🇷🇺_24"
      - "🇷🇺_25"
      - "🇷🇺_26"
      - "🇷🇺_27"
      - "🇷🇺_28"
      - "🇷🇺_29"
      - "🇷🇺_30"
      - "🇷🇺_31"
      - "🇷🇺_32"
      - "🇷🇺_33"
      - "🇷🇺_34"
      - "🇷🇺_35"
      - "🇷🇺_36"
      - "🇷🇺_37"
      - "🇷🇺_38"
      - "🇷🇺_39"
      - "🇷🇺_40"
      - "🇷🇺_41"
      - "🇷🇺_42"
      - "🇷🇺_43"
      - "🇷🇺_44"


rules:
  - MATCH,PROXY
