name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "186.246.12.242"
    port: 2053
    uuid: "9a47a8ff-8cdd-4a35-b765-fbad6d40e0a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bz9.wba-pn.ru"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "bz9.wba-pn.ru"
  - name: "🇷🇺_2"
    type: vless
    server: "80.90.185.80"
    port: 9892
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_3"
    type: vless
    server: "91.210.169.181"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_4"
    type: vless
    server: "185.147.27.183"
    port: 8443
    uuid: "379998c5-2a71-4202-9c74-522e0c3c5404"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "user-6a917f32.noooo.win"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_5"
    type: vless
    server: "77.110.104.125"
    port: 8443
    uuid: "e0b9fb0f-1bbd-478b-9580-c2294778338b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "maps.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "OMlQAFrCMZ3DX0xlnbEZiByLBFzpUE8XJHJsrBzLdlY"
      short-id: "2da4299da566b7"
    network: grpc
    grpc-opts:
      grpc-service-name: "your-custom-path"
  - name: "🇷🇺_6"
    type: vless
    server: "200.169.182.57"
    port: 443
    uuid: "7a97f64d-5fc7-4011-9028-58d2ba751595"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "defaultenginedimly.rivetpress.me"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "niL0fb-4IaVHr5VCg2yN_5wDTNYEq9W8wi7pDWLPcVg"
      short-id: "7505bfa3b6b933e6"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_7"
    type: vless
    server: "85.198.70.200"
    port: 14406
    uuid: "237f91bf-102e-4077-8cc3-baebccb42936"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.ru"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "ldAmsl3dqTCUBmlmA8CS9ZnpznP6cFWj9AxNddWnbxY"
      short-id: "1a2b3c4d5e6f7a8b"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_8"
    type: vless
    server: "95.213.184.165"
    port: 9844
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_9"
    type: vless
    server: "188.225.33.141"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_10"
    type: vless
    server: "84.38.185.149"
    port: 9889
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_11"
    type: vless
    server: "82.202.157.181"
    port: 9882
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_12"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_13"
    type: vless
    server: "193.233.217.140"
    port: 2200
    uuid: "19365fd3-d23c-4a9e-a2ef-543d230e65c4"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇷🇺_14"
    type: vless
    server: "144.31.50.236"
    port: 443
    uuid: "1c332eae-7e02-4acd-996d-4eb3e652401c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "randomized"
    reality-opts:
      public-key: "uitO4Z8t9TplwwYaqwLqh5rfxDh_X8bOBiNuPbzvaEM"
      short-id: "bbe46bd8f6b96839"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_15"
    type: vless
    server: "109.172.39.252"
    port: 8443
    uuid: "246b101b-4e4a-451f-8e9c-5e8d3b64b4ef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "maps.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "22xsvJd-vHeh8Xtg7n8Zb6C7yz31UCPyWZTreKTUrlY"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "your-custom-path"
  - name: "🇷🇺_16"
    type: vless
    server: "77.110.104.125"
    port: 443
    uuid: "e0b9fb0f-1bbd-478b-9580-c2294778338b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "maps.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "gr7DAOBqoNiHEUhWZQh3nSqBOmg6QwmRC0HKj7TOsUk"
      short-id: "2da4299da566b7"
    network: grpc
    grpc-opts:
      grpc-service-name: "your-custom-path"
  - name: "🇷🇺_17"
    type: vless
    server: "46.243.235.188"
    port: 443
    uuid: "ecf728d9-1555-4e12-b178-1d8bd98465e4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "pool.dataroute.biz"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "_ilhBTibNauMOEUqylnlBAUTYiqHHtmEDXkx18SHCR4"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_18"
    type: vless
    server: "46.8.208.29"
    port: 443
    uuid: "2f39df59-0ec9-4b92-b6f7-10f746942c70"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.okko.tv"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "HHZwsut0m8Z4tTCbU0QdnbyfQMQfk8XuEbBO0wFObis"
      short-id: "7765b2a4cef1033e"
    network: grpc
    grpc-opts:
      grpc-service-name: "UpdateService"
  - name: "🇷🇺_19"
    type: vless
    server: "193.233.221.163"
    port: 443
    uuid: "7a97f64d-5fc7-4011-9028-58d2ba751595"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "glowingjockeycorny.grayribbon.app"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "GJu4Ucn-XsY8pYyihFZOtFZWaowxSV8JqcVozlfSqkk"
      short-id: "e066cfc5aed13a33"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_20"
    type: vless
    server: "46.8.208.29"
    port: 443
    uuid: "5f922903-69b5-4d99-924d-52ca6337741e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.okko.tv"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "HHZwsut0m8Z4tTCbU0QdnbyfQMQfk8XuEbBO0wFObis"
      short-id: "7765b2a4cef1033e"
    network: grpc
    grpc-opts:
      grpc-service-name: "UpdateService"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"
      - "🇷🇺_20"


rules:
  - MATCH,PROXY
