name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇷🇺_1"
    type: vless
    server: "176.108.241.137"
    port: 9882
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_2"
    type: vless
    server: "176.108.241.137"
    port: 9891
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_3"
    type: vless
    server: "185.229.9.137"
    port: 443
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "vk.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "wKK4zrsWJkXdJdmllznFD39qW2cUKDBKwIe3PvWqonU"
      short-id: "27e53bbcab7593d7"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_4"
    type: vless
    server: "79.137.192.2"
    port: 443
    uuid: "2412bd96-925b-43f2-81d1-0ed4f0793699"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn.cloudflare.steamstatic.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "zcA1E7_aUxhHP1B4po52NeviW16smzEqcyb2qiQYaTc"
      short-id: ""
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_5"
    type: vless
    server: "79.174.95.96"
    port: 443
    uuid: "7974c820-9744-44a0-9fee-67292b70e125"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "tVc65Jg20nTeP9qsSd9WIqRjLqU-PWKFYtBYHQbwtyw"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇷🇺_6"
    type: vless
    server: "185.229.9.31"
    port: 47175
    uuid: "b2ec02a7-df54-428d-9cf7-de8f35fedc18"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xnWGzgAkUvHwQ7iDHFhkgyRUmBL1VV-H-F1rfll48BI"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇷🇺_7"
    type: vless
    server: "144.31.93.231"
    port: 443
    uuid: "3710fc0f-5f0c-4b9c-a5d4-40cb419e943a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "WKN5yaRN05O2WdCURXRmS-yBVYaabaFWOvGudX6ohWc"
      short-id: "b97e7d4582b6fa6e"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_8"
    type: vless
    server: "176.108.247.67"
    port: 9881
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_9"
    type: vless
    server: "176.109.104.195"
    port: 9873
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_10"
    type: vless
    server: "193.163.203.170"
    port: 443
    uuid: "11aabba0-5fd1-4f15-8068-74c1a466cefc"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "GCCZ1ZZjB_nj7yxqFi22bIIWWr_G6rnWUzDcssN_40o"
      short-id: "b28db60d77c50b4f"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_11"
    type: vless
    server: "176.108.243.18"
    port: 9872
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "sm3E3hjmT6_Gmg_O9rBz4nfXYrHpnl6-LvcCp6T6_xc"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_12"
    type: vless
    server: "72.4.65.116"
    port: 443
    uuid: "0dca2cfe-98eb-4f9d-9a47-cf87510c558b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "assets-de2.pleiades.codes"
    client-fingerprint: "chrome"
    network: grpc
    grpc-opts:
      grpc-service-name: "cdn.v1.AssetService"
  - name: "🇷🇺_13"
    type: vless
    server: "212.113.120.174"
    port: 443
    uuid: "2412bd96-925b-43f2-81d1-0ed4f0793699"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "lk.x5.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "gjdfyCCn9DXEzaAmN-geTg1sCvVj1WEwuhmgXIReR1E"
      short-id: "f932c14eee8ef133"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_14"
    type: vless
    server: "2.26.10.137"
    port: 443
    uuid: "fdc48be3-a615-41ac-8bd1-ed844c931048"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "edgetunnel-4uw.pages.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "edgetunnel-4uw.pages.dev"
  - name: "🇷🇺_15"
    type: vless
    server: "144.31.50.236"
    port: 443
    uuid: "1c332eae-7e02-4acd-996d-4eb3e652401c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "uitO4Z8t9TplwwYaqwLqh5rfxDh_X8bOBiNuPbzvaEM"
      short-id: "bbe46bd8f6b96839"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_16"
    type: vless
    server: "176.109.104.195"
    port: 9882
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_17"
    type: vless
    server: "79.174.95.96"
    port: 443
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "tVc65Jg20nTeP9qsSd9WIqRjLqU-PWKFYtBYHQbwtyw"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇷🇺_18"
    type: vless
    server: "186.246.12.242"
    port: 2053
    uuid: "9a47a8ff-8cdd-4a35-b765-fbad6d40e0a0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "speedtest.tinkoff.ru"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇷🇺_19"
    type: vless
    server: "213.171.25.178"
    port: 9830
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_20"
    type: vless
    server: "85.208.86.91"
    port: 9872
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "sm3E3hjmT6_Gmg_O9rBz4nfXYrHpnl6-LvcCp6T6_xc"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_21"
    type: vless
    server: "176.108.246.58"
    port: 9889
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_22"
    type: vless
    server: "shprcdn.homes"
    port: 8443
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "shprcdn.homes"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PwTWopKMpDawru-Y7AllJMSAORInNOBKuA28h0r9DXE"
      short-id: "ba35e449b9e0"
    network: grpc
    grpc-opts:
      grpc-service-name: "media.ingest.v2.ChunkUploadService"
  - name: "🇷🇺_23"
    type: vless
    server: "176.108.246.73"
    port: 9873
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_24"
    type: vless
    server: "168.222.194.138"
    port: 9880
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_25"
    type: vless
    server: "46.243.232.117"
    port: 2026
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smartcaptcha.yandexcloud.net"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "mYfxnx_YSzgRITmnYu_icly3s1BUaocGdqYTNMyERVA"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇷🇺_26"
    type: vless
    server: "200.165.231.209"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_27"
    type: vless
    server: "79.174.92.185"
    port: 443
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PAP10NLpy_4J_vf1CEtDuLJtce3pLSNhHLbuuAUXqBU"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇷🇺_28"
    type: vless
    server: "188.225.33.141"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_29"
    type: vless
    server: "95.163.232.171"
    port: 14443
    uuid: "365de9e9-ba29-4819-af2d-766f9638e3be"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "media-se.compressor.work"
    client-fingerprint: "android"
    network: ws
    ws-opts:
      path: "/ws"
  - name: "🇷🇺_30"
    type: vless
    server: "213.171.25.29"
    port: 9889
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_31"
    type: vless
    server: "95.163.232.98"
    port: 443
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ZgSVwP_wlM4-oG8E03W3cMqK_VrS8oHXF4wzyBkISWo"
      short-id: "a1b2c3d4"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "🇷🇺_32"
    type: vless
    server: "185.229.9.237"
    port: 43119
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "max.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ZHAz8dR_SKkAI_wAHiXhQfFaqsAbCQa5kF7OKCzRNn0"
      short-id: "e0bae89a"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"
  - name: "🇷🇺_33"
    type: vless
    server: "91.210.169.181"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇷🇺_34"
    type: vless
    server: "193.163.203.199"
    port: 443
    uuid: "3e2591b2-4739-4c59-b540-344f0b6505ac"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "x6.megabitvpn.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xa2v36oJSdYGM1SSiMYyehw9RTdlBHOLcE5-YOK6unE"
      short-id: "3c7ab85b281ecc8f"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_35"
    type: vless
    server: "45.12.75.242"
    port: 26424
    uuid: "633f424e-2b11-48da-a6b3-a849dd71456f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "l8AubqcxQO-HRFJy4pZL1vbLOo-eXit69s-XulSELE0"
      short-id: "23103e1e"
  - name: "🇷🇺_36"
    type: vless
    server: "45.9.24.199"
    port: 8443
    uuid: "8d2341a3-13b8-4e5e-84e1-da1c4923149a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "shprcdn.homes"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "PwTWopKMpDawru-Y7AllJMSAORInNOBKuA28h0r9DXE"
      short-id: "ba35e449b9e0"
    network: grpc
    grpc-opts:
      grpc-service-name: "media.ingest.v2.ChunkUploadService"
  - name: "🇷🇺_37"
    type: vless
    server: "138.124.255.165"
    port: 25535
    uuid: "c379d8e4-c67d-42ec-a3ed-ca99d1ad0546"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.microsoft.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Jh7CocBJSA55VZcLfXwXwoQ_Hi5pV-L1vv1SY-IrSh4"
      short-id: "7642ce57308852e7"
  - name: "🇷🇺_38"
    type: vless
    server: "176.108.246.110"
    port: 9830
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_39"
    type: vless
    server: "176.123.165.180"
    port: 9881
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aabbccdd"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_40"
    type: vless
    server: "176.108.244.178"
    port: 9881
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "ycPIUcY6ci2yi7YA_OHc20e4gzxEdJTqpmeShxSuHRU"
      short-id: "aa"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_41"
    type: vless
    server: "176.108.244.38"
    port: 9881
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_42"
    type: vless
    server: "176.123.162.100"
    port: 9880
    uuid: "5d16ac22-6eea-426f-b778-6f4c2961faef"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇷🇺_43"
    type: vless
    server: "91.240.87.237"
    port: 443
    uuid: "1b201db0-b373-455a-8ccd-fd624aaef8d3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fiae3.maxtelemost.com"
    client-fingerprint: "random"
    reality-opts:
      public-key: "J0SK1ic3YJvP1gac5m3KSVaUuK_bxFtqz0fh0uEdEw4"
      short-id: "00000000"
    flow: "xtls-rprx-vision"
  - name: "🇷🇺_44"
    type: ss
    server: "80.242.57.97"
    port: 1
    cipher: "chacha20-ietf-poly1305"
    password: "9qGcNiZj4uCi7DGSjxlg5Q"
    udp: true
  - name: "🇷🇺_45"
    type: ss
    server: "80.242.57.97"
    port: 3
    cipher: "chacha20-ietf-poly1305"
    password: "9qGcNiZj4uCi7DGSjxlg5Q"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇷🇺_1"
      - "🇷🇺_2"
      - "🇷🇺_3"
      - "🇷🇺_4"
      - "🇷🇺_5"
      - "🇷🇺_6"
      - "🇷🇺_7"
      - "🇷🇺_8"
      - "🇷🇺_9"
      - "🇷🇺_10"
      - "🇷🇺_11"
      - "🇷🇺_12"
      - "🇷🇺_13"
      - "🇷🇺_14"
      - "🇷🇺_15"
      - "🇷🇺_16"
      - "🇷🇺_17"
      - "🇷🇺_18"
      - "🇷🇺_19"
      - "🇷🇺_20"
      - "🇷🇺_21"
      - "🇷🇺_22"
      - "🇷🇺_23"
      - "🇷🇺_24"
      - "🇷🇺_25"
      - "🇷🇺_26"
      - "🇷🇺_27"
      - "🇷🇺_28"
      - "🇷🇺_29"
      - "🇷🇺_30"
      - "🇷🇺_31"
      - "🇷🇺_32"
      - "🇷🇺_33"
      - "🇷🇺_34"
      - "🇷🇺_35"
      - "🇷🇺_36"
      - "🇷🇺_37"
      - "🇷🇺_38"
      - "🇷🇺_39"
      - "🇷🇺_40"
      - "🇷🇺_41"
      - "🇷🇺_42"
      - "🇷🇺_43"
      - "🇷🇺_44"
      - "🇷🇺_45"


rules:
  - MATCH,PROXY
