name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇨_1"
    type: vless
    server: "45.130.125.162"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "po.fastbrokencompony.com"
  - name: "🇸🇨_2"
    type: vless
    server: "45.130.125.158"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "po.fastbrokencompony.com"
  - name: "🇸🇨_3"
    type: vless
    server: "200.165.228.114"
    port: 9871
    uuid: "2a650f3b-d95b-4bd6-aadf-16ccc0717155"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Dfgu8Ey0M8Hz4gXGZAwQ3H9jLt2HByVsjAOTWiuKDB0"
      short-id: "aabb"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇸🇨_4"
    type: vless
    server: "200.165.228.51"
    port: 4100
    uuid: "e3a625d4-5adb-463d-bbff-bbe06b8e2c5c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇸🇨_5"
    type: vless
    server: "45.130.125.138"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "firefox"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_6"
    type: vless
    server: "200.165.234.62"
    port: 4100
    uuid: "5383fb97-1178-4709-9a25-b767b743e911"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇸🇨_7"
    type: vless
    server: "45.130.125.207"
    port: 80
    uuid: "dc8eccdb-ecfa-435f-9ac1-5dc4882e7b51"
    udp: true
    network: ws
    ws-opts:
      path: "/http"
      headers:
        Host: "de.vpnbase.net"
  - name: "🇸🇨_8"
    type: vless
    server: "200.165.228.47"
    port: 4100
    uuid: "6620ef58-9c62-43fe-9596-ff862b200958"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇸🇨_9"
    type: vless
    server: "200.165.228.51"
    port: 2200
    uuid: "e3a625d4-5adb-463d-bbff-bbe06b8e2c5c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇸🇨_10"
    type: vless
    server: "45.130.125.158"
    port: 443
    uuid: "4311bd3f-4f66-4538-a624-221b87690b2c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "mjtbknetmkhremge.ordak.qzz.io"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/fl?ed"
      headers:
        Host: "mjtbknetmkhremge.ordak.qzz.io"
  - name: "🇸🇨_11"
    type: vless
    server: "45.130.125.207"
    port: 443
    uuid: "b2f6aa3a-2550-4a1c-b2c0-1c94b1207217"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "terazhediii.info"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/hdgrbws"
      headers:
        Host: "terazhediii.info"
  - name: "🇸🇨_12"
    type: trojan
    server: "45.130.125.112"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇸🇨_13"
    type: trojan
    server: "45.130.125.75"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_14"
    type: trojan
    server: "45.130.125.76"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_15"
    type: trojan
    server: "45.130.125.190"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇨_1"
      - "🇸🇨_2"
      - "🇸🇨_3"
      - "🇸🇨_4"
      - "🇸🇨_5"
      - "🇸🇨_6"
      - "🇸🇨_7"
      - "🇸🇨_8"
      - "🇸🇨_9"
      - "🇸🇨_10"
      - "🇸🇨_11"
      - "🇸🇨_12"
      - "🇸🇨_13"
      - "🇸🇨_14"
      - "🇸🇨_15"


rules:
  - MATCH,PROXY
