name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇨_1"
    type: vless
    server: "200.165.234.119"
    port: 2200
    uuid: "936b7663-a841-4b42-b639-6e3fab1dbf45"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇸🇨_2"
    type: vless
    server: "200.165.234.62"
    port: 4100
    uuid: "5383fb97-1178-4709-9a25-b767b743e911"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇸🇨_3"
    type: vless
    server: "45.130.125.201"
    port: 80
    uuid: "dc8a9493-c54a-459e-d060-81a700000001"
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "nahan-core.netizo09.workers.dev"
  - name: "🇸🇨_4"
    type: vless
    server: "200.165.235.43"
    port: 2053
    uuid: "41f33146-7eb4-11f1-855a-d60b69bb56c6"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dzen.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "j8OW1foMwfeiy3VMbNPHLgTXgy_ZPdFFxv-H3HrbNF0"
      short-id: "2c60309fa586eb60"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-direct"
  - name: "🇸🇨_5"
    type: vless
    server: "200.165.231.209"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "200.165.231.209"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇸🇨_6"
    type: vless
    server: "45.130.125.207"
    port: 80
    uuid: "dc8eccdb-ecfa-435f-9ac1-5dc4882e7b51"
    udp: true
    network: ws
    ws-opts:
      path: "/http"
      headers:
        Host: "de.vpnbase.net"
  - name: "🇸🇨_7"
    type: trojan
    server: "45.130.125.75"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_8"
    type: trojan
    server: "45.130.125.76"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_9"
    type: trojan
    server: "45.130.125.160"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_10"
    type: trojan
    server: "45.130.125.190"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇨_1"
      - "🇸🇨_2"
      - "🇸🇨_3"
      - "🇸🇨_4"
      - "🇸🇨_5"
      - "🇸🇨_6"
      - "🇸🇨_7"
      - "🇸🇨_8"
      - "🇸🇨_9"
      - "🇸🇨_10"


rules:
  - MATCH,PROXY
