name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇨_1"
    type: vless
    server: "45.130.125.138"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_2"
    type: vless
    server: "ru.golu-gulu.online"
    port: 3443
    uuid: "e7c11cc8-e4ae-45cf-98ef-6d9bc9cc5aa7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "id.pervye.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "xEShpzw3ELhAha1ilVBZdkfgxtRMxZmP8Ji_Y3FZSX0"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "nss"
  - name: "🇸🇨_3"
    type: vless
    server: "200.165.234.83"
    port: 443
    uuid: "8aca40d2-0f55-4ca2-97cb-b22ec432b82d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ya.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "MEf-wwgnhZG97nPrgwU2gry9o9lKn8PmaNNi6OaMEy8"
      short-id: "3c7ad26694142132"
    flow: "xtls-rprx-vision"
  - name: "🇸🇨_4"
    type: vless
    server: "45.130.125.207"
    port: 80
    uuid: "dc8eccdb-ecfa-435f-9ac1-5dc4882e7b51"
    udp: true
    network: ws
    ws-opts:
      path: "/http"
      headers:
        Host: "de.vpnbase.net"
  - name: "🇸🇨_5"
    type: vless
    server: "45.130.125.209"
    port: 80
    uuid: "dc8eccdb-ecfa-435f-9ac1-5dc4882e7b51"
    udp: true
    network: ws
    ws-opts:
      path: "/http"
      headers:
        Host: "de.vpnbase.net"
  - name: "🇸🇨_6"
    type: vless
    server: "200.165.228.47"
    port: 4100
    uuid: "6620ef58-9c62-43fe-9596-ff862b200958"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇸🇨_7"
    type: vless
    server: "200.165.228.51"
    port: 4100
    uuid: "e3a625d4-5adb-463d-bbff-bbe06b8e2c5c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇸🇨_8"
    type: vless
    server: "45.130.125.50"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime58.workers.dev"
  - name: "🇸🇨_9"
    type: vless
    server: "200.165.234.238"
    port: 8443
    uuid: "e7c11cc8-e4ae-45cf-98ef-6d9bc9cc5aa7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "id.pervye.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xEShpzw3ELhAha1ilVBZdkfgxtRMxZmP8Ji_Y3FZSX0"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "nss"
  - name: "🇸🇨_10"
    type: vless
    server: "wstg.datasynctrue.online"
    port: 443
    uuid: "ff0b6ba8-bed0-4c4d-bbc9-23af47582615"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "wstg.datasynctrue.online"
    client-fingerprint: "qq"
    network: ws
    ws-opts:
      path: "/api/connect"
      headers:
        Host: "wstg.datasynctrue.online"
  - name: "🇸🇨_11"
    type: vless
    server: "200.165.234.62"
    port: 4100
    uuid: "5383fb97-1178-4709-9a25-b767b743e911"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "live.ok.ru"
  - name: "🇸🇨_12"
    type: vless
    server: "45.130.125.162"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "ios"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "po.fastbrokencompony.com"
  - name: "🇸🇨_13"
    type: vless
    server: "45.130.125.114"
    port: 8443
    uuid: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "ssl.soren-app.com."
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "free-hzr113-cdn.soren-app.com."
  - name: "🇸🇨_14"
    type: vless
    server: "200.165.228.51"
    port: 2200
    uuid: "e3a625d4-5adb-463d-bbff-bbe06b8e2c5c"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
  - name: "🇸🇨_15"
    type: vless
    server: "45.130.125.73"
    port: 80
    uuid: "50414e45-4c5f-5a45-5553-cea58e4acf49"
    udp: true
    network: ws
    ws-opts:
      path: "/api/ws"
      headers:
        Host: "web-app-aug8yr.app-f1qsy1.workers.dev"
  - name: "🇸🇨_16"
    type: vless
    server: "45.130.125.201"
    port: 80
    uuid: "dc8a9493-c54a-459e-d060-81a700000001"
    udp: true
    network: ws
    ws-opts:
      path: "/sync"
      headers:
        Host: "nahan-core.netizo09.workers.dev"
  - name: "🇸🇨_17"
    type: vless
    server: "200.165.234.119"
    port: 2200
    uuid: "936b7663-a841-4b42-b639-6e3fab1dbf45"
    udp: true
    network: ws
    ws-opts:
      path: "/v1"
      headers:
        Host: "rzd.ru"
  - name: "🇸🇨_18"
    type: vless
    server: "45.130.125.207"
    port: 443
    uuid: "6680846a-8a57-4dfd-9a0e-63209cfc8535"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "support.zoom.us.yxls.eu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/sg-amz"
      headers:
        Host: "support.zoom.us.yxls.eu.cc"
  - name: "🇸🇨_19"
    type: vless
    server: "ru.golu-gulu.online"
    port: 8443
    uuid: "e7c11cc8-e4ae-45cf-98ef-6d9bc9cc5aa7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "id.pervye.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "xEShpzw3ELhAha1ilVBZdkfgxtRMxZmP8Ji_Y3FZSX0"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "nss"
  - name: "🇸🇨_20"
    type: vless
    server: "45.130.125.158"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "po.fastbrokencompony.com"
  - name: "🇸🇨_21"
    type: vless
    server: "45.130.125.200"
    port: 2053
    uuid: "e7961655-9674-4cbd-a36f-ec0d5d7d660c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "po.fastbrokencompony.com"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇨_22"
    type: vless
    server: "200.165.234.238"
    port: 3443
    uuid: "e7c11cc8-e4ae-45cf-98ef-6d9bc9cc5aa7"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "id.pervye.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "xEShpzw3ELhAha1ilVBZdkfgxtRMxZmP8Ji_Y3FZSX0"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "nss"
  - name: "🇸🇨_23"
    type: trojan
    server: "45.130.125.18"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇸🇨_24"
    type: trojan
    server: "45.130.125.75"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_25"
    type: trojan
    server: "45.130.125.160"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_26"
    type: trojan
    server: "45.130.125.112"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇸🇨_27"
    type: trojan
    server: "45.130.125.76"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"
  - name: "🇸🇨_28"
    type: trojan
    server: "45.130.125.126"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
  - name: "🇸🇨_29"
    type: trojan
    server: "45.130.125.190"
    port: 443
    password: "humanity"
    sni: "www.calmlunch.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmlunch.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇨_1"
      - "🇸🇨_2"
      - "🇸🇨_3"
      - "🇸🇨_4"
      - "🇸🇨_5"
      - "🇸🇨_6"
      - "🇸🇨_7"
      - "🇸🇨_8"
      - "🇸🇨_9"
      - "🇸🇨_10"
      - "🇸🇨_11"
      - "🇸🇨_12"
      - "🇸🇨_13"
      - "🇸🇨_14"
      - "🇸🇨_15"
      - "🇸🇨_16"
      - "🇸🇨_17"
      - "🇸🇨_18"
      - "🇸🇨_19"
      - "🇸🇨_20"
      - "🇸🇨_21"
      - "🇸🇨_22"
      - "🇸🇨_23"
      - "🇸🇨_24"
      - "🇸🇨_25"
      - "🇸🇨_26"
      - "🇸🇨_27"
      - "🇸🇨_28"
      - "🇸🇨_29"


rules:
  - MATCH,PROXY
