name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "79.141.174.147"
    port: 33743
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "wGMBs7bvzyzA0-OUiwSkOOTDEMdxEOsSdRzxiP8GGQY"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇸🇪_2"
    type: vless
    server: "193.42.39.10"
    port: 33743
    uuid: "b3a11068-1a7e-4643-85de-7c82cce46943"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "wGMBs7bvzyzA0-OUiwSkOOTDEMdxEOsSdRzxiP8GGQY"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇸🇪_3"
    type: vless
    server: "eu-central-pl-1.hanvpn.biz"
    port: 443
    uuid: "d9d0f208-d582-41d5-bb7b-742671402810"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central-pl-1.hanvpn.biz"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "NjIuu35vz5MthSzqd6kt8PbXbZxCCL2Rb2GbpMCRTEY"
      short-id: "12e3b7681806bc97"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_4"
    type: vless
    server: "45.80.230.2"
    port: 443
    uuid: "56cba26b-efcb-40d0-838a-d66df2dd516f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sni.868001.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_5"
    type: vless
    server: "eu-north-sw-1.hanvpn.biz"
    port: 443
    uuid: "d9d0f208-d582-41d5-bb7b-742671402810"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-north-sw-1.hanvpn.biz"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "ELFdNdI6NYwuEq5OqCkYwnUInHvIpsUhd4z2ud7pOCM"
      short-id: "0172b7681806bc97"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_6"
    type: vless
    server: "167.104.104.138"
    port: 8443
    uuid: "a5194487-9b9a-462f-a047-ac7580d80201"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "n.tmkkarss.online"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_7"
    type: vless
    server: "5.157.10.146"
    port: 443
    uuid: "732255eb-8ce9-4cd5-8bdc-376bd3fa0b11"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sweb1.loozerp.wiki"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "x6p656szvu_3CKLsJ4NtkooRvdTVGx7IoPca_p58_jA"
      short-id: "fb442438e2223836"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_8"
    type: vless
    server: "193.148.59.178"
    port: 443
    uuid: "20d7c485-5d24-49b5-a5cc-bb7a7daf9908"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-GMpCber8qtrKzJbwvpLcwlIhOy-5zS66u_x9lLvIjE"
      short-id: "e3daad69"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_9"
    type: vless
    server: "serr-arnrr-2.blook.network"
    port: 443
    uuid: "93fa1107-b1b4-4a45-b4e7-890f7dbac7b3"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "serr-arnrr-2.blook.network"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "2neBenQDielZoPvaNGMsjWEHOqHRKvSEw0e1NapEmAw"
      short-id: "5227"
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"


rules:
  - MATCH,PROXY
