name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇪_1"
    type: vless
    server: "v-de-node-03.bot-auth.com"
    port: 8443
    uuid: "b9b1e7c9-4160-49b4-85a4-2f096706509a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.oracle.com"
    reality-opts:
      public-key: "dNfk0sOCzOlmE61B7ur7YzU2i08RqXIBcGVBA2Ne1Ck"
      short-id: "7548bc"
  - name: "🇸🇪_2"
    type: vless
    server: "89.125.76.140"
    port: 443
    uuid: "218fd696-e3a2-4c33-b397-a5f13a82969e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "se12.tcpnet.fun"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Z22m3SU-sV639Bdnchaz6Xe9px7TEl9IcqQR02tFgDA"
      short-id: "15e86cec"
  - name: "🇸🇪_3"
    type: vless
    server: "150.241.79.143"
    port: 8443
    uuid: "b9b1e7c9-4160-49b4-85a4-2f096706509a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.oracle.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "dNfk0sOCzOlmE61B7ur7YzU2i08RqXIBcGVBA2Ne1Ck"
      short-id: "7548bc"
  - name: "🇸🇪_4"
    type: vless
    server: "213.176.112.136"
    port: 5222
    uuid: "8d955d71-ed5d-4f4c-ae68-42d120f06861"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/@Marisa_kristi"
      headers:
        Host: "kqjifhg9rw.tradsc8p9xp7wxyqmc1wy0ah.workers.dev"
  - name: "🇸🇪_5"
    type: vless
    server: "194.87.30.161"
    port: 22647
    uuid: "ffa289e7-a058-493a-b234-3db1f26378d7"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇪_6"
    type: vless
    server: "94.242.59.190"
    port: 443
    uuid: "4f375fb4-3c95-425f-bc7b-8085487a6f3c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "31.76.11.46.cdn-one.org"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/52872/BNzG4FvIAr"
      headers:
        Host: "31.76.11.46.cdn-one.org"
  - name: "🇸🇪_7"
    type: vless
    server: "142.111.244.75"
    port: 448
    uuid: "f128bc2c-8018-43a1-8ed7-66eabc8f157c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.samsung.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "r8ljXJO_4yLUonHdkPeWbD9A__XqoudwWAiXx9fbcj8"
      short-id: "39a997621a3598c9"
  - name: "🇸🇪_8"
    type: vless
    server: "46.246.92.109"
    port: 443
    uuid: "14f19724-de91-4285-a633-aa8e2caaf812"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.rumedia-cdn.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "JwL5KoiWkCJI2vMJxyTEplfv-zBAtwxOH8SMbw6QHzY"
      short-id: "cd40c992fe4b10c2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_9"
    type: vless
    server: "85.137.170.110"
    port: 443
    uuid: "06d44c57-8e1a-41f4-b9c4-65d35869e078"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "smm.tunnelpoint.space"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "aBNWkd8CVkuimbtzgsDNsIUIENI-PQuKkpUInLncz2o"
      short-id: "fdda9806fe5d8584"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_10"
    type: vless
    server: "150.241.72.5"
    port: 443
    uuid: "fc1b3bda-b226-452a-8c5c-b0e36a1f8f88"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇸🇪_11"
    type: trojan
    server: "194.87.77.91"
    port: 443
    password: "1234567890"
    sni: "kfm-bn0.pages.dev"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇪_1"
      - "🇸🇪_2"
      - "🇸🇪_3"
      - "🇸🇪_4"
      - "🇸🇪_5"
      - "🇸🇪_6"
      - "🇸🇪_7"
      - "🇸🇪_8"
      - "🇸🇪_9"
      - "🇸🇪_10"
      - "🇸🇪_11"


rules:
  - MATCH,PROXY
