name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇬_1"
    type: vless
    server: "139.162.61.57"
    port: 443
    uuid: "03fcc618-b93d-6796-6aed-8a38c975d581"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "139.162.61.57"
  - name: "🇸🇬_2"
    type: vless
    server: "152.42.217.27"
    port: 4321
    uuid: "b8f3a337-ad39-4064-95f1-33a725a65877"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "iFKNWOLqlwrSmvR8wkxap1u85leVrr6YqEBy3Vn8WX0"
      short-id: "950e9d42106bedae"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_3"
    type: vless
    server: "3.0.111.82"
    port: 17623
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_4"
    type: vless
    server: "3.0.111.82"
    port: 12972
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_5"
    type: vless
    server: "104.64.207.134"
    port: 443
    uuid: "1bc380b1-cff7-446f-b13f-5c0ad29fc75a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zero.csmaster.ggff.net"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇬_6"
    type: vless
    server: "178.128.112.70"
    port: 443
    uuid: "9206ae06-88ee-49b1-a558-531ade80fcaa"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amazon.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-O8QFkqeMAc6TzQp6eY1s38my_8jhBd7HDHxNki6QlY"
      short-id: "7f7f"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_7"
    type: vless
    server: "52.74.176.20"
    port: 443
    uuid: "5ad0bed3-68ac-495e-b778-8b2d0e1dc176"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "🇸🇬_8"
    type: vless
    server: "sgxi.959555.xyz"
    port: 10000
    uuid: "af6904c1-4349-4448-8e99-0024824a0c33"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gateway.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "xELgry1aUBwZLDAAvyiBkLTXsIi1M-mKhuqvwiP6FxU"
      short-id: "3b0b73e5"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_9"
    type: vless
    server: "217.217.254.126"
    port: 2053
    uuid: "6b408e62-c5d5-45e1-ae3a-4c9833d46d82"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "T4CMxxAJiCcrGk2r87kMkDcvmfNs3nL-gKleaE1wTHQ"
      short-id: "fb7ebc9996caf9ac"
  - name: "🇸🇬_10"
    type: vless
    server: "178.128.52.52"
    port: 443
    uuid: "efd11a89-7506-44ce-95b6-6654859f155b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "zoom.us"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "EeLAX-BAjzSdRes-zpUFzVOYsBedmP8lUOHhXXJFXyI"
      short-id: "5a42dbd7e26a0415"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_11"
    type: vless
    server: "140.245.50.174"
    port: 10000
    uuid: "af6904c1-4349-4448-8e99-0024824a0c33"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "gateway.icloud.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "xELgry1aUBwZLDAAvyiBkLTXsIi1M-mKhuqvwiP6FxU"
      short-id: "3b0b73e5"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_12"
    type: vless
    server: "3.0.111.82"
    port: 10574
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_13"
    type: vless
    server: "91.192.81.214"
    port: 443
    uuid: "607801ac-dbdd-4938-a167-129015d9978e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bMcyxNueltQhz5Kuxcf8odDStWHowYfLhKNdCbUweDc"
      short-id: "d1742269"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_14"
    type: vless
    server: "194.233.75.66"
    port: 443
    uuid: "55d61055-1a7f-4bc5-aca2-4ee78c738b60"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sahanwickramasinghevip.shop"
    client-fingerprint: "firefox"
  - name: "🇸🇬_15"
    type: vless
    server: "103.106.229.190"
    port: 19261
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_16"
    type: vless
    server: "103.106.229.190"
    port: 13898
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_17"
    type: trojan
    server: "47.128.147.181"
    port: 443
    password: "AE62539071"
    sni: "rich-mule.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_18"
    type: trojan
    server: "sacred-anemone.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "sacred-anemone.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_19"
    type: trojan
    server: "integral-quetzal.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "integral-quetzal.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_20"
    type: trojan
    server: "47.129.157.81"
    port: 443
    password: "AE62539071"
    sni: "noted-bass.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_21"
    type: trojan
    server: "13.212.35.252"
    port: 443
    password: "AE62539071"
    sni: "adapted-whippet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_22"
    type: trojan
    server: "smooth-hornet.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "smooth-hornet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_23"
    type: trojan
    server: "47.131.229.80"
    port: 443
    password: "AE62539071"
    sni: "elegant-marten.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_24"
    type: trojan
    server: "13.212.44.180"
    port: 443
    password: "AE62539071"
    sni: "smooth-hornet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_25"
    type: trojan
    server: "adapted-whippet.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "adapted-whippet.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_26"
    type: trojan
    server: "rested-osprey.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "rested-osprey.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_27"
    type: trojan
    server: "excited-sole.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "excited-sole.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_28"
    type: trojan
    server: "47.131.225.150"
    port: 443
    password: "AE62539071"
    sni: "sacred-anemone.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_29"
    type: trojan
    server: "simple-rodent.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "simple-rodent.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_30"
    type: trojan
    server: "54.169.117.161"
    port: 443
    password: "AE62539071"
    sni: "simple-rodent.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_31"
    type: trojan
    server: "massive-terrapin.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "massive-terrapin.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_32"
    type: trojan
    server: "stirred-buck.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "stirred-buck.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_33"
    type: trojan
    server: "13.250.126.30"
    port: 443
    password: "AE62539071"
    sni: "adapted-martin.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_34"
    type: trojan
    server: "elegant-marten.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "elegant-marten.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_35"
    type: trojan
    server: "54.169.117.191"
    port: 443
    password: "AE62539071"
    sni: "excited-sole.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_36"
    type: trojan
    server: "rich-mule.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "rich-mule.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_37"
    type: trojan
    server: "54.169.241.164"
    port: 443
    password: "AE62539071"
    sni: "rested-osprey.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_38"
    type: trojan
    server: "13.229.94.200"
    port: 443
    password: "AE62539071"
    sni: "massive-terrapin.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_39"
    type: trojan
    server: "47.128.150.245"
    port: 443
    password: "AE62539071"
    sni: "stirred-buck.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_40"
    type: trojan
    server: "54.169.174.154"
    port: 443
    password: "AE62539071"
    sni: "absolute-hare.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_41"
    type: trojan
    server: "adapted-martin.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "adapted-martin.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_42"
    type: trojan
    server: "absolute-hare.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "absolute-hare.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_43"
    type: trojan
    server: "139.59.238.97"
    port: 50573
    password: "pvZE3UfT0ziK1omVLlsjINBqeqqwab1M"
    sni: "139.59.238.97"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_44"
    type: trojan
    server: "noted-bass.rooster465.autos"
    port: 443
    password: "AE62539071"
    sni: "noted-bass.rooster465.autos"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_45"
    type: ss
    server: "167.150.100.115"
    port: 27755
    cipher: "2022-blake3-aes-256-gcm"
    password: "fnvo82p9y4AKykZXyIFtnodFy6fQmWnVlI2SvGleOB0="
    udp: true
  - name: "🇸🇬_46"
    type: ss
    server: "167.150.100.115"
    port: 27755
    cipher: "2022-blake3-aes-256-gcm"
    password: "fnvo82p9y4AKykZXyIFtnodFy6fQmWnVlI2SvGleOB0="
    udp: true
  - name: "🇸🇬_47"
    type: ss
    server: "129.150.59.74"
    port: 14384
    cipher: "2022-blake3-aes-256-gcm"
    password: "sUR6Ny8Y6PSvHhl/DUxconwxg6VZyFdsdfaVCvEatJo=:7bTEhHgpErKiRjE1ega+H6pcpJsNLFB0CjQseujAHrA="
    udp: true
  - name: "🇸🇬_48"
    type: ss
    server: "167.150.100.115"
    port: 27755
    cipher: "2022-blake3-aes-256-gcm"
    password: "fnvo82p9y4AKykZXyIFtnodFy6fQmWnVlI2SvGleOB0="
    udp: true
  - name: "🇸🇬_49"
    type: ss
    server: "161.118.223.103"
    port: 56927
    cipher: "2022-blake3-chacha20-poly1305"
    password: "Qqi0DW+qDG5A4P9/gyCzj50oBg4cnsxXaUYEBuALI2g="
    udp: true
  - name: "🇸🇬_50"
    type: ss
    server: "sec2.masterdpibypass.com"
    port: 12892
    cipher: "chacha20-ietf-poly1305"
    password: "gwzmrnjrsep/PzW/3yYc4jE4RG41aEwJAthlbTupBjw="
    udp: true
  - name: "🇸🇬_51"
    type: ss
    server: "sec2.masterdpibypass.com"
    port: 12892
    cipher: "chacha20-ietf-poly1305"
    password: "gwzmrnjrsep/PzW/3yYc4jE4RG41aEwJAthlbTupBjw="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇬_1"
      - "🇸🇬_2"
      - "🇸🇬_3"
      - "🇸🇬_4"
      - "🇸🇬_5"
      - "🇸🇬_6"
      - "🇸🇬_7"
      - "🇸🇬_8"
      - "🇸🇬_9"
      - "🇸🇬_10"
      - "🇸🇬_11"
      - "🇸🇬_12"
      - "🇸🇬_13"
      - "🇸🇬_14"
      - "🇸🇬_15"
      - "🇸🇬_16"
      - "🇸🇬_17"
      - "🇸🇬_18"
      - "🇸🇬_19"
      - "🇸🇬_20"
      - "🇸🇬_21"
      - "🇸🇬_22"
      - "🇸🇬_23"
      - "🇸🇬_24"
      - "🇸🇬_25"
      - "🇸🇬_26"
      - "🇸🇬_27"
      - "🇸🇬_28"
      - "🇸🇬_29"
      - "🇸🇬_30"
      - "🇸🇬_31"
      - "🇸🇬_32"
      - "🇸🇬_33"
      - "🇸🇬_34"
      - "🇸🇬_35"
      - "🇸🇬_36"
      - "🇸🇬_37"
      - "🇸🇬_38"
      - "🇸🇬_39"
      - "🇸🇬_40"
      - "🇸🇬_41"
      - "🇸🇬_42"
      - "🇸🇬_43"
      - "🇸🇬_44"
      - "🇸🇬_45"
      - "🇸🇬_46"
      - "🇸🇬_47"
      - "🇸🇬_48"
      - "🇸🇬_49"
      - "🇸🇬_50"
      - "🇸🇬_51"


rules:
  - MATCH,PROXY
