name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇸🇬_1"
    type: vless
    server: "13.212.211.73"
    port: 20221
    uuid: "9f752e03-411f-4df4-841f-a23c4c43d183"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "Fd3DtGiQyvw9IBKoMqKtgaKVkdvjnaErL_1ib-zXqxY"
      short-id: "85ae3d83d037b7"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_2"
    type: vless
    server: "206.206.78.36"
    port: 443
    uuid: "e3f0c894-0f76-4683-a751-6a93da8fd14d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "UOLfRKeEoVxkp-APTF2OlvFkKSoiR2mWzUuhSWxcVmQ"
      short-id: "133a3f10a1581047"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_3"
    type: vless
    server: "13.212.10.131"
    port: 30666
    uuid: "37834c00-7fa5-46ba-a4b9-7e13c8fcdf8f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    reality-opts:
      public-key: "3fKobetnIIC1NFGtQEPkBx75UdTMmq886OAr9bOt2S4"
      short-id: "c919090e3c660c"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_4"
    type: vless
    server: "54.255.121.205"
    port: 43840
    uuid: "f053b140-9673-4ac5-bc8b-587bfd2c8fd8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.sony.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "tDzxVcXg6zzA1r0I_1j2y4vE0zkgmIVX3_Jf0UG1AnA"
      short-id: "ac4b9f02123aa50b"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_5"
    type: vless
    server: "54.169.200.246"
    port: 41688
    uuid: "49c0aac1-5e05-4f04-b624-248fc59e03c4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "srwIElIGTPs0kshpN1vvPsn4wixV_pLd56y_v9m0sTk"
      short-id: "7f342137c20387"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_6"
    type: vless
    server: "47.129.204.35"
    port: 58335
    uuid: "0f4ce6d4-b4b4-41b9-b1e7-c109ad32b274"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.tesla.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "5uFce3cR8rT889d0IDLpENoFf9OnFXaOoO9B8mI8cWQ"
      short-id: "6ce3397cbd5ada"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_7"
    type: vless
    server: "3.0.111.82"
    port: 12972
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_8"
    type: vless
    server: "54.251.224.5"
    port: 26017
    uuid: "d318cdac-0033-4b6e-98bf-35116e79c93f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "cy4ePzAdSz4pqRmAXXchMIgSoSKo8qjq2qLk5805LRA"
      short-id: "af1c2e33b0c7dad7"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_9"
    type: vless
    server: "142.91.102.35"
    port: 443
    uuid: "54a9c202-cfe9-4bb8-826c-653a52a96c6d"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "8.sahanwickramasinghe.me"
    client-fingerprint: "qq"
  - name: "🇸🇬_10"
    type: vless
    server: "146.235.16.130"
    port: 19825
    uuid: "2d1ad594-80a4-4bfb-87a6-038e39701f51"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sg2-8sb.6121999.dpdns.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "GvvkY8xYb9QjvwvzYq_uNC4tOGd0DCxRnz6770-xgkI"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_11"
    type: vless
    server: "3.0.111.82"
    port: 17623
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_12"
    type: vless
    server: "13.229.44.152"
    port: 34033
    uuid: "b5138354-066a-4e9f-93e3-5bc700eaf89f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.amd.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "R1mts7yXplVMaA15AC1U0TMnYvqiX3OPbK1_ZBan_XQ"
      short-id: "702186e48d5646"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_13"
    type: vless
    server: "47.129.185.35"
    port: 49805
    uuid: "0803fc94-25f9-42db-9e6b-dd1418ae50ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "KhyeJbZtFAik5Mx1K_AQMIEK_MPwQnwUwSe-jTjq8yU"
      short-id: "4a753538b6a9eee9"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_14"
    type: vless
    server: "sg2-8sb.6121999.dpdns.org"
    port: 19825
    uuid: "2d1ad594-80a4-4bfb-87a6-038e39701f51"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sg2-8sb.6121999.dpdns.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "GvvkY8xYb9QjvwvzYq_uNC4tOGd0DCxRnz6770-xgkI"
      short-id: "6ba85179e30d4fc2"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_15"
    type: vless
    server: "46.137.202.178"
    port: 12512
    uuid: "2a6c617d-98e4-49c3-95ab-76f02fcf0150"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sO0RBMr_l8TLtZaYBX8n3NdI9AtaugUqJpCR1szNsyA"
      short-id: "e692a8250d2e2fd0"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_16"
    type: vless
    server: "54.251.9.130"
    port: 24146
    uuid: "9d9a048b-3aea-4b3e-b106-1106bf301feb"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.intel.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "VeluC9A7XDurAWQNgXKShS2SJSgoK79QHFgiAMYrvGo"
      short-id: "7205d9079521832c"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_17"
    type: vless
    server: "134.122.154.210"
    port: 443
    uuid: "7f549a50-4655-46b6-962d-183cfc532fc9"
    udp: true
  - name: "🇸🇬_18"
    type: vless
    server: "91.192.81.214"
    port: 443
    uuid: "607801ac-dbdd-4938-a167-129015d9978e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "bMcyxNueltQhz5Kuxcf8odDStWHowYfLhKNdCbUweDc"
      short-id: "d1742269"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_19"
    type: vless
    server: "3.0.111.82"
    port: 10574
    uuid: "814bd064-544d-4255-a070-5705c03f6da9"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "k2hPp0tTW0Da-HK94wYpSCLbuK44LfGqC2MSJIM1Ti0"
      short-id: "48050fab"
    flow: "xtls-rprx-vision"
  - name: "🇸🇬_20"
    type: trojan
    server: "86.38.247.109"
    port: 2087
    password: "sshs8_6481354771"
    sni: "ul-singapore1.09vpn.com"
    skip-cert-verify: true
    udp: true
  - name: "🇸🇬_21"
    type: ss
    server: "167.150.100.115"
    port: 27755
    cipher: "2022-blake3-aes-256-gcm"
    password: "fnvo82p9y4AKykZXyIFtnodFy6fQmWnVlI2SvGleOB0="
    udp: true
  - name: "🇸🇬_22"
    type: ss
    server: "167.150.100.115"
    port: 27755
    cipher: "2022-blake3-aes-256-gcm"
    password: "fnvo82p9y4AKykZXyIFtnodFy6fQmWnVlI2SvGleOB0="
    udp: true
  - name: "🇸🇬_23"
    type: ss
    server: "176.97.64.144"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "TFElG2FVqyqG"
    udp: true
  - name: "🇸🇬_24"
    type: ss
    server: "167.150.100.115"
    port: 27755
    cipher: "2022-blake3-aes-256-gcm"
    password: "fnvo82p9y4AKykZXyIFtnodFy6fQmWnVlI2SvGleOB0="
    udp: true
  - name: "🇸🇬_25"
    type: ss
    server: "129.150.41.188"
    port: 56927
    cipher: "2022-blake3-chacha20-poly1305"
    password: "3xm2WUDvZ0PZH9tUl32lpOiKj+Lzm9LfHDGWl2YxG/4="
    udp: true
  - name: "🇸🇬_26"
    type: ss
    server: "129.150.59.74"
    port: 14384
    cipher: "2022-blake3-aes-256-gcm"
    password: "sUR6Ny8Y6PSvHhl/DUxconwxg6VZyFdsdfaVCvEatJo=:7bTEhHgpErKiRjE1ega+H6pcpJsNLFB0CjQseujAHrA="
    udp: true
  - name: "🇸🇬_27"
    type: ss
    server: "176.97.64.144"
    port: 8388
    cipher: "chacha20-ietf-poly1305"
    password: "TFElG2FVqyqG"
    udp: true
  - name: "🇸🇬_28"
    type: ss
    server: "146.235.19.129"
    port: 56927
    cipher: "2022-blake3-chacha20-poly1305"
    password: "i699dvro3+yyb9U6o3qsojnoZw2MsymfU8jhW6SzVLg="
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇸🇬_1"
      - "🇸🇬_2"
      - "🇸🇬_3"
      - "🇸🇬_4"
      - "🇸🇬_5"
      - "🇸🇬_6"
      - "🇸🇬_7"
      - "🇸🇬_8"
      - "🇸🇬_9"
      - "🇸🇬_10"
      - "🇸🇬_11"
      - "🇸🇬_12"
      - "🇸🇬_13"
      - "🇸🇬_14"
      - "🇸🇬_15"
      - "🇸🇬_16"
      - "🇸🇬_17"
      - "🇸🇬_18"
      - "🇸🇬_19"
      - "🇸🇬_20"
      - "🇸🇬_21"
      - "🇸🇬_22"
      - "🇸🇬_23"
      - "🇸🇬_24"
      - "🇸🇬_25"
      - "🇸🇬_26"
      - "🇸🇬_27"
      - "🇸🇬_28"


rules:
  - MATCH,PROXY
