name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "93.190.8.19"
    port: 3090
    uuid: "6687af93-eb39-47a3-9a73-0f79234ef507"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_2"
    type: vless
    server: "167.104.219.66"
    port: 18361
    uuid: "My-chanel-Telegram-ATOVPN "
    udp: true
  - name: "🇹🇷_3"
    type: vless
    server: "185.113.223.183"
    port: 8443
    uuid: "d342d11e-d424-4583-b36e-524ab1f0afa4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cdn8848.776676.xyz"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/channels/act"
      headers:
        Host: "cdn8848.776676.xyz"
  - name: "🇹🇷_4"
    type: vless
    server: "89.251.8.205"
    port: 80
    uuid: "c0e453eb-33ac-4206-8423-3e1286c2ba7a"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "play.google.com"
  - name: "🇹🇷_5"
    type: vless
    server: "93.190.9.23"
    port: 3090
    uuid: "2ff150f3-705a-4699-ba63-3dd743942a67"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_6"
    type: vless
    server: "78.135.73.47"
    port: 443
    uuid: "25e16692-d097-4e69-9e2d-8415609c1968"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.datadoghq.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "sZAJkAu23wp1WKY-qeaeiwR38izP5OyfhumoE9xhbB8"
      short-id: "f46cd3ea3d1eb72d"
    flow: "xtls-rprx-vision"
  - name: "🇹🇷_7"
    type: vless
    server: "93.190.9.2"
    port: 3090
    uuid: "eeccb1d3-2d30-439e-b4c7-895f84c41f03"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇹🇷_8"
    type: vless
    server: "151.241.226.201"
    port: 2053
    uuid: "0eed6293-8cf1-4e77-ac10-9c3d50d0b2f8"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.apple.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "bYW_MmB_CUHrsyoCAUKviI2LZdHf63yY2yOPXbih104"
      short-id: "9e419c0759b54d6f"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"
      - "🇹🇷_7"
      - "🇹🇷_8"


rules:
  - MATCH,PROXY
