name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇹🇷_1"
    type: vless
    server: "213.156.152.98"
    port: 8443
    uuid: "f1505323-ecb6-4152-9a5b-d37b3ae1cacf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play-apps-features.googleusercontent.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "0h-taEebHyMkglCVL878JFgy3OH98A6_ER_Z3_mVKxs"
      short-id: "e9eb3da9b21742de"
  - name: "🇹🇷_2"
    type: vless
    server: "202.133.90.93"
    port: 8444
    uuid: "0b39a009-2a2a-4035-ba87-cc82894f8e21"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "connect3.nyxserver.ir"
    client-fingerprint: "firefox"
  - name: "🇹🇷_3"
    type: vless
    server: "195.162.69.203"
    port: 8443
    uuid: "953358cb-82ba-4296-960d-6d2ec3468f4c"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "195-162-69-203.sslip.io"
    client-fingerprint: "chrome"
  - name: "🇹🇷_4"
    type: vless
    server: "45.74.178.209"
    port: 32306
    uuid: "f1505323-ecb6-4152-9a5b-d37b3ae1cacf"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "play-apps-features.googleusercontent.com"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "SXkGZe1mcU3mqQHdr-8izIYr1YQvsAYf_jgFnO85kW0"
      short-id: "c03b6ff9e11d0a5d"
  - name: "🇹🇷_5"
    type: vless
    server: "206.1.96.228"
    port: 8082
    uuid: "bfb3f06c-e33f-41ac-b101-012c8325a689"
    udp: true
  - name: "🇹🇷_6"
    type: vless
    server: "156.67.63.231"
    port: 443
    uuid: "b052df40-d51c-456c-9bd6-57af01a87e4e"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "sync-bridge.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "PTqeBbbr2xJ1L3V1PyYjKjxanMKKqJHU-wtnpYmFQCI"
      short-id: "5606d4a25c99e7af"
    flow: "xtls-rprx-vision"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇹🇷_1"
      - "🇹🇷_2"
      - "🇹🇷_3"
      - "🇹🇷_4"
      - "🇹🇷_5"
      - "🇹🇷_6"


rules:
  - MATCH,PROXY
