name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇺🇦_1"
    type: vless
    server: "5.34.182.23"
    port: 443
    uuid: "423b1d79-08c4-403f-9d5e-c541f791b55f"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "eu-central.cendora.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI"
      short-id: "00bca5982f82d083"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_2"
    type: vless
    server: "89.116.180.40"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime09.workers.dev"
  - name: "🇺🇦_3"
    type: vless
    server: "s282.wagahaha.xyz"
    port: 443
    uuid: "41f4cb15-5a3f-3934-89fe-b4177146adf4"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "u643766ubdb325a3s274.kukuss.top"
    client-fingerprint: "firefox"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_4"
    type: vless
    server: "89.116.180.30"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "vms.lifetime09.workers.dev"
  - name: "🇺🇦_5"
    type: vless
    server: "91.224.87.22"
    port: 9873
    uuid: "14777bd9-56a5-46f6-a94f-826b4800dc05"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "dl.google.com"
    client-fingerprint: "qq"
    reality-opts:
      public-key: "bnRIb3Er1i-K6NGGByCO9UbGfOvu43ZoiK7ulPd1SzU"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "grpc-tunnel"
  - name: "🇺🇦_6"
    type: vless
    server: "193.238.153.15"
    port: 443
    uuid: "40cfbd0a-f133-4174-8e03-ab0e587e1099"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.cloudflare.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "dzknsuwujuOacNHTXzdPxBLNUEJfEImiwLinPPNFmwU"
      short-id: "1ea21a140beaecc5"
    flow: "xtls-rprx-vision"
  - name: "🇺🇦_7"
    type: trojan
    server: "89.116.180.49"
    port: 443
    password: "f18d6149-e214-8554-e737-f7523c8b2eea"
    sni: "0403.infinityconfig4.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sync"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇺🇦_1"
      - "🇺🇦_2"
      - "🇺🇦_3"
      - "🇺🇦_4"
      - "🇺🇦_5"
      - "🇺🇦_6"
      - "🇺🇦_7"


rules:
  - MATCH,PROXY
