name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 94.140.14.14
    - 64.6.64.6
    - 84.200.69.80
    - 76.76.19.19
    - 8.26.56.26
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://doh.comodo.com/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family

proxies:
  - name: "🇺🇦_1"
    type: vless
    server: "104.245.240.9"
    port: 8443
    uuid: "bb20d3fc-fc15-0935-11c5-82775c39e6b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "download.nvidia.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "D2SXHZRRYM0WcFChGWd57XB-U73aIsGfMpe2-Gq5XSs"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇺🇦_2"
    type: vless
    server: "104.143.223.69"
    port: 2085
    uuid: "f68a9fd4-16c7-46d1-b17c-0a4b224cc00d"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇺🇦_3"
    type: vless
    server: "104.245.240.8"
    port: 8443
    uuid: "bb20d3fc-fc15-0935-11c5-82775c39e6b0"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.epson.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "-GbQJg3bnEGEVFjVaRRu01cgF1f0K_maI4d5MWtMb28"
      short-id: ""
    network: grpc
    grpc-opts:
      grpc-service-name: "TunService"
  - name: "🇺🇦_4"
    type: vless
    server: "89.116.180.40"
    port: 8880
    uuid: "6202b230-417c-4d8e-b624-0f71afa9c75d"
    udp: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: "vms.lifetime09.workers.dev"
  - name: "🇺🇦_5"
    type: vless
    server: "104.143.223.71"
    port: 2085
    uuid: "3f654175-4f83-47ec-8ce2-f2bf0d160b27"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇺🇦_6"
    type: vless
    server: "104.143.223.82"
    port: 2085
    uuid: "15295b3e-e233-4f3b-95d1-8860d40c75fe"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇺🇦_7"
    type: vless
    server: "104.143.223.56"
    port: 2085
    uuid: "b41bac9b-17f7-469f-9df0-05b09140081b"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: "vless"
  - name: "🇺🇦_8"
    type: trojan
    server: "89.116.180.49"
    port: 443
    password: "f18d6149-e214-8554-e737-f7523c8b2eea"
    sni: "0403.infinityconfig4.workers.dev"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/sync"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Auto"

  - name: "Auto"
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 180
    tolerance: 30
    lazy: true
    proxies:
      - "🇺🇦_1"
      - "🇺🇦_2"
      - "🇺🇦_3"
      - "🇺🇦_4"
      - "🇺🇦_5"
      - "🇺🇦_6"
      - "🇺🇦_7"
      - "🇺🇦_8"


rules:
  - MATCH,PROXY
